/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.children.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateChildAttributes.Builder.class)
public final class UpdateChildAttributes {
    private final Optional<String> name;

    private final Optional<String> externalId;

    private final Optional<List<String>> bins;

    private final Map<String, Object> additionalProperties;

    private UpdateChildAttributes(
            Optional<String> name,
            Optional<String> externalId,
            Optional<List<String>> bins,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.externalId = externalId;
        this.bins = bins;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return New name for the child organization (must be uppercase, no spaces)
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return External identifier for the child organization
     */
    @JsonProperty("externalId")
    public Optional<String> getExternalId() {
        return externalId;
    }

    /**
     * @return Bank Identification Numbers for the child organization
     */
    @JsonProperty("bins")
    public Optional<List<String>> getBins() {
        return bins;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateChildAttributes && equalTo((UpdateChildAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateChildAttributes other) {
        return name.equals(other.name) && externalId.equals(other.externalId) && bins.equals(other.bins);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.externalId, this.bins);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> externalId = Optional.empty();

        private Optional<List<String>> bins = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateChildAttributes other) {
            name(other.getName());
            externalId(other.getExternalId());
            bins(other.getBins());
            return this;
        }

        /**
         * <p>New name for the child organization (must be uppercase, no spaces)</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>External identifier for the child organization</p>
         */
        @JsonSetter(value = "externalId", nulls = Nulls.SKIP)
        public Builder externalId(Optional<String> externalId) {
            this.externalId = externalId;
            return this;
        }

        public Builder externalId(String externalId) {
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        /**
         * <p>Bank Identification Numbers for the child organization</p>
         */
        @JsonSetter(value = "bins", nulls = Nulls.SKIP)
        public Builder bins(Optional<List<String>> bins) {
            this.bins = bins;
            return this;
        }

        public Builder bins(List<String> bins) {
            this.bins = Optional.ofNullable(bins);
            return this;
        }

        public UpdateChildAttributes build() {
            return new UpdateChildAttributes(name, externalId, bins, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
