/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.txnmatching.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Offer.Builder.class)
public final class Offer {
    private final String id;

    private final String merchantId;

    private final List<String> merchantLocationIds;

    private final String category;

    private final String commissionType;

    private final double commissionValue;

    private final String createdDate;

    private final String expirationDate;

    private final boolean isLocationSpecific;

    private final Map<String, Double> issuerCommissionsMap;

    private final String lastModified;

    private final String merchantNetwork;

    private final String name;

    private final String offerType;

    private final List<String> qualifiedIssuer;

    private final String source;

    private final String startDate;

    private final String status;

    private final String terms;

    private final Map<String, Boolean> validOfferForIssuer;

    private final Map<String, Double> userCommissionsMap;

    private final List<String> audiences;

    private final boolean displayAlways;

    private final boolean isCustom;

    private final List<String> mcc;

    private final List<String> segments;

    private final int minRewardAmount;

    private final int maxRewardAmount;

    private final int minUserRewardAmount;

    private final int maxUserRewardAmount;

    private final boolean redeemableOnce;

    private final Map<String, Object> additionalProperties;

    private Offer(
            String id,
            String merchantId,
            List<String> merchantLocationIds,
            String category,
            String commissionType,
            double commissionValue,
            String createdDate,
            String expirationDate,
            boolean isLocationSpecific,
            Map<String, Double> issuerCommissionsMap,
            String lastModified,
            String merchantNetwork,
            String name,
            String offerType,
            List<String> qualifiedIssuer,
            String source,
            String startDate,
            String status,
            String terms,
            Map<String, Boolean> validOfferForIssuer,
            Map<String, Double> userCommissionsMap,
            List<String> audiences,
            boolean displayAlways,
            boolean isCustom,
            List<String> mcc,
            List<String> segments,
            int minRewardAmount,
            int maxRewardAmount,
            int minUserRewardAmount,
            int maxUserRewardAmount,
            boolean redeemableOnce,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.merchantId = merchantId;
        this.merchantLocationIds = merchantLocationIds;
        this.category = category;
        this.commissionType = commissionType;
        this.commissionValue = commissionValue;
        this.createdDate = createdDate;
        this.expirationDate = expirationDate;
        this.isLocationSpecific = isLocationSpecific;
        this.issuerCommissionsMap = issuerCommissionsMap;
        this.lastModified = lastModified;
        this.merchantNetwork = merchantNetwork;
        this.name = name;
        this.offerType = offerType;
        this.qualifiedIssuer = qualifiedIssuer;
        this.source = source;
        this.startDate = startDate;
        this.status = status;
        this.terms = terms;
        this.validOfferForIssuer = validOfferForIssuer;
        this.userCommissionsMap = userCommissionsMap;
        this.audiences = audiences;
        this.displayAlways = displayAlways;
        this.isCustom = isCustom;
        this.mcc = mcc;
        this.segments = segments;
        this.minRewardAmount = minRewardAmount;
        this.maxRewardAmount = maxRewardAmount;
        this.minUserRewardAmount = minUserRewardAmount;
        this.maxUserRewardAmount = maxUserRewardAmount;
        this.redeemableOnce = redeemableOnce;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("_id")
    public String getId() {
        return id;
    }

    @JsonProperty("merchantId")
    public String getMerchantId() {
        return merchantId;
    }

    @JsonProperty("merchantLocationIds")
    public List<String> getMerchantLocationIds() {
        return merchantLocationIds;
    }

    @JsonProperty("category")
    public String getCategory() {
        return category;
    }

    @JsonProperty("commissionType")
    public String getCommissionType() {
        return commissionType;
    }

    @JsonProperty("commissionValue")
    public double getCommissionValue() {
        return commissionValue;
    }

    @JsonProperty("createdDate")
    public String getCreatedDate() {
        return createdDate;
    }

    @JsonProperty("expirationDate")
    public String getExpirationDate() {
        return expirationDate;
    }

    @JsonProperty("isLocationSpecific")
    public boolean getIsLocationSpecific() {
        return isLocationSpecific;
    }

    @JsonProperty("issuerCommissionsMap")
    public Map<String, Double> getIssuerCommissionsMap() {
        return issuerCommissionsMap;
    }

    @JsonProperty("lastModified")
    public String getLastModified() {
        return lastModified;
    }

    @JsonProperty("merchantNetwork")
    public String getMerchantNetwork() {
        return merchantNetwork;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("offerType")
    public String getOfferType() {
        return offerType;
    }

    @JsonProperty("qualifiedIssuer")
    public List<String> getQualifiedIssuer() {
        return qualifiedIssuer;
    }

    @JsonProperty("source")
    public String getSource() {
        return source;
    }

    @JsonProperty("startDate")
    public String getStartDate() {
        return startDate;
    }

    @JsonProperty("status")
    public String getStatus() {
        return status;
    }

    @JsonProperty("terms")
    public String getTerms() {
        return terms;
    }

    @JsonProperty("validOfferForIssuer")
    public Map<String, Boolean> getValidOfferForIssuer() {
        return validOfferForIssuer;
    }

    @JsonProperty("userCommissionsMap")
    public Map<String, Double> getUserCommissionsMap() {
        return userCommissionsMap;
    }

    @JsonProperty("audiences")
    public List<String> getAudiences() {
        return audiences;
    }

    @JsonProperty("displayAlways")
    public boolean getDisplayAlways() {
        return displayAlways;
    }

    @JsonProperty("isCustom")
    public boolean getIsCustom() {
        return isCustom;
    }

    @JsonProperty("mcc")
    public List<String> getMcc() {
        return mcc;
    }

    @JsonProperty("segments")
    public List<String> getSegments() {
        return segments;
    }

    @JsonProperty("minRewardAmount")
    public int getMinRewardAmount() {
        return minRewardAmount;
    }

    @JsonProperty("maxRewardAmount")
    public int getMaxRewardAmount() {
        return maxRewardAmount;
    }

    @JsonProperty("minUserRewardAmount")
    public int getMinUserRewardAmount() {
        return minUserRewardAmount;
    }

    @JsonProperty("maxUserRewardAmount")
    public int getMaxUserRewardAmount() {
        return maxUserRewardAmount;
    }

    @JsonProperty("redeemableOnce")
    public boolean getRedeemableOnce() {
        return redeemableOnce;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Offer && equalTo((Offer) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Offer other) {
        return id.equals(other.id)
                && merchantId.equals(other.merchantId)
                && merchantLocationIds.equals(other.merchantLocationIds)
                && category.equals(other.category)
                && commissionType.equals(other.commissionType)
                && commissionValue == other.commissionValue
                && createdDate.equals(other.createdDate)
                && expirationDate.equals(other.expirationDate)
                && isLocationSpecific == other.isLocationSpecific
                && issuerCommissionsMap.equals(other.issuerCommissionsMap)
                && lastModified.equals(other.lastModified)
                && merchantNetwork.equals(other.merchantNetwork)
                && name.equals(other.name)
                && offerType.equals(other.offerType)
                && qualifiedIssuer.equals(other.qualifiedIssuer)
                && source.equals(other.source)
                && startDate.equals(other.startDate)
                && status.equals(other.status)
                && terms.equals(other.terms)
                && validOfferForIssuer.equals(other.validOfferForIssuer)
                && userCommissionsMap.equals(other.userCommissionsMap)
                && audiences.equals(other.audiences)
                && displayAlways == other.displayAlways
                && isCustom == other.isCustom
                && mcc.equals(other.mcc)
                && segments.equals(other.segments)
                && minRewardAmount == other.minRewardAmount
                && maxRewardAmount == other.maxRewardAmount
                && minUserRewardAmount == other.minUserRewardAmount
                && maxUserRewardAmount == other.maxUserRewardAmount
                && redeemableOnce == other.redeemableOnce;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.merchantId,
                this.merchantLocationIds,
                this.category,
                this.commissionType,
                this.commissionValue,
                this.createdDate,
                this.expirationDate,
                this.isLocationSpecific,
                this.issuerCommissionsMap,
                this.lastModified,
                this.merchantNetwork,
                this.name,
                this.offerType,
                this.qualifiedIssuer,
                this.source,
                this.startDate,
                this.status,
                this.terms,
                this.validOfferForIssuer,
                this.userCommissionsMap,
                this.audiences,
                this.displayAlways,
                this.isCustom,
                this.mcc,
                this.segments,
                this.minRewardAmount,
                this.maxRewardAmount,
                this.minUserRewardAmount,
                this.maxUserRewardAmount,
                this.redeemableOnce);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        MerchantIdStage id(@NotNull String id);

        Builder from(Offer other);
    }

    public interface MerchantIdStage {
        CategoryStage merchantId(@NotNull String merchantId);
    }

    public interface CategoryStage {
        CommissionTypeStage category(@NotNull String category);
    }

    public interface CommissionTypeStage {
        CommissionValueStage commissionType(@NotNull String commissionType);
    }

    public interface CommissionValueStage {
        CreatedDateStage commissionValue(double commissionValue);
    }

    public interface CreatedDateStage {
        ExpirationDateStage createdDate(@NotNull String createdDate);
    }

    public interface ExpirationDateStage {
        IsLocationSpecificStage expirationDate(@NotNull String expirationDate);
    }

    public interface IsLocationSpecificStage {
        LastModifiedStage isLocationSpecific(boolean isLocationSpecific);
    }

    public interface LastModifiedStage {
        MerchantNetworkStage lastModified(@NotNull String lastModified);
    }

    public interface MerchantNetworkStage {
        NameStage merchantNetwork(@NotNull String merchantNetwork);
    }

    public interface NameStage {
        OfferTypeStage name(@NotNull String name);
    }

    public interface OfferTypeStage {
        SourceStage offerType(@NotNull String offerType);
    }

    public interface SourceStage {
        StartDateStage source(@NotNull String source);
    }

    public interface StartDateStage {
        StatusStage startDate(@NotNull String startDate);
    }

    public interface StatusStage {
        TermsStage status(@NotNull String status);
    }

    public interface TermsStage {
        DisplayAlwaysStage terms(@NotNull String terms);
    }

    public interface DisplayAlwaysStage {
        IsCustomStage displayAlways(boolean displayAlways);
    }

    public interface IsCustomStage {
        MinRewardAmountStage isCustom(boolean isCustom);
    }

    public interface MinRewardAmountStage {
        MaxRewardAmountStage minRewardAmount(int minRewardAmount);
    }

    public interface MaxRewardAmountStage {
        MinUserRewardAmountStage maxRewardAmount(int maxRewardAmount);
    }

    public interface MinUserRewardAmountStage {
        MaxUserRewardAmountStage minUserRewardAmount(int minUserRewardAmount);
    }

    public interface MaxUserRewardAmountStage {
        RedeemableOnceStage maxUserRewardAmount(int maxUserRewardAmount);
    }

    public interface RedeemableOnceStage {
        _FinalStage redeemableOnce(boolean redeemableOnce);
    }

    public interface _FinalStage {
        Offer build();

        _FinalStage merchantLocationIds(List<String> merchantLocationIds);

        _FinalStage addMerchantLocationIds(String merchantLocationIds);

        _FinalStage addAllMerchantLocationIds(List<String> merchantLocationIds);

        _FinalStage issuerCommissionsMap(Map<String, Double> issuerCommissionsMap);

        _FinalStage putAllIssuerCommissionsMap(Map<String, Double> issuerCommissionsMap);

        _FinalStage issuerCommissionsMap(String key, Double value);

        _FinalStage qualifiedIssuer(List<String> qualifiedIssuer);

        _FinalStage addQualifiedIssuer(String qualifiedIssuer);

        _FinalStage addAllQualifiedIssuer(List<String> qualifiedIssuer);

        _FinalStage validOfferForIssuer(Map<String, Boolean> validOfferForIssuer);

        _FinalStage putAllValidOfferForIssuer(Map<String, Boolean> validOfferForIssuer);

        _FinalStage validOfferForIssuer(String key, Boolean value);

        _FinalStage userCommissionsMap(Map<String, Double> userCommissionsMap);

        _FinalStage putAllUserCommissionsMap(Map<String, Double> userCommissionsMap);

        _FinalStage userCommissionsMap(String key, Double value);

        _FinalStage audiences(List<String> audiences);

        _FinalStage addAudiences(String audiences);

        _FinalStage addAllAudiences(List<String> audiences);

        _FinalStage mcc(List<String> mcc);

        _FinalStage addMcc(String mcc);

        _FinalStage addAllMcc(List<String> mcc);

        _FinalStage segments(List<String> segments);

        _FinalStage addSegments(String segments);

        _FinalStage addAllSegments(List<String> segments);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    MerchantIdStage,
                    CategoryStage,
                    CommissionTypeStage,
                    CommissionValueStage,
                    CreatedDateStage,
                    ExpirationDateStage,
                    IsLocationSpecificStage,
                    LastModifiedStage,
                    MerchantNetworkStage,
                    NameStage,
                    OfferTypeStage,
                    SourceStage,
                    StartDateStage,
                    StatusStage,
                    TermsStage,
                    DisplayAlwaysStage,
                    IsCustomStage,
                    MinRewardAmountStage,
                    MaxRewardAmountStage,
                    MinUserRewardAmountStage,
                    MaxUserRewardAmountStage,
                    RedeemableOnceStage,
                    _FinalStage {
        private String id;

        private String merchantId;

        private String category;

        private String commissionType;

        private double commissionValue;

        private String createdDate;

        private String expirationDate;

        private boolean isLocationSpecific;

        private String lastModified;

        private String merchantNetwork;

        private String name;

        private String offerType;

        private String source;

        private String startDate;

        private String status;

        private String terms;

        private boolean displayAlways;

        private boolean isCustom;

        private int minRewardAmount;

        private int maxRewardAmount;

        private int minUserRewardAmount;

        private int maxUserRewardAmount;

        private boolean redeemableOnce;

        private List<String> segments = new ArrayList<>();

        private List<String> mcc = new ArrayList<>();

        private List<String> audiences = new ArrayList<>();

        private Map<String, Double> userCommissionsMap = new LinkedHashMap<>();

        private Map<String, Boolean> validOfferForIssuer = new LinkedHashMap<>();

        private List<String> qualifiedIssuer = new ArrayList<>();

        private Map<String, Double> issuerCommissionsMap = new LinkedHashMap<>();

        private List<String> merchantLocationIds = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Offer other) {
            id(other.getId());
            merchantId(other.getMerchantId());
            merchantLocationIds(other.getMerchantLocationIds());
            category(other.getCategory());
            commissionType(other.getCommissionType());
            commissionValue(other.getCommissionValue());
            createdDate(other.getCreatedDate());
            expirationDate(other.getExpirationDate());
            isLocationSpecific(other.getIsLocationSpecific());
            issuerCommissionsMap(other.getIssuerCommissionsMap());
            lastModified(other.getLastModified());
            merchantNetwork(other.getMerchantNetwork());
            name(other.getName());
            offerType(other.getOfferType());
            qualifiedIssuer(other.getQualifiedIssuer());
            source(other.getSource());
            startDate(other.getStartDate());
            status(other.getStatus());
            terms(other.getTerms());
            validOfferForIssuer(other.getValidOfferForIssuer());
            userCommissionsMap(other.getUserCommissionsMap());
            audiences(other.getAudiences());
            displayAlways(other.getDisplayAlways());
            isCustom(other.getIsCustom());
            mcc(other.getMcc());
            segments(other.getSegments());
            minRewardAmount(other.getMinRewardAmount());
            maxRewardAmount(other.getMaxRewardAmount());
            minUserRewardAmount(other.getMinUserRewardAmount());
            maxUserRewardAmount(other.getMaxUserRewardAmount());
            redeemableOnce(other.getRedeemableOnce());
            return this;
        }

        @java.lang.Override
        @JsonSetter("_id")
        public MerchantIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("merchantId")
        public CategoryStage merchantId(@NotNull String merchantId) {
            this.merchantId = Objects.requireNonNull(merchantId, "merchantId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("category")
        public CommissionTypeStage category(@NotNull String category) {
            this.category = Objects.requireNonNull(category, "category must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("commissionType")
        public CommissionValueStage commissionType(@NotNull String commissionType) {
            this.commissionType = Objects.requireNonNull(commissionType, "commissionType must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("commissionValue")
        public CreatedDateStage commissionValue(double commissionValue) {
            this.commissionValue = commissionValue;
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdDate")
        public ExpirationDateStage createdDate(@NotNull String createdDate) {
            this.createdDate = Objects.requireNonNull(createdDate, "createdDate must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("expirationDate")
        public IsLocationSpecificStage expirationDate(@NotNull String expirationDate) {
            this.expirationDate = Objects.requireNonNull(expirationDate, "expirationDate must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("isLocationSpecific")
        public LastModifiedStage isLocationSpecific(boolean isLocationSpecific) {
            this.isLocationSpecific = isLocationSpecific;
            return this;
        }

        @java.lang.Override
        @JsonSetter("lastModified")
        public MerchantNetworkStage lastModified(@NotNull String lastModified) {
            this.lastModified = Objects.requireNonNull(lastModified, "lastModified must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("merchantNetwork")
        public NameStage merchantNetwork(@NotNull String merchantNetwork) {
            this.merchantNetwork = Objects.requireNonNull(merchantNetwork, "merchantNetwork must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public OfferTypeStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("offerType")
        public SourceStage offerType(@NotNull String offerType) {
            this.offerType = Objects.requireNonNull(offerType, "offerType must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("source")
        public StartDateStage source(@NotNull String source) {
            this.source = Objects.requireNonNull(source, "source must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("startDate")
        public StatusStage startDate(@NotNull String startDate) {
            this.startDate = Objects.requireNonNull(startDate, "startDate must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public TermsStage status(@NotNull String status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("terms")
        public DisplayAlwaysStage terms(@NotNull String terms) {
            this.terms = Objects.requireNonNull(terms, "terms must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("displayAlways")
        public IsCustomStage displayAlways(boolean displayAlways) {
            this.displayAlways = displayAlways;
            return this;
        }

        @java.lang.Override
        @JsonSetter("isCustom")
        public MinRewardAmountStage isCustom(boolean isCustom) {
            this.isCustom = isCustom;
            return this;
        }

        @java.lang.Override
        @JsonSetter("minRewardAmount")
        public MaxRewardAmountStage minRewardAmount(int minRewardAmount) {
            this.minRewardAmount = minRewardAmount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("maxRewardAmount")
        public MinUserRewardAmountStage maxRewardAmount(int maxRewardAmount) {
            this.maxRewardAmount = maxRewardAmount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("minUserRewardAmount")
        public MaxUserRewardAmountStage minUserRewardAmount(int minUserRewardAmount) {
            this.minUserRewardAmount = minUserRewardAmount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("maxUserRewardAmount")
        public RedeemableOnceStage maxUserRewardAmount(int maxUserRewardAmount) {
            this.maxUserRewardAmount = maxUserRewardAmount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("redeemableOnce")
        public _FinalStage redeemableOnce(boolean redeemableOnce) {
            this.redeemableOnce = redeemableOnce;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllSegments(List<String> segments) {
            if (segments != null) {
                this.segments.addAll(segments);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addSegments(String segments) {
            this.segments.add(segments);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "segments", nulls = Nulls.SKIP)
        public _FinalStage segments(List<String> segments) {
            this.segments.clear();
            if (segments != null) {
                this.segments.addAll(segments);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllMcc(List<String> mcc) {
            if (mcc != null) {
                this.mcc.addAll(mcc);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addMcc(String mcc) {
            this.mcc.add(mcc);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "mcc", nulls = Nulls.SKIP)
        public _FinalStage mcc(List<String> mcc) {
            this.mcc.clear();
            if (mcc != null) {
                this.mcc.addAll(mcc);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllAudiences(List<String> audiences) {
            if (audiences != null) {
                this.audiences.addAll(audiences);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAudiences(String audiences) {
            this.audiences.add(audiences);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "audiences", nulls = Nulls.SKIP)
        public _FinalStage audiences(List<String> audiences) {
            this.audiences.clear();
            if (audiences != null) {
                this.audiences.addAll(audiences);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage userCommissionsMap(String key, Double value) {
            this.userCommissionsMap.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllUserCommissionsMap(Map<String, Double> userCommissionsMap) {
            if (userCommissionsMap != null) {
                this.userCommissionsMap.putAll(userCommissionsMap);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "userCommissionsMap", nulls = Nulls.SKIP)
        public _FinalStage userCommissionsMap(Map<String, Double> userCommissionsMap) {
            this.userCommissionsMap.clear();
            if (userCommissionsMap != null) {
                this.userCommissionsMap.putAll(userCommissionsMap);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage validOfferForIssuer(String key, Boolean value) {
            this.validOfferForIssuer.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllValidOfferForIssuer(Map<String, Boolean> validOfferForIssuer) {
            if (validOfferForIssuer != null) {
                this.validOfferForIssuer.putAll(validOfferForIssuer);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "validOfferForIssuer", nulls = Nulls.SKIP)
        public _FinalStage validOfferForIssuer(Map<String, Boolean> validOfferForIssuer) {
            this.validOfferForIssuer.clear();
            if (validOfferForIssuer != null) {
                this.validOfferForIssuer.putAll(validOfferForIssuer);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllQualifiedIssuer(List<String> qualifiedIssuer) {
            if (qualifiedIssuer != null) {
                this.qualifiedIssuer.addAll(qualifiedIssuer);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addQualifiedIssuer(String qualifiedIssuer) {
            this.qualifiedIssuer.add(qualifiedIssuer);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "qualifiedIssuer", nulls = Nulls.SKIP)
        public _FinalStage qualifiedIssuer(List<String> qualifiedIssuer) {
            this.qualifiedIssuer.clear();
            if (qualifiedIssuer != null) {
                this.qualifiedIssuer.addAll(qualifiedIssuer);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage issuerCommissionsMap(String key, Double value) {
            this.issuerCommissionsMap.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllIssuerCommissionsMap(Map<String, Double> issuerCommissionsMap) {
            if (issuerCommissionsMap != null) {
                this.issuerCommissionsMap.putAll(issuerCommissionsMap);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "issuerCommissionsMap", nulls = Nulls.SKIP)
        public _FinalStage issuerCommissionsMap(Map<String, Double> issuerCommissionsMap) {
            this.issuerCommissionsMap.clear();
            if (issuerCommissionsMap != null) {
                this.issuerCommissionsMap.putAll(issuerCommissionsMap);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllMerchantLocationIds(List<String> merchantLocationIds) {
            if (merchantLocationIds != null) {
                this.merchantLocationIds.addAll(merchantLocationIds);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addMerchantLocationIds(String merchantLocationIds) {
            this.merchantLocationIds.add(merchantLocationIds);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "merchantLocationIds", nulls = Nulls.SKIP)
        public _FinalStage merchantLocationIds(List<String> merchantLocationIds) {
            this.merchantLocationIds.clear();
            if (merchantLocationIds != null) {
                this.merchantLocationIds.addAll(merchantLocationIds);
            }
            return this;
        }

        @java.lang.Override
        public Offer build() {
            return new Offer(
                    id,
                    merchantId,
                    merchantLocationIds,
                    category,
                    commissionType,
                    commissionValue,
                    createdDate,
                    expirationDate,
                    isLocationSpecific,
                    issuerCommissionsMap,
                    lastModified,
                    merchantNetwork,
                    name,
                    offerType,
                    qualifiedIssuer,
                    source,
                    startDate,
                    status,
                    terms,
                    validOfferForIssuer,
                    userCommissionsMap,
                    audiences,
                    displayAlways,
                    isCustom,
                    mcc,
                    segments,
                    minRewardAmount,
                    maxRewardAmount,
                    minUserRewardAmount,
                    maxUserRewardAmount,
                    redeemableOnce,
                    additionalProperties);
        }
    }
}
