/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.txnmatching.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ValidationErrorResult.Builder.class)
public final class ValidationErrorResult {
    private final ValidationStatus status;

    private final List<ValidationMetadata> failures;

    private final EnrichedTransactionRecord transaction;

    private final Map<String, Object> additionalProperties;

    private ValidationErrorResult(
            ValidationStatus status,
            List<ValidationMetadata> failures,
            EnrichedTransactionRecord transaction,
            Map<String, Object> additionalProperties) {
        this.status = status;
        this.failures = failures;
        this.transaction = transaction;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("status")
    public ValidationStatus getStatus() {
        return status;
    }

    @JsonProperty("failures")
    public List<ValidationMetadata> getFailures() {
        return failures;
    }

    @JsonProperty("transaction")
    public EnrichedTransactionRecord getTransaction() {
        return transaction;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ValidationErrorResult && equalTo((ValidationErrorResult) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ValidationErrorResult other) {
        return status.equals(other.status) && failures.equals(other.failures) && transaction.equals(other.transaction);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.status, this.failures, this.transaction);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StatusStage builder() {
        return new Builder();
    }

    public interface StatusStage {
        TransactionStage status(@NotNull ValidationStatus status);

        Builder from(ValidationErrorResult other);
    }

    public interface TransactionStage {
        _FinalStage transaction(@NotNull EnrichedTransactionRecord transaction);
    }

    public interface _FinalStage {
        ValidationErrorResult build();

        _FinalStage failures(List<ValidationMetadata> failures);

        _FinalStage addFailures(ValidationMetadata failures);

        _FinalStage addAllFailures(List<ValidationMetadata> failures);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements StatusStage, TransactionStage, _FinalStage {
        private ValidationStatus status;

        private EnrichedTransactionRecord transaction;

        private List<ValidationMetadata> failures = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ValidationErrorResult other) {
            status(other.getStatus());
            failures(other.getFailures());
            transaction(other.getTransaction());
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public TransactionStage status(@NotNull ValidationStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("transaction")
        public _FinalStage transaction(@NotNull EnrichedTransactionRecord transaction) {
            this.transaction = Objects.requireNonNull(transaction, "transaction must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllFailures(List<ValidationMetadata> failures) {
            if (failures != null) {
                this.failures.addAll(failures);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addFailures(ValidationMetadata failures) {
            this.failures.add(failures);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "failures", nulls = Nulls.SKIP)
        public _FinalStage failures(List<ValidationMetadata> failures) {
            this.failures.clear();
            if (failures != null) {
                this.failures.addAll(failures);
            }
            return this;
        }

        @java.lang.Override
        public ValidationErrorResult build() {
            return new ValidationErrorResult(status, failures, transaction, additionalProperties);
        }
    }
}
