/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.txnmatching.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ValidationMetadata.Builder.class)
public final class ValidationMetadata {
    private final boolean isSkippable;

    private final String validationName;

    private final String message;

    private final Map<String, Object> additionalProperties;

    private ValidationMetadata(
            boolean isSkippable, String validationName, String message, Map<String, Object> additionalProperties) {
        this.isSkippable = isSkippable;
        this.validationName = validationName;
        this.message = message;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("isSkippable")
    public boolean getIsSkippable() {
        return isSkippable;
    }

    @JsonProperty("validationName")
    public String getValidationName() {
        return validationName;
    }

    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ValidationMetadata && equalTo((ValidationMetadata) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ValidationMetadata other) {
        return isSkippable == other.isSkippable
                && validationName.equals(other.validationName)
                && message.equals(other.message);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.isSkippable, this.validationName, this.message);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IsSkippableStage builder() {
        return new Builder();
    }

    public interface IsSkippableStage {
        ValidationNameStage isSkippable(boolean isSkippable);

        Builder from(ValidationMetadata other);
    }

    public interface ValidationNameStage {
        MessageStage validationName(@NotNull String validationName);
    }

    public interface MessageStage {
        _FinalStage message(@NotNull String message);
    }

    public interface _FinalStage {
        ValidationMetadata build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IsSkippableStage, ValidationNameStage, MessageStage, _FinalStage {
        private boolean isSkippable;

        private String validationName;

        private String message;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ValidationMetadata other) {
            isSkippable(other.getIsSkippable());
            validationName(other.getValidationName());
            message(other.getMessage());
            return this;
        }

        @java.lang.Override
        @JsonSetter("isSkippable")
        public ValidationNameStage isSkippable(boolean isSkippable) {
            this.isSkippable = isSkippable;
            return this;
        }

        @java.lang.Override
        @JsonSetter("validationName")
        public MessageStage validationName(@NotNull String validationName) {
            this.validationName = Objects.requireNonNull(validationName, "validationName must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        @java.lang.Override
        public ValidationMetadata build() {
            return new ValidationMetadata(isSkippable, validationName, message, additionalProperties);
        }
    }
}
