/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.txnmatching.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VisaMidsAttributes.Builder.class)
public final class VisaMidsAttributes {
    private final VisaMidsDetails mids;

    private final Map<String, Object> additionalProperties;

    private VisaMidsAttributes(VisaMidsDetails mids, Map<String, Object> additionalProperties) {
        this.mids = mids;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Merchant ID (MID) associated with the processor
     */
    @JsonProperty("mids")
    public VisaMidsDetails getMids() {
        return mids;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VisaMidsAttributes && equalTo((VisaMidsAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VisaMidsAttributes other) {
        return mids.equals(other.mids);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.mids);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MidsStage builder() {
        return new Builder();
    }

    public interface MidsStage {
        /**
         * <p>Merchant ID (MID) associated with the processor</p>
         */
        _FinalStage mids(@NotNull VisaMidsDetails mids);

        Builder from(VisaMidsAttributes other);
    }

    public interface _FinalStage {
        VisaMidsAttributes build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MidsStage, _FinalStage {
        private VisaMidsDetails mids;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(VisaMidsAttributes other) {
            mids(other.getMids());
            return this;
        }

        /**
         * <p>Merchant ID (MID) associated with the processor</p>
         * <p>Merchant ID (MID) associated with the processor</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("mids")
        public _FinalStage mids(@NotNull VisaMidsDetails mids) {
            this.mids = Objects.requireNonNull(mids, "mids must not be null");
            return this;
        }

        @java.lang.Override
        public VisaMidsAttributes build() {
            return new VisaMidsAttributes(mids, additionalProperties);
        }
    }
}
