/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.contentstrategies.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ContentStrategySort {
    public static final ContentStrategySort EXPIRING_SOON =
            new ContentStrategySort(Value.EXPIRING_SOON, "EXPIRING_SOON");

    public static final ContentStrategySort OFFERS_NEAR_YOU =
            new ContentStrategySort(Value.OFFERS_NEAR_YOU, "OFFERS_NEAR_YOU");

    public static final ContentStrategySort PERSONALIZED = new ContentStrategySort(Value.PERSONALIZED, "PERSONALIZED");

    public static final ContentStrategySort HIGHEST_CASHBACK =
            new ContentStrategySort(Value.HIGHEST_CASHBACK, "HIGHEST_CASHBACK");

    public static final ContentStrategySort NEWLY_LIVE = new ContentStrategySort(Value.NEWLY_LIVE, "NEWLY_LIVE");

    private final Value value;

    private final String string;

    ContentStrategySort(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ContentStrategySort && this.string.equals(((ContentStrategySort) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EXPIRING_SOON:
                return visitor.visitExpiringSoon();
            case OFFERS_NEAR_YOU:
                return visitor.visitOffersNearYou();
            case PERSONALIZED:
                return visitor.visitPersonalized();
            case HIGHEST_CASHBACK:
                return visitor.visitHighestCashback();
            case NEWLY_LIVE:
                return visitor.visitNewlyLive();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ContentStrategySort valueOf(String value) {
        switch (value) {
            case "EXPIRING_SOON":
                return EXPIRING_SOON;
            case "OFFERS_NEAR_YOU":
                return OFFERS_NEAR_YOU;
            case "PERSONALIZED":
                return PERSONALIZED;
            case "HIGHEST_CASHBACK":
                return HIGHEST_CASHBACK;
            case "NEWLY_LIVE":
                return NEWLY_LIVE;
            default:
                return new ContentStrategySort(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NEWLY_LIVE,

        EXPIRING_SOON,

        HIGHEST_CASHBACK,

        PERSONALIZED,

        OFFERS_NEAR_YOU,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNewlyLive();

        T visitExpiringSoon();

        T visitHighestCashback();

        T visitPersonalized();

        T visitOffersNearYou();

        T visitUnknown(String unknownType);
    }
}
