/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.contentstrategies.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateContentStrategyRequestBody.Builder.class)
public final class UpdateContentStrategyRequestBody {
    private final UpdateContentStrategyRequestData data;

    private final Map<String, Object> additionalProperties;

    private UpdateContentStrategyRequestBody(
            UpdateContentStrategyRequestData data, Map<String, Object> additionalProperties) {
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Content strategy data for update
     */
    @JsonProperty("data")
    public UpdateContentStrategyRequestData getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateContentStrategyRequestBody && equalTo((UpdateContentStrategyRequestBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateContentStrategyRequestBody other) {
        return data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DataStage builder() {
        return new Builder();
    }

    public interface DataStage {
        /**
         * <p>Content strategy data for update</p>
         */
        _FinalStage data(@NotNull UpdateContentStrategyRequestData data);

        Builder from(UpdateContentStrategyRequestBody other);
    }

    public interface _FinalStage {
        UpdateContentStrategyRequestBody build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DataStage, _FinalStage {
        private UpdateContentStrategyRequestData data;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateContentStrategyRequestBody other) {
            data(other.getData());
            return this;
        }

        /**
         * <p>Content strategy data for update</p>
         * <p>Content strategy data for update</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("data")
        public _FinalStage data(@NotNull UpdateContentStrategyRequestData data) {
            this.data = Objects.requireNonNull(data, "data must not be null");
            return this;
        }

        @java.lang.Override
        public UpdateContentStrategyRequestBody build() {
            return new UpdateContentStrategyRequestBody(data, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
