/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UserRequestData.Builder.class)
public final class UserRequestData {
    private final String id;

    private final UserRequestAttributes attributes;

    private final Map<String, Object> additionalProperties;

    private UserRequestData(String id, UserRequestAttributes attributes, Map<String, Object> additionalProperties) {
        this.id = id;
        this.attributes = attributes;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("attributes")
    public UserRequestAttributes getAttributes() {
        return attributes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserRequestData && equalTo((UserRequestData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserRequestData other) {
        return id.equals(other.id) && attributes.equals(other.attributes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.attributes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        AttributesStage id(@NotNull String id);

        Builder from(UserRequestData other);
    }

    public interface AttributesStage {
        _FinalStage attributes(@NotNull UserRequestAttributes attributes);
    }

    public interface _FinalStage {
        UserRequestData build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, AttributesStage, _FinalStage {
        private String id;

        private UserRequestAttributes attributes;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UserRequestData other) {
            id(other.getId());
            attributes(other.getAttributes());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public AttributesStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("attributes")
        public _FinalStage attributes(@NotNull UserRequestAttributes attributes) {
            this.attributes = Objects.requireNonNull(attributes, "attributes must not be null");
            return this;
        }

        @java.lang.Override
        public UserRequestData build() {
            return new UserRequestData(id, attributes, additionalProperties);
        }
    }
}
