/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.placements.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.organizations.placements.types.PlacementTypeFilter;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListPlacementsRequest.Builder.class)
public final class ListPlacementsRequest {
    private final Optional<PlacementTypeFilter> filterType;

    private final Optional<String> filterName;

    private final Optional<String> pageAfter;

    private final Optional<Integer> pageSize;

    private final Map<String, Object> additionalProperties;

    private ListPlacementsRequest(
            Optional<PlacementTypeFilter> filterType,
            Optional<String> filterName,
            Optional<String> pageAfter,
            Optional<Integer> pageSize,
            Map<String, Object> additionalProperties) {
        this.filterType = filterType;
        this.filterName = filterName;
        this.pageAfter = pageAfter;
        this.pageSize = pageSize;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Filter by placement type (placementMainPage or placementPushNotification)
     */
    @JsonIgnore
    public Optional<PlacementTypeFilter> getFilterType() {
        return filterType;
    }

    /**
     * @return Filter by exact placement name (unique within an organization per type)
     */
    @JsonIgnore
    public Optional<String> getFilterName() {
        return filterName;
    }

    /**
     * @return Cursor value for the next page of results
     */
    @JsonIgnore
    public Optional<String> getPageAfter() {
        return pageAfter;
    }

    /**
     * @return Maximum number of records to return [1 - 200] (default = 200)
     */
    @JsonIgnore
    public Optional<Integer> getPageSize() {
        return pageSize;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListPlacementsRequest && equalTo((ListPlacementsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListPlacementsRequest other) {
        return filterType.equals(other.filterType)
                && filterName.equals(other.filterName)
                && pageAfter.equals(other.pageAfter)
                && pageSize.equals(other.pageSize);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.filterType, this.filterName, this.pageAfter, this.pageSize);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<PlacementTypeFilter> filterType = Optional.empty();

        private Optional<String> filterName = Optional.empty();

        private Optional<String> pageAfter = Optional.empty();

        private Optional<Integer> pageSize = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListPlacementsRequest other) {
            filterType(other.getFilterType());
            filterName(other.getFilterName());
            pageAfter(other.getPageAfter());
            pageSize(other.getPageSize());
            return this;
        }

        /**
         * <p>Filter by placement type (placementMainPage or placementPushNotification)</p>
         */
        @JsonSetter(value = "filter[type]", nulls = Nulls.SKIP)
        public Builder filterType(Optional<PlacementTypeFilter> filterType) {
            this.filterType = filterType;
            return this;
        }

        public Builder filterType(PlacementTypeFilter filterType) {
            this.filterType = Optional.ofNullable(filterType);
            return this;
        }

        /**
         * <p>Filter by exact placement name (unique within an organization per type)</p>
         */
        @JsonSetter(value = "filter[name]", nulls = Nulls.SKIP)
        public Builder filterName(Optional<String> filterName) {
            this.filterName = filterName;
            return this;
        }

        public Builder filterName(String filterName) {
            this.filterName = Optional.ofNullable(filterName);
            return this;
        }

        /**
         * <p>Cursor value for the next page of results</p>
         */
        @JsonSetter(value = "page[after]", nulls = Nulls.SKIP)
        public Builder pageAfter(Optional<String> pageAfter) {
            this.pageAfter = pageAfter;
            return this;
        }

        public Builder pageAfter(String pageAfter) {
            this.pageAfter = Optional.ofNullable(pageAfter);
            return this;
        }

        /**
         * <p>Maximum number of records to return [1 - 200] (default = 200)</p>
         */
        @JsonSetter(value = "page[size]", nulls = Nulls.SKIP)
        public Builder pageSize(Optional<Integer> pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        public Builder pageSize(Integer pageSize) {
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        public ListPlacementsRequest build() {
            return new ListPlacementsRequest(filterType, filterName, pageAfter, pageSize, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
