/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications;

import com.kard.api.core.ClientOptions;
import com.kard.api.core.Suppliers;
import com.kard.api.resources.notifications.subscriptions.SubscriptionsClient;
import java.util.function.Supplier;

public class NotificationsClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<SubscriptionsClient> subscriptionsClient;

    public NotificationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.subscriptionsClient = Suppliers.memoize(() -> new SubscriptionsClient(clientOptions));
    }

    public SubscriptionsClient subscriptions() {
        return this.subscriptionsClient.get();
    }
}
