/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.audit.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProcessEventsRequest.Builder.class)
public final class ProcessEventsRequest {
    private final SnsEventMessage snsEventMessage;

    private final Map<String, Object> additionalProperties;

    private ProcessEventsRequest(SnsEventMessage snsEventMessage, Map<String, Object> additionalProperties) {
        this.snsEventMessage = snsEventMessage;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("snsEventMessage")
    public SnsEventMessage getSnsEventMessage() {
        return snsEventMessage;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProcessEventsRequest && equalTo((ProcessEventsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProcessEventsRequest other) {
        return snsEventMessage.equals(other.snsEventMessage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.snsEventMessage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SnsEventMessageStage builder() {
        return new Builder();
    }

    public interface SnsEventMessageStage {
        _FinalStage snsEventMessage(@NotNull SnsEventMessage snsEventMessage);

        Builder from(ProcessEventsRequest other);
    }

    public interface _FinalStage {
        ProcessEventsRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SnsEventMessageStage, _FinalStage {
        private SnsEventMessage snsEventMessage;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProcessEventsRequest other) {
            snsEventMessage(other.getSnsEventMessage());
            return this;
        }

        @java.lang.Override
        @JsonSetter("snsEventMessage")
        public _FinalStage snsEventMessage(@NotNull SnsEventMessage snsEventMessage) {
            this.snsEventMessage = Objects.requireNonNull(snsEventMessage, "snsEventMessage must not be null");
            return this;
        }

        @java.lang.Override
        public ProcessEventsRequest build() {
            return new ProcessEventsRequest(snsEventMessage, additionalProperties);
        }
    }
}
