/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.billingcommons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RewardEntryFull.Builder.class)
public final class RewardEntryFull {
    private final UUID rewardId;

    private final List<String> transactionIds;

    private final int transactionAmount;

    private final OffsetDateTime transactionTimestamp;

    private final String offerId;

    private final String userId;

    private final String issuerId;

    private final String merchantId;

    private final int issuerAmount;

    private final int cardHolderAmount;

    private final int kardFees;

    private final String description;

    private final OffsetDateTime createdAt;

    private final RewardType type;

    private final Map<String, Object> additionalProperties;

    private RewardEntryFull(
            UUID rewardId,
            List<String> transactionIds,
            int transactionAmount,
            OffsetDateTime transactionTimestamp,
            String offerId,
            String userId,
            String issuerId,
            String merchantId,
            int issuerAmount,
            int cardHolderAmount,
            int kardFees,
            String description,
            OffsetDateTime createdAt,
            RewardType type,
            Map<String, Object> additionalProperties) {
        this.rewardId = rewardId;
        this.transactionIds = transactionIds;
        this.transactionAmount = transactionAmount;
        this.transactionTimestamp = transactionTimestamp;
        this.offerId = offerId;
        this.userId = userId;
        this.issuerId = issuerId;
        this.merchantId = merchantId;
        this.issuerAmount = issuerAmount;
        this.cardHolderAmount = cardHolderAmount;
        this.kardFees = kardFees;
        this.description = description;
        this.createdAt = createdAt;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID of the reward
     */
    @JsonProperty("rewardId")
    public UUID getRewardId() {
        return rewardId;
    }

    /**
     * @return TransactionIds is a list of transactions related to the reward payout
     */
    @JsonProperty("transactionIds")
    public List<String> getTransactionIds() {
        return transactionIds;
    }

    /**
     * @return Total amount of the transaction(s)
     */
    @JsonProperty("transactionAmount")
    public int getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * @return Date of the transaction that triggered the reward (even for multi-txns)
     */
    @JsonProperty("transactionTimestamp")
    public OffsetDateTime getTransactionTimestamp() {
        return transactionTimestamp;
    }

    /**
     * @return Offer ID that resulted in this entry
     */
    @JsonProperty("offerId")
    public String getOfferId() {
        return offerId;
    }

    /**
     * @return ID of the user
     */
    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    /**
     * @return Issuer ID associated with the reward
     */
    @JsonProperty("issuerId")
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * @return Merchant ID associated with the reward
     */
    @JsonProperty("merchantId")
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * @return Amount in cents to the Issuer
     */
    @JsonProperty("issuerAmount")
    public int getIssuerAmount() {
        return issuerAmount;
    }

    /**
     * @return Amount in cents to the Card Holder
     */
    @JsonProperty("cardHolderAmount")
    public int getCardHolderAmount() {
        return cardHolderAmount;
    }

    /**
     * @return Amount in cents of the Kard fees
     */
    @JsonProperty("kardFees")
    public int getKardFees() {
        return kardFees;
    }

    /**
     * @return Description of the payout
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    /**
     * @return Date and time of the reward entry
     */
    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Type of reward entry
     */
    @JsonProperty("type")
    public RewardType getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RewardEntryFull && equalTo((RewardEntryFull) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RewardEntryFull other) {
        return rewardId.equals(other.rewardId)
                && transactionIds.equals(other.transactionIds)
                && transactionAmount == other.transactionAmount
                && transactionTimestamp.equals(other.transactionTimestamp)
                && offerId.equals(other.offerId)
                && userId.equals(other.userId)
                && issuerId.equals(other.issuerId)
                && merchantId.equals(other.merchantId)
                && issuerAmount == other.issuerAmount
                && cardHolderAmount == other.cardHolderAmount
                && kardFees == other.kardFees
                && description.equals(other.description)
                && createdAt.equals(other.createdAt)
                && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.rewardId,
                this.transactionIds,
                this.transactionAmount,
                this.transactionTimestamp,
                this.offerId,
                this.userId,
                this.issuerId,
                this.merchantId,
                this.issuerAmount,
                this.cardHolderAmount,
                this.kardFees,
                this.description,
                this.createdAt,
                this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RewardIdStage builder() {
        return new Builder();
    }

    public interface RewardIdStage {
        /**
         * <p>ID of the reward</p>
         */
        TransactionAmountStage rewardId(@NotNull UUID rewardId);

        Builder from(RewardEntryFull other);
    }

    public interface TransactionAmountStage {
        /**
         * <p>Total amount of the transaction(s)</p>
         */
        TransactionTimestampStage transactionAmount(int transactionAmount);
    }

    public interface TransactionTimestampStage {
        /**
         * <p>Date of the transaction that triggered the reward (even for multi-txns)</p>
         */
        OfferIdStage transactionTimestamp(@NotNull OffsetDateTime transactionTimestamp);
    }

    public interface OfferIdStage {
        /**
         * <p>Offer ID that resulted in this entry</p>
         */
        UserIdStage offerId(@NotNull String offerId);
    }

    public interface UserIdStage {
        /**
         * <p>ID of the user</p>
         */
        IssuerIdStage userId(@NotNull String userId);
    }

    public interface IssuerIdStage {
        /**
         * <p>Issuer ID associated with the reward</p>
         */
        MerchantIdStage issuerId(@NotNull String issuerId);
    }

    public interface MerchantIdStage {
        /**
         * <p>Merchant ID associated with the reward</p>
         */
        IssuerAmountStage merchantId(@NotNull String merchantId);
    }

    public interface IssuerAmountStage {
        /**
         * <p>Amount in cents to the Issuer</p>
         */
        CardHolderAmountStage issuerAmount(int issuerAmount);
    }

    public interface CardHolderAmountStage {
        /**
         * <p>Amount in cents to the Card Holder</p>
         */
        KardFeesStage cardHolderAmount(int cardHolderAmount);
    }

    public interface KardFeesStage {
        /**
         * <p>Amount in cents of the Kard fees</p>
         */
        DescriptionStage kardFees(int kardFees);
    }

    public interface DescriptionStage {
        /**
         * <p>Description of the payout</p>
         */
        CreatedAtStage description(@NotNull String description);
    }

    public interface CreatedAtStage {
        /**
         * <p>Date and time of the reward entry</p>
         */
        TypeStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface TypeStage {
        /**
         * <p>Type of reward entry</p>
         */
        _FinalStage type(@NotNull RewardType type);
    }

    public interface _FinalStage {
        RewardEntryFull build();

        /**
         * <p>TransactionIds is a list of transactions related to the reward payout</p>
         */
        _FinalStage transactionIds(List<String> transactionIds);

        _FinalStage addTransactionIds(String transactionIds);

        _FinalStage addAllTransactionIds(List<String> transactionIds);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements RewardIdStage,
                    TransactionAmountStage,
                    TransactionTimestampStage,
                    OfferIdStage,
                    UserIdStage,
                    IssuerIdStage,
                    MerchantIdStage,
                    IssuerAmountStage,
                    CardHolderAmountStage,
                    KardFeesStage,
                    DescriptionStage,
                    CreatedAtStage,
                    TypeStage,
                    _FinalStage {
        private UUID rewardId;

        private int transactionAmount;

        private OffsetDateTime transactionTimestamp;

        private String offerId;

        private String userId;

        private String issuerId;

        private String merchantId;

        private int issuerAmount;

        private int cardHolderAmount;

        private int kardFees;

        private String description;

        private OffsetDateTime createdAt;

        private RewardType type;

        private List<String> transactionIds = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RewardEntryFull other) {
            rewardId(other.getRewardId());
            transactionIds(other.getTransactionIds());
            transactionAmount(other.getTransactionAmount());
            transactionTimestamp(other.getTransactionTimestamp());
            offerId(other.getOfferId());
            userId(other.getUserId());
            issuerId(other.getIssuerId());
            merchantId(other.getMerchantId());
            issuerAmount(other.getIssuerAmount());
            cardHolderAmount(other.getCardHolderAmount());
            kardFees(other.getKardFees());
            description(other.getDescription());
            createdAt(other.getCreatedAt());
            type(other.getType());
            return this;
        }

        /**
         * <p>ID of the reward</p>
         * <p>ID of the reward</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("rewardId")
        public TransactionAmountStage rewardId(@NotNull UUID rewardId) {
            this.rewardId = Objects.requireNonNull(rewardId, "rewardId must not be null");
            return this;
        }

        /**
         * <p>Total amount of the transaction(s)</p>
         * <p>Total amount of the transaction(s)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("transactionAmount")
        public TransactionTimestampStage transactionAmount(int transactionAmount) {
            this.transactionAmount = transactionAmount;
            return this;
        }

        /**
         * <p>Date of the transaction that triggered the reward (even for multi-txns)</p>
         * <p>Date of the transaction that triggered the reward (even for multi-txns)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("transactionTimestamp")
        public OfferIdStage transactionTimestamp(@NotNull OffsetDateTime transactionTimestamp) {
            this.transactionTimestamp =
                    Objects.requireNonNull(transactionTimestamp, "transactionTimestamp must not be null");
            return this;
        }

        /**
         * <p>Offer ID that resulted in this entry</p>
         * <p>Offer ID that resulted in this entry</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("offerId")
        public UserIdStage offerId(@NotNull String offerId) {
            this.offerId = Objects.requireNonNull(offerId, "offerId must not be null");
            return this;
        }

        /**
         * <p>ID of the user</p>
         * <p>ID of the user</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("userId")
        public IssuerIdStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        /**
         * <p>Issuer ID associated with the reward</p>
         * <p>Issuer ID associated with the reward</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("issuerId")
        public MerchantIdStage issuerId(@NotNull String issuerId) {
            this.issuerId = Objects.requireNonNull(issuerId, "issuerId must not be null");
            return this;
        }

        /**
         * <p>Merchant ID associated with the reward</p>
         * <p>Merchant ID associated with the reward</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("merchantId")
        public IssuerAmountStage merchantId(@NotNull String merchantId) {
            this.merchantId = Objects.requireNonNull(merchantId, "merchantId must not be null");
            return this;
        }

        /**
         * <p>Amount in cents to the Issuer</p>
         * <p>Amount in cents to the Issuer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("issuerAmount")
        public CardHolderAmountStage issuerAmount(int issuerAmount) {
            this.issuerAmount = issuerAmount;
            return this;
        }

        /**
         * <p>Amount in cents to the Card Holder</p>
         * <p>Amount in cents to the Card Holder</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("cardHolderAmount")
        public KardFeesStage cardHolderAmount(int cardHolderAmount) {
            this.cardHolderAmount = cardHolderAmount;
            return this;
        }

        /**
         * <p>Amount in cents of the Kard fees</p>
         * <p>Amount in cents of the Kard fees</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("kardFees")
        public DescriptionStage kardFees(int kardFees) {
            this.kardFees = kardFees;
            return this;
        }

        /**
         * <p>Description of the payout</p>
         * <p>Description of the payout</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public CreatedAtStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        /**
         * <p>Date and time of the reward entry</p>
         * <p>Date and time of the reward entry</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAt")
        public TypeStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Type of reward entry</p>
         * <p>Type of reward entry</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull RewardType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>TransactionIds is a list of transactions related to the reward payout</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllTransactionIds(List<String> transactionIds) {
            if (transactionIds != null) {
                this.transactionIds.addAll(transactionIds);
            }
            return this;
        }

        /**
         * <p>TransactionIds is a list of transactions related to the reward payout</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addTransactionIds(String transactionIds) {
            this.transactionIds.add(transactionIds);
            return this;
        }

        /**
         * <p>TransactionIds is a list of transactions related to the reward payout</p>
         */
        @java.lang.Override
        @JsonSetter(value = "transactionIds", nulls = Nulls.SKIP)
        public _FinalStage transactionIds(List<String> transactionIds) {
            this.transactionIds.clear();
            if (transactionIds != null) {
                this.transactionIds.addAll(transactionIds);
            }
            return this;
        }

        @java.lang.Override
        public RewardEntryFull build() {
            return new RewardEntryFull(
                    rewardId,
                    transactionIds,
                    transactionAmount,
                    transactionTimestamp,
                    offerId,
                    userId,
                    issuerId,
                    merchantId,
                    issuerAmount,
                    cardHolderAmount,
                    kardFees,
                    description,
                    createdAt,
                    type,
                    additionalProperties);
        }
    }
}
