/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.subscriptions.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.commons.types.NotificationType;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SubscriptionAttributes.Builder.class)
public final class SubscriptionAttributes {
    private final NotificationType eventName;

    private final String webhookUrl;

    private final boolean enabled;

    private final Map<String, Object> additionalProperties;

    private SubscriptionAttributes(
            NotificationType eventName, String webhookUrl, boolean enabled, Map<String, Object> additionalProperties) {
        this.eventName = eventName;
        this.webhookUrl = webhookUrl;
        this.enabled = enabled;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the event
     */
    @JsonProperty("eventName")
    public NotificationType getEventName() {
        return eventName;
    }

    /**
     * @return The URL to which notifications will be sent
     */
    @JsonProperty("webhookUrl")
    public String getWebhookUrl() {
        return webhookUrl;
    }

    /**
     * @return Indicates whether the subscription is active
     */
    @JsonProperty("enabled")
    public boolean getEnabled() {
        return enabled;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SubscriptionAttributes && equalTo((SubscriptionAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SubscriptionAttributes other) {
        return eventName.equals(other.eventName) && webhookUrl.equals(other.webhookUrl) && enabled == other.enabled;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.eventName, this.webhookUrl, this.enabled);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EventNameStage builder() {
        return new Builder();
    }

    public interface EventNameStage {
        /**
         * <p>The name of the event</p>
         */
        WebhookUrlStage eventName(@NotNull NotificationType eventName);

        Builder from(SubscriptionAttributes other);
    }

    public interface WebhookUrlStage {
        /**
         * <p>The URL to which notifications will be sent</p>
         */
        EnabledStage webhookUrl(@NotNull String webhookUrl);
    }

    public interface EnabledStage {
        /**
         * <p>Indicates whether the subscription is active</p>
         */
        _FinalStage enabled(boolean enabled);
    }

    public interface _FinalStage {
        SubscriptionAttributes build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EventNameStage, WebhookUrlStage, EnabledStage, _FinalStage {
        private NotificationType eventName;

        private String webhookUrl;

        private boolean enabled;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SubscriptionAttributes other) {
            eventName(other.getEventName());
            webhookUrl(other.getWebhookUrl());
            enabled(other.getEnabled());
            return this;
        }

        /**
         * <p>The name of the event</p>
         * <p>The name of the event</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("eventName")
        public WebhookUrlStage eventName(@NotNull NotificationType eventName) {
            this.eventName = Objects.requireNonNull(eventName, "eventName must not be null");
            return this;
        }

        /**
         * <p>The URL to which notifications will be sent</p>
         * <p>The URL to which notifications will be sent</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("webhookUrl")
        public EnabledStage webhookUrl(@NotNull String webhookUrl) {
            this.webhookUrl = Objects.requireNonNull(webhookUrl, "webhookUrl must not be null");
            return this;
        }

        /**
         * <p>Indicates whether the subscription is active</p>
         * <p>Indicates whether the subscription is active</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("enabled")
        public _FinalStage enabled(boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        @java.lang.Override
        public SubscriptionAttributes build() {
            return new SubscriptionAttributes(eventName, webhookUrl, enabled, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
