/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.rewards.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ComponentType {
    public static final ComponentType BOOSTED_REWARD = new ComponentType(Value.BOOSTED_REWARD, "boostedReward");

    public static final ComponentType BASE_REWARD = new ComponentType(Value.BASE_REWARD, "baseReward");

    public static final ComponentType CTA = new ComponentType(Value.CTA, "cta");

    public static final ComponentType TAGS = new ComponentType(Value.TAGS, "tags");

    public static final ComponentType LOGO_FLARE = new ComponentType(Value.LOGO_FLARE, "logoFlare");

    public static final ComponentType SHORT_DESCRIPTION =
            new ComponentType(Value.SHORT_DESCRIPTION, "shortDescription");

    public static final ComponentType LONG_DESCRIPTION = new ComponentType(Value.LONG_DESCRIPTION, "longDescription");

    public static final ComponentType DETAIL_TAGS = new ComponentType(Value.DETAIL_TAGS, "detailTags");

    private final Value value;

    private final String string;

    ComponentType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ComponentType && this.string.equals(((ComponentType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case BOOSTED_REWARD:
                return visitor.visitBoostedReward();
            case BASE_REWARD:
                return visitor.visitBaseReward();
            case CTA:
                return visitor.visitCta();
            case TAGS:
                return visitor.visitTags();
            case LOGO_FLARE:
                return visitor.visitLogoFlare();
            case SHORT_DESCRIPTION:
                return visitor.visitShortDescription();
            case LONG_DESCRIPTION:
                return visitor.visitLongDescription();
            case DETAIL_TAGS:
                return visitor.visitDetailTags();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ComponentType valueOf(String value) {
        switch (value) {
            case "boostedReward":
                return BOOSTED_REWARD;
            case "baseReward":
                return BASE_REWARD;
            case "cta":
                return CTA;
            case "tags":
                return TAGS;
            case "logoFlare":
                return LOGO_FLARE;
            case "shortDescription":
                return SHORT_DESCRIPTION;
            case "longDescription":
                return LONG_DESCRIPTION;
            case "detailTags":
                return DETAIL_TAGS;
            default:
                return new ComponentType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SHORT_DESCRIPTION,

        LONG_DESCRIPTION,

        BASE_REWARD,

        BOOSTED_REWARD,

        CTA,

        TAGS,

        DETAIL_TAGS,

        LOGO_FLARE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitShortDescription();

        T visitLongDescription();

        T visitBaseReward();

        T visitBoostedReward();

        T visitCta();

        T visitTags();

        T visitDetailTags();

        T visitLogoFlare();

        T visitUnknown(String unknownType);
    }
}
