/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.rewards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EligibilityLocationAddress.Builder.class)
public final class EligibilityLocationAddress {
    private final String street;

    private final String city;

    private final String state;

    private final String zipCode;

    private final Map<String, Object> additionalProperties;

    private EligibilityLocationAddress(
            String street, String city, String state, String zipCode, Map<String, Object> additionalProperties) {
        this.street = street;
        this.city = city;
        this.state = state;
        this.zipCode = zipCode;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("street")
    public String getStreet() {
        return street;
    }

    @JsonProperty("city")
    public String getCity() {
        return city;
    }

    @JsonProperty("state")
    public String getState() {
        return state;
    }

    @JsonProperty("zipCode")
    public String getZipCode() {
        return zipCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EligibilityLocationAddress && equalTo((EligibilityLocationAddress) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EligibilityLocationAddress other) {
        return street.equals(other.street)
                && city.equals(other.city)
                && state.equals(other.state)
                && zipCode.equals(other.zipCode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.street, this.city, this.state, this.zipCode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StreetStage builder() {
        return new Builder();
    }

    public interface StreetStage {
        CityStage street(@NotNull String street);

        Builder from(EligibilityLocationAddress other);
    }

    public interface CityStage {
        StateStage city(@NotNull String city);
    }

    public interface StateStage {
        ZipCodeStage state(@NotNull String state);
    }

    public interface ZipCodeStage {
        _FinalStage zipCode(@NotNull String zipCode);
    }

    public interface _FinalStage {
        EligibilityLocationAddress build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements StreetStage, CityStage, StateStage, ZipCodeStage, _FinalStage {
        private String street;

        private String city;

        private String state;

        private String zipCode;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EligibilityLocationAddress other) {
            street(other.getStreet());
            city(other.getCity());
            state(other.getState());
            zipCode(other.getZipCode());
            return this;
        }

        @java.lang.Override
        @JsonSetter("street")
        public CityStage street(@NotNull String street) {
            this.street = Objects.requireNonNull(street, "street must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("city")
        public StateStage city(@NotNull String city) {
            this.city = Objects.requireNonNull(city, "city must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("state")
        public ZipCodeStage state(@NotNull String state) {
            this.state = Objects.requireNonNull(state, "state must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("zipCode")
        public _FinalStage zipCode(@NotNull String zipCode) {
            this.zipCode = Objects.requireNonNull(zipCode, "zipCode must not be null");
            return this;
        }

        @java.lang.Override
        public EligibilityLocationAddress build() {
            return new EligibilityLocationAddress(street, city, state, zipCode, additionalProperties);
        }
    }
}
