/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.rewards.types;

public interface IPurchaseCountOfferCore {
    String getId();

    PurchaseCountOfferFields getAttributes();
}
