/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.rewards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.Nullable;
import com.kard.api.core.NullableNonemptyFilter;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LocationRating.Builder.class)
public final class LocationRating {
    private final double value;

    private final Optional<Integer> count;

    private final Map<String, Object> additionalProperties;

    private LocationRating(double value, Optional<Integer> count, Map<String, Object> additionalProperties) {
        this.value = value;
        this.count = count;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Restaurant star rating. Rating is out of 5.
     */
    @JsonProperty("value")
    public double getValue() {
        return value;
    }

    /**
     * @return Number of ratings the score is based on. Null when a count is not available.
     */
    @JsonIgnore
    public Optional<Integer> getCount() {
        if (count == null) {
            return Optional.empty();
        }
        return count;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("count")
    private Optional<Integer> _getCount() {
        return count;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LocationRating && equalTo((LocationRating) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(LocationRating other) {
        return value == other.value && count.equals(other.count);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value, this.count);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ValueStage builder() {
        return new Builder();
    }

    public interface ValueStage {
        /**
         * <p>Restaurant star rating. Rating is out of 5.</p>
         */
        _FinalStage value(double value);

        Builder from(LocationRating other);
    }

    public interface _FinalStage {
        LocationRating build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Number of ratings the score is based on. Null when a count is not available.</p>
         */
        _FinalStage count(Optional<Integer> count);

        _FinalStage count(Integer count);

        _FinalStage count(Nullable<Integer> count);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ValueStage, _FinalStage {
        private double value;

        private Optional<Integer> count = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(LocationRating other) {
            value(other.getValue());
            count(other.getCount());
            return this;
        }

        /**
         * <p>Restaurant star rating. Rating is out of 5.</p>
         * <p>Restaurant star rating. Rating is out of 5.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("value")
        public _FinalStage value(double value) {
            this.value = value;
            return this;
        }

        /**
         * <p>Number of ratings the score is based on. Null when a count is not available.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage count(Nullable<Integer> count) {
            if (count.isNull()) {
                this.count = null;
            } else if (count.isEmpty()) {
                this.count = Optional.empty();
            } else {
                this.count = Optional.of(count.get());
            }
            return this;
        }

        /**
         * <p>Number of ratings the score is based on. Null when a count is not available.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage count(Integer count) {
            this.count = Optional.ofNullable(count);
            return this;
        }

        /**
         * <p>Number of ratings the score is based on. Null when a count is not available.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "count", nulls = Nulls.SKIP)
        public _FinalStage count(Optional<Integer> count) {
            this.count = count;
            return this;
        }

        @java.lang.Override
        public LocationRating build() {
            return new LocationRating(value, count, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
