/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.rewards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OfferComponents.Builder.class)
public final class OfferComponents {
    private final Optional<String> shortDescription;

    private final Optional<String> longDescription;

    private final Optional<CtaComponent> cta;

    private final Optional<List<String>> tags;

    private final Optional<List<String>> detailTags;

    private final Map<String, Object> additionalProperties;

    private OfferComponents(
            Optional<String> shortDescription,
            Optional<String> longDescription,
            Optional<CtaComponent> cta,
            Optional<List<String>> tags,
            Optional<List<String>> detailTags,
            Map<String, Object> additionalProperties) {
        this.shortDescription = shortDescription;
        this.longDescription = longDescription;
        this.cta = cta;
        this.tags = tags;
        this.detailTags = detailTags;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Short description for the offer
     */
    @JsonProperty("shortDescription")
    public Optional<String> getShortDescription() {
        return shortDescription;
    }

    /**
     * @return Long description for the offer
     */
    @JsonProperty("longDescription")
    public Optional<String> getLongDescription() {
        return longDescription;
    }

    /**
     * @return Call-to-action button component
     */
    @JsonProperty("cta")
    public Optional<CtaComponent> getCta() {
        return cta;
    }

    /**
     * @return Tags for the offer
     */
    @JsonProperty("tags")
    public Optional<List<String>> getTags() {
        return tags;
    }

    /**
     * @return Detail tags for the offer
     */
    @JsonProperty("detailTags")
    public Optional<List<String>> getDetailTags() {
        return detailTags;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OfferComponents && equalTo((OfferComponents) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OfferComponents other) {
        return shortDescription.equals(other.shortDescription)
                && longDescription.equals(other.longDescription)
                && cta.equals(other.cta)
                && tags.equals(other.tags)
                && detailTags.equals(other.detailTags);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.shortDescription, this.longDescription, this.cta, this.tags, this.detailTags);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> shortDescription = Optional.empty();

        private Optional<String> longDescription = Optional.empty();

        private Optional<CtaComponent> cta = Optional.empty();

        private Optional<List<String>> tags = Optional.empty();

        private Optional<List<String>> detailTags = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(OfferComponents other) {
            shortDescription(other.getShortDescription());
            longDescription(other.getLongDescription());
            cta(other.getCta());
            tags(other.getTags());
            detailTags(other.getDetailTags());
            return this;
        }

        /**
         * <p>Short description for the offer</p>
         */
        @JsonSetter(value = "shortDescription", nulls = Nulls.SKIP)
        public Builder shortDescription(Optional<String> shortDescription) {
            this.shortDescription = shortDescription;
            return this;
        }

        public Builder shortDescription(String shortDescription) {
            this.shortDescription = Optional.ofNullable(shortDescription);
            return this;
        }

        /**
         * <p>Long description for the offer</p>
         */
        @JsonSetter(value = "longDescription", nulls = Nulls.SKIP)
        public Builder longDescription(Optional<String> longDescription) {
            this.longDescription = longDescription;
            return this;
        }

        public Builder longDescription(String longDescription) {
            this.longDescription = Optional.ofNullable(longDescription);
            return this;
        }

        /**
         * <p>Call-to-action button component</p>
         */
        @JsonSetter(value = "cta", nulls = Nulls.SKIP)
        public Builder cta(Optional<CtaComponent> cta) {
            this.cta = cta;
            return this;
        }

        public Builder cta(CtaComponent cta) {
            this.cta = Optional.ofNullable(cta);
            return this;
        }

        /**
         * <p>Tags for the offer</p>
         */
        @JsonSetter(value = "tags", nulls = Nulls.SKIP)
        public Builder tags(Optional<List<String>> tags) {
            this.tags = tags;
            return this;
        }

        public Builder tags(List<String> tags) {
            this.tags = Optional.ofNullable(tags);
            return this;
        }

        /**
         * <p>Detail tags for the offer</p>
         */
        @JsonSetter(value = "detailTags", nulls = Nulls.SKIP)
        public Builder detailTags(Optional<List<String>> detailTags) {
            this.detailTags = detailTags;
            return this;
        }

        public Builder detailTags(List<String> detailTags) {
            this.detailTags = Optional.ofNullable(detailTags);
            return this;
        }

        public OfferComponents build() {
            return new OfferComponents(shortDescription, longDescription, cta, tags, detailTags, additionalProperties);
        }
    }
}
