/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.rewards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OperationTime.Builder.class)
public final class OperationTime {
    private final int day;

    private final String time;

    private final Map<String, Object> additionalProperties;

    private OperationTime(int day, String time, Map<String, Object> additionalProperties) {
        this.day = day;
        this.time = time;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("day")
    public int getDay() {
        return day;
    }

    @JsonProperty("time")
    public String getTime() {
        return time;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OperationTime && equalTo((OperationTime) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OperationTime other) {
        return day == other.day && time.equals(other.time);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.day, this.time);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DayStage builder() {
        return new Builder();
    }

    public interface DayStage {
        TimeStage day(int day);

        Builder from(OperationTime other);
    }

    public interface TimeStage {
        _FinalStage time(@NotNull String time);
    }

    public interface _FinalStage {
        OperationTime build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DayStage, TimeStage, _FinalStage {
        private int day;

        private String time;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OperationTime other) {
            day(other.getDay());
            time(other.getTime());
            return this;
        }

        @java.lang.Override
        @JsonSetter("day")
        public TimeStage day(int day) {
            this.day = day;
            return this;
        }

        @java.lang.Override
        @JsonSetter("time")
        public _FinalStage time(@NotNull String time) {
            this.time = Objects.requireNonNull(time, "time must not be null");
            return this;
        }

        @java.lang.Override
        public OperationTime build() {
            return new OperationTime(day, time, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
