/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.rewards.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProgressBarSegmentLabel.Builder.class)
public final class ProgressBarSegmentLabel {
    private final String title;

    private final String description;

    private final Map<String, Object> additionalProperties;

    private ProgressBarSegmentLabel(String title, String description, Map<String, Object> additionalProperties) {
        this.title = title;
        this.description = description;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Title text for the segment node
     */
    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    /**
     * @return Description text for the segment node
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProgressBarSegmentLabel && equalTo((ProgressBarSegmentLabel) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProgressBarSegmentLabel other) {
        return title.equals(other.title) && description.equals(other.description);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.title, this.description);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TitleStage builder() {
        return new Builder();
    }

    public interface TitleStage {
        /**
         * <p>Title text for the segment node</p>
         */
        DescriptionStage title(@NotNull String title);

        Builder from(ProgressBarSegmentLabel other);
    }

    public interface DescriptionStage {
        /**
         * <p>Description text for the segment node</p>
         */
        _FinalStage description(@NotNull String description);
    }

    public interface _FinalStage {
        ProgressBarSegmentLabel build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TitleStage, DescriptionStage, _FinalStage {
        private String title;

        private String description;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProgressBarSegmentLabel other) {
            title(other.getTitle());
            description(other.getDescription());
            return this;
        }

        /**
         * <p>Title text for the segment node</p>
         * <p>Title text for the segment node</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("title")
        public DescriptionStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        /**
         * <p>Description text for the segment node</p>
         * <p>Description text for the segment node</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public _FinalStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        @java.lang.Override
        public ProgressBarSegmentLabel build() {
            return new ProgressBarSegmentLabel(title, description, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
