/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.internalorganizations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MerchantNetwork.Builder.class)
public final class MerchantNetwork {
    private final MerchantNetworkName name;

    private final int priority;

    private final Map<String, Object> additionalProperties;

    private MerchantNetwork(MerchantNetworkName name, int priority, Map<String, Object> additionalProperties) {
        this.name = name;
        this.priority = priority;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the merchant network
     */
    @JsonProperty("name")
    public MerchantNetworkName getName() {
        return name;
    }

    /**
     * @return Priority of the merchant network (higher = more preferred)
     */
    @JsonProperty("priority")
    public int getPriority() {
        return priority;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MerchantNetwork && equalTo((MerchantNetwork) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MerchantNetwork other) {
        return name.equals(other.name) && priority == other.priority;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.priority);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Name of the merchant network</p>
         */
        PriorityStage name(@NotNull MerchantNetworkName name);

        Builder from(MerchantNetwork other);
    }

    public interface PriorityStage {
        /**
         * <p>Priority of the merchant network (higher = more preferred)</p>
         */
        _FinalStage priority(int priority);
    }

    public interface _FinalStage {
        MerchantNetwork build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, PriorityStage, _FinalStage {
        private MerchantNetworkName name;

        private int priority;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MerchantNetwork other) {
            name(other.getName());
            priority(other.getPriority());
            return this;
        }

        /**
         * <p>Name of the merchant network</p>
         * <p>Name of the merchant network</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public PriorityStage name(@NotNull MerchantNetworkName name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Priority of the merchant network (higher = more preferred)</p>
         * <p>Priority of the merchant network (higher = more preferred)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("priority")
        public _FinalStage priority(int priority) {
            this.priority = priority;
            return this;
        }

        @java.lang.Override
        public MerchantNetwork build() {
            return new MerchantNetwork(name, priority, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
