/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.attributions.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InternalApiOfferAttributionAttributes.Builder.class)
public final class InternalApiOfferAttributionAttributes {
    private final String issuerId;

    private final String userId;

    private final String entityId;

    private final InternalEventCode eventCode;

    private final InternalOfferMedium medium;

    private final OffsetDateTime eventDate;

    private final Map<String, Object> additionalProperties;

    private InternalApiOfferAttributionAttributes(
            String issuerId,
            String userId,
            String entityId,
            InternalEventCode eventCode,
            InternalOfferMedium medium,
            OffsetDateTime eventDate,
            Map<String, Object> additionalProperties) {
        this.issuerId = issuerId;
        this.userId = userId;
        this.entityId = entityId;
        this.eventCode = eventCode;
        this.medium = medium;
        this.eventDate = eventDate;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("issuerId")
    public String getIssuerId() {
        return issuerId;
    }

    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    /**
     * @return The offer ID
     */
    @JsonProperty("entityId")
    public String getEntityId() {
        return entityId;
    }

    @JsonProperty("eventCode")
    public InternalEventCode getEventCode() {
        return eventCode;
    }

    @JsonProperty("medium")
    public InternalOfferMedium getMedium() {
        return medium;
    }

    /**
     * @return The timestamp of the attribution event.
     * Must be in ISO 8601 format (e.g., &quot;2025-01-01T00:00:00Z&quot;).
     */
    @JsonProperty("eventDate")
    public OffsetDateTime getEventDate() {
        return eventDate;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InternalApiOfferAttributionAttributes
                && equalTo((InternalApiOfferAttributionAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InternalApiOfferAttributionAttributes other) {
        return issuerId.equals(other.issuerId)
                && userId.equals(other.userId)
                && entityId.equals(other.entityId)
                && eventCode.equals(other.eventCode)
                && medium.equals(other.medium)
                && eventDate.equals(other.eventDate);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.issuerId, this.userId, this.entityId, this.eventCode, this.medium, this.eventDate);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IssuerIdStage builder() {
        return new Builder();
    }

    public interface IssuerIdStage {
        UserIdStage issuerId(@NotNull String issuerId);

        Builder from(InternalApiOfferAttributionAttributes other);
    }

    public interface UserIdStage {
        EntityIdStage userId(@NotNull String userId);
    }

    public interface EntityIdStage {
        /**
         * <p>The offer ID</p>
         */
        EventCodeStage entityId(@NotNull String entityId);
    }

    public interface EventCodeStage {
        MediumStage eventCode(@NotNull InternalEventCode eventCode);
    }

    public interface MediumStage {
        EventDateStage medium(@NotNull InternalOfferMedium medium);
    }

    public interface EventDateStage {
        /**
         * <p>The timestamp of the attribution event.
         * Must be in ISO 8601 format (e.g., &quot;2025-01-01T00:00:00Z&quot;).</p>
         */
        _FinalStage eventDate(@NotNull OffsetDateTime eventDate);
    }

    public interface _FinalStage {
        InternalApiOfferAttributionAttributes build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IssuerIdStage,
                    UserIdStage,
                    EntityIdStage,
                    EventCodeStage,
                    MediumStage,
                    EventDateStage,
                    _FinalStage {
        private String issuerId;

        private String userId;

        private String entityId;

        private InternalEventCode eventCode;

        private InternalOfferMedium medium;

        private OffsetDateTime eventDate;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InternalApiOfferAttributionAttributes other) {
            issuerId(other.getIssuerId());
            userId(other.getUserId());
            entityId(other.getEntityId());
            eventCode(other.getEventCode());
            medium(other.getMedium());
            eventDate(other.getEventDate());
            return this;
        }

        @java.lang.Override
        @JsonSetter("issuerId")
        public UserIdStage issuerId(@NotNull String issuerId) {
            this.issuerId = Objects.requireNonNull(issuerId, "issuerId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("userId")
        public EntityIdStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        /**
         * <p>The offer ID</p>
         * <p>The offer ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("entityId")
        public EventCodeStage entityId(@NotNull String entityId) {
            this.entityId = Objects.requireNonNull(entityId, "entityId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("eventCode")
        public MediumStage eventCode(@NotNull InternalEventCode eventCode) {
            this.eventCode = Objects.requireNonNull(eventCode, "eventCode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("medium")
        public EventDateStage medium(@NotNull InternalOfferMedium medium) {
            this.medium = Objects.requireNonNull(medium, "medium must not be null");
            return this;
        }

        /**
         * <p>The timestamp of the attribution event.
         * Must be in ISO 8601 format (e.g., &quot;2025-01-01T00:00:00Z&quot;).</p>
         * <p>The timestamp of the attribution event.
         * Must be in ISO 8601 format (e.g., &quot;2025-01-01T00:00:00Z&quot;).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("eventDate")
        public _FinalStage eventDate(@NotNull OffsetDateTime eventDate) {
            this.eventDate = Objects.requireNonNull(eventDate, "eventDate must not be null");
            return this;
        }

        @java.lang.Override
        public InternalApiOfferAttributionAttributes build() {
            return new InternalApiOfferAttributionAttributes(
                    issuerId, userId, entityId, eventCode, medium, eventDate, additionalProperties);
        }
    }
}
