/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.attributions.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InternalAttributionMessageMetadata.Builder.class)
public final class InternalAttributionMessageMetadata {
    private final String collectionName;

    private final String cellName;

    private final String issuerId;

    private final String userId;

    private final Map<String, Object> additionalProperties;

    private InternalAttributionMessageMetadata(
            String collectionName,
            String cellName,
            String issuerId,
            String userId,
            Map<String, Object> additionalProperties) {
        this.collectionName = collectionName;
        this.cellName = cellName;
        this.issuerId = issuerId;
        this.userId = userId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("collectionName")
    public String getCollectionName() {
        return collectionName;
    }

    @JsonProperty("cellName")
    public String getCellName() {
        return cellName;
    }

    @JsonProperty("issuerId")
    public String getIssuerId() {
        return issuerId;
    }

    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InternalAttributionMessageMetadata
                && equalTo((InternalAttributionMessageMetadata) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InternalAttributionMessageMetadata other) {
        return collectionName.equals(other.collectionName)
                && cellName.equals(other.cellName)
                && issuerId.equals(other.issuerId)
                && userId.equals(other.userId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.collectionName, this.cellName, this.issuerId, this.userId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CollectionNameStage builder() {
        return new Builder();
    }

    public interface CollectionNameStage {
        CellNameStage collectionName(@NotNull String collectionName);

        Builder from(InternalAttributionMessageMetadata other);
    }

    public interface CellNameStage {
        IssuerIdStage cellName(@NotNull String cellName);
    }

    public interface IssuerIdStage {
        UserIdStage issuerId(@NotNull String issuerId);
    }

    public interface UserIdStage {
        _FinalStage userId(@NotNull String userId);
    }

    public interface _FinalStage {
        InternalAttributionMessageMetadata build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CollectionNameStage, CellNameStage, IssuerIdStage, UserIdStage, _FinalStage {
        private String collectionName;

        private String cellName;

        private String issuerId;

        private String userId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InternalAttributionMessageMetadata other) {
            collectionName(other.getCollectionName());
            cellName(other.getCellName());
            issuerId(other.getIssuerId());
            userId(other.getUserId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("collectionName")
        public CellNameStage collectionName(@NotNull String collectionName) {
            this.collectionName = Objects.requireNonNull(collectionName, "collectionName must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("cellName")
        public IssuerIdStage cellName(@NotNull String cellName) {
            this.cellName = Objects.requireNonNull(cellName, "cellName must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("issuerId")
        public UserIdStage issuerId(@NotNull String issuerId) {
            this.issuerId = Objects.requireNonNull(issuerId, "issuerId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("userId")
        public _FinalStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        @java.lang.Override
        public InternalAttributionMessageMetadata build() {
            return new InternalAttributionMessageMetadata(
                    collectionName, cellName, issuerId, userId, additionalProperties);
        }
    }
}
