/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.attributions.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InternalOfferAttributionAttributes.Builder.class)
public final class InternalOfferAttributionAttributes {
    private final String entityId;

    private final InternalEventCode eventCode;

    private final InternalOfferMedium medium;

    private final OffsetDateTime eventDate;

    private final Map<String, Object> additionalProperties;

    private InternalOfferAttributionAttributes(
            String entityId,
            InternalEventCode eventCode,
            InternalOfferMedium medium,
            OffsetDateTime eventDate,
            Map<String, Object> additionalProperties) {
        this.entityId = entityId;
        this.eventCode = eventCode;
        this.medium = medium;
        this.eventDate = eventDate;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The offer ID
     */
    @JsonProperty("entityId")
    public String getEntityId() {
        return entityId;
    }

    @JsonProperty("eventCode")
    public InternalEventCode getEventCode() {
        return eventCode;
    }

    @JsonProperty("medium")
    public InternalOfferMedium getMedium() {
        return medium;
    }

    /**
     * @return The timestamp of the attribution event.
     * Must be in ISO 8601 format (e.g., &quot;2025-01-01T00:00:00Z&quot;).
     */
    @JsonProperty("eventDate")
    public OffsetDateTime getEventDate() {
        return eventDate;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InternalOfferAttributionAttributes
                && equalTo((InternalOfferAttributionAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InternalOfferAttributionAttributes other) {
        return entityId.equals(other.entityId)
                && eventCode.equals(other.eventCode)
                && medium.equals(other.medium)
                && eventDate.equals(other.eventDate);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.entityId, this.eventCode, this.medium, this.eventDate);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EntityIdStage builder() {
        return new Builder();
    }

    public interface EntityIdStage {
        /**
         * <p>The offer ID</p>
         */
        EventCodeStage entityId(@NotNull String entityId);

        Builder from(InternalOfferAttributionAttributes other);
    }

    public interface EventCodeStage {
        MediumStage eventCode(@NotNull InternalEventCode eventCode);
    }

    public interface MediumStage {
        EventDateStage medium(@NotNull InternalOfferMedium medium);
    }

    public interface EventDateStage {
        /**
         * <p>The timestamp of the attribution event.
         * Must be in ISO 8601 format (e.g., &quot;2025-01-01T00:00:00Z&quot;).</p>
         */
        _FinalStage eventDate(@NotNull OffsetDateTime eventDate);
    }

    public interface _FinalStage {
        InternalOfferAttributionAttributes build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements EntityIdStage, EventCodeStage, MediumStage, EventDateStage, _FinalStage {
        private String entityId;

        private InternalEventCode eventCode;

        private InternalOfferMedium medium;

        private OffsetDateTime eventDate;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InternalOfferAttributionAttributes other) {
            entityId(other.getEntityId());
            eventCode(other.getEventCode());
            medium(other.getMedium());
            eventDate(other.getEventDate());
            return this;
        }

        /**
         * <p>The offer ID</p>
         * <p>The offer ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("entityId")
        public EventCodeStage entityId(@NotNull String entityId) {
            this.entityId = Objects.requireNonNull(entityId, "entityId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("eventCode")
        public MediumStage eventCode(@NotNull InternalEventCode eventCode) {
            this.eventCode = Objects.requireNonNull(eventCode, "eventCode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("medium")
        public EventDateStage medium(@NotNull InternalOfferMedium medium) {
            this.medium = Objects.requireNonNull(medium, "medium must not be null");
            return this;
        }

        /**
         * <p>The timestamp of the attribution event.
         * Must be in ISO 8601 format (e.g., &quot;2025-01-01T00:00:00Z&quot;).</p>
         * <p>The timestamp of the attribution event.
         * Must be in ISO 8601 format (e.g., &quot;2025-01-01T00:00:00Z&quot;).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("eventDate")
        public _FinalStage eventDate(@NotNull OffsetDateTime eventDate) {
            this.eventDate = Objects.requireNonNull(eventDate, "eventDate must not be null");
            return this;
        }

        @java.lang.Override
        public InternalOfferAttributionAttributes build() {
            return new InternalOfferAttributionAttributes(entityId, eventCode, medium, eventDate, additionalProperties);
        }
    }
}
