/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.attributions.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.commons.types.Links;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InternalGetAttributionsResponse.Builder.class)
public final class InternalGetAttributionsResponse {
    private final List<InternalApiAttribution> data;

    private final Links links;

    private final Map<String, Object> additionalProperties;

    private InternalGetAttributionsResponse(
            List<InternalApiAttribution> data, Links links, Map<String, Object> additionalProperties) {
        this.data = data;
        this.links = links;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("data")
    public List<InternalApiAttribution> getData() {
        return data;
    }

    @JsonProperty("links")
    public Links getLinks() {
        return links;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InternalGetAttributionsResponse && equalTo((InternalGetAttributionsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InternalGetAttributionsResponse other) {
        return data.equals(other.data) && links.equals(other.links);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.links);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static LinksStage builder() {
        return new Builder();
    }

    public interface LinksStage {
        _FinalStage links(@NotNull Links links);

        Builder from(InternalGetAttributionsResponse other);
    }

    public interface _FinalStage {
        InternalGetAttributionsResponse build();

        _FinalStage data(List<InternalApiAttribution> data);

        _FinalStage addData(InternalApiAttribution data);

        _FinalStage addAllData(List<InternalApiAttribution> data);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements LinksStage, _FinalStage {
        private Links links;

        private List<InternalApiAttribution> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InternalGetAttributionsResponse other) {
            data(other.getData());
            links(other.getLinks());
            return this;
        }

        @java.lang.Override
        @JsonSetter("links")
        public _FinalStage links(@NotNull Links links) {
            this.links = Objects.requireNonNull(links, "links must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllData(List<InternalApiAttribution> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addData(InternalApiAttribution data) {
            this.data.add(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(List<InternalApiAttribution> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public InternalGetAttributionsResponse build() {
            return new InternalGetAttributionsResponse(data, links, additionalProperties);
        }
    }
}
