/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.auth.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = WebViewTokenResponse.Builder.class)
public final class WebViewTokenResponse {
    private final String accessToken;

    private final int expiresIn;

    private final String tokenType;

    private final Map<String, Object> additionalProperties;

    private WebViewTokenResponse(
            String accessToken, int expiresIn, String tokenType, Map<String, Object> additionalProperties) {
        this.accessToken = accessToken;
        this.expiresIn = expiresIn;
        this.tokenType = tokenType;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("access_token")
    public String getAccessToken() {
        return accessToken;
    }

    @JsonProperty("expires_in")
    public int getExpiresIn() {
        return expiresIn;
    }

    @JsonProperty("token_type")
    public String getTokenType() {
        return tokenType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof WebViewTokenResponse && equalTo((WebViewTokenResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(WebViewTokenResponse other) {
        return accessToken.equals(other.accessToken)
                && expiresIn == other.expiresIn
                && tokenType.equals(other.tokenType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.accessToken, this.expiresIn, this.tokenType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AccessTokenStage builder() {
        return new Builder();
    }

    public interface AccessTokenStage {
        ExpiresInStage accessToken(@NotNull String accessToken);

        Builder from(WebViewTokenResponse other);
    }

    public interface ExpiresInStage {
        TokenTypeStage expiresIn(int expiresIn);
    }

    public interface TokenTypeStage {
        _FinalStage tokenType(@NotNull String tokenType);
    }

    public interface _FinalStage {
        WebViewTokenResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AccessTokenStage, ExpiresInStage, TokenTypeStage, _FinalStage {
        private String accessToken;

        private int expiresIn;

        private String tokenType;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(WebViewTokenResponse other) {
            accessToken(other.getAccessToken());
            expiresIn(other.getExpiresIn());
            tokenType(other.getTokenType());
            return this;
        }

        @java.lang.Override
        @JsonSetter("access_token")
        public ExpiresInStage accessToken(@NotNull String accessToken) {
            this.accessToken = Objects.requireNonNull(accessToken, "accessToken must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("expires_in")
        public TokenTypeStage expiresIn(int expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        @java.lang.Override
        @JsonSetter("token_type")
        public _FinalStage tokenType(@NotNull String tokenType) {
            this.tokenType = Objects.requireNonNull(tokenType, "tokenType must not be null");
            return this;
        }

        @java.lang.Override
        public WebViewTokenResponse build() {
            return new WebViewTokenResponse(accessToken, expiresIn, tokenType, additionalProperties);
        }
    }
}
