/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.attributions.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ActivatePlacementSlotResponseAttributes.Builder.class)
public final class ActivatePlacementSlotResponseAttributes {
    private final String placementId;

    private final String slotId;

    private final String eventCode;

    private final String medium;

    private final OffsetDateTime eventDate;

    private final List<String> offerIds;

    private final Map<String, Object> additionalProperties;

    private ActivatePlacementSlotResponseAttributes(
            String placementId,
            String slotId,
            String eventCode,
            String medium,
            OffsetDateTime eventDate,
            List<String> offerIds,
            Map<String, Object> additionalProperties) {
        this.placementId = placementId;
        this.slotId = slotId;
        this.eventCode = eventCode;
        this.medium = medium;
        this.eventDate = eventDate;
        this.offerIds = offerIds;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier of the placement
     */
    @JsonProperty("placementId")
    public String getPlacementId() {
        return placementId;
    }

    /**
     * @return Stable identifier for the slot within the placement
     */
    @JsonProperty("slotId")
    public String getSlotId() {
        return slotId;
    }

    @JsonProperty("eventCode")
    public String getEventCode() {
        return eventCode;
    }

    @JsonProperty("medium")
    public String getMedium() {
        return medium;
    }

    @JsonProperty("eventDate")
    public OffsetDateTime getEventDate() {
        return eventDate;
    }

    /**
     * @return All offer IDs that resolved under the slot's content strategy and had
     * per-offer <code>offerAttribution</code> ACTIVATE events written. The partner can use
     * this to render the batch immediately without an extra round-trip.
     */
    @JsonProperty("offerIds")
    public List<String> getOfferIds() {
        return offerIds;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActivatePlacementSlotResponseAttributes
                && equalTo((ActivatePlacementSlotResponseAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ActivatePlacementSlotResponseAttributes other) {
        return placementId.equals(other.placementId)
                && slotId.equals(other.slotId)
                && eventCode.equals(other.eventCode)
                && medium.equals(other.medium)
                && eventDate.equals(other.eventDate)
                && offerIds.equals(other.offerIds);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.placementId, this.slotId, this.eventCode, this.medium, this.eventDate, this.offerIds);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PlacementIdStage builder() {
        return new Builder();
    }

    public interface PlacementIdStage {
        /**
         * <p>Unique identifier of the placement</p>
         */
        SlotIdStage placementId(@NotNull String placementId);

        Builder from(ActivatePlacementSlotResponseAttributes other);
    }

    public interface SlotIdStage {
        /**
         * <p>Stable identifier for the slot within the placement</p>
         */
        EventCodeStage slotId(@NotNull String slotId);
    }

    public interface EventCodeStage {
        MediumStage eventCode(@NotNull String eventCode);
    }

    public interface MediumStage {
        EventDateStage medium(@NotNull String medium);
    }

    public interface EventDateStage {
        _FinalStage eventDate(@NotNull OffsetDateTime eventDate);
    }

    public interface _FinalStage {
        ActivatePlacementSlotResponseAttributes build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>All offer IDs that resolved under the slot's content strategy and had
         * per-offer <code>offerAttribution</code> ACTIVATE events written. The partner can use
         * this to render the batch immediately without an extra round-trip.</p>
         */
        _FinalStage offerIds(List<String> offerIds);

        _FinalStage addOfferIds(String offerIds);

        _FinalStage addAllOfferIds(List<String> offerIds);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements PlacementIdStage, SlotIdStage, EventCodeStage, MediumStage, EventDateStage, _FinalStage {
        private String placementId;

        private String slotId;

        private String eventCode;

        private String medium;

        private OffsetDateTime eventDate;

        private List<String> offerIds = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ActivatePlacementSlotResponseAttributes other) {
            placementId(other.getPlacementId());
            slotId(other.getSlotId());
            eventCode(other.getEventCode());
            medium(other.getMedium());
            eventDate(other.getEventDate());
            offerIds(other.getOfferIds());
            return this;
        }

        /**
         * <p>Unique identifier of the placement</p>
         * <p>Unique identifier of the placement</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("placementId")
        public SlotIdStage placementId(@NotNull String placementId) {
            this.placementId = Objects.requireNonNull(placementId, "placementId must not be null");
            return this;
        }

        /**
         * <p>Stable identifier for the slot within the placement</p>
         * <p>Stable identifier for the slot within the placement</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("slotId")
        public EventCodeStage slotId(@NotNull String slotId) {
            this.slotId = Objects.requireNonNull(slotId, "slotId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("eventCode")
        public MediumStage eventCode(@NotNull String eventCode) {
            this.eventCode = Objects.requireNonNull(eventCode, "eventCode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("medium")
        public EventDateStage medium(@NotNull String medium) {
            this.medium = Objects.requireNonNull(medium, "medium must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("eventDate")
        public _FinalStage eventDate(@NotNull OffsetDateTime eventDate) {
            this.eventDate = Objects.requireNonNull(eventDate, "eventDate must not be null");
            return this;
        }

        /**
         * <p>All offer IDs that resolved under the slot's content strategy and had
         * per-offer <code>offerAttribution</code> ACTIVATE events written. The partner can use
         * this to render the batch immediately without an extra round-trip.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllOfferIds(List<String> offerIds) {
            if (offerIds != null) {
                this.offerIds.addAll(offerIds);
            }
            return this;
        }

        /**
         * <p>All offer IDs that resolved under the slot's content strategy and had
         * per-offer <code>offerAttribution</code> ACTIVATE events written. The partner can use
         * this to render the batch immediately without an extra round-trip.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addOfferIds(String offerIds) {
            this.offerIds.add(offerIds);
            return this;
        }

        /**
         * <p>All offer IDs that resolved under the slot's content strategy and had
         * per-offer <code>offerAttribution</code> ACTIVATE events written. The partner can use
         * this to render the batch immediately without an extra round-trip.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "offerIds", nulls = Nulls.SKIP)
        public _FinalStage offerIds(List<String> offerIds) {
            this.offerIds.clear();
            if (offerIds != null) {
                this.offerIds.addAll(offerIds);
            }
            return this;
        }

        @java.lang.Override
        public ActivatePlacementSlotResponseAttributes build() {
            return new ActivatePlacementSlotResponseAttributes(
                    placementId, slotId, eventCode, medium, eventDate, offerIds, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
