/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.attributions.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OfferMedium {
    public static final OfferMedium SEARCH = new OfferMedium(Value.SEARCH, "SEARCH");

    public static final OfferMedium BROWSE = new OfferMedium(Value.BROWSE, "BROWSE");

    public static final OfferMedium EMAIL = new OfferMedium(Value.EMAIL, "EMAIL");

    public static final OfferMedium MAP = new OfferMedium(Value.MAP, "MAP");

    private final Value value;

    private final String string;

    OfferMedium(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof OfferMedium && this.string.equals(((OfferMedium) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SEARCH:
                return visitor.visitSearch();
            case BROWSE:
                return visitor.visitBrowse();
            case EMAIL:
                return visitor.visitEmail();
            case MAP:
                return visitor.visitMap();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OfferMedium valueOf(String value) {
        switch (value) {
            case "SEARCH":
                return SEARCH;
            case "BROWSE":
                return BROWSE;
            case "EMAIL":
                return EMAIL;
            case "MAP":
                return MAP;
            default:
                return new OfferMedium(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        BROWSE,

        EMAIL,

        MAP,

        SEARCH,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitBrowse();

        T visitEmail();

        T visitMap();

        T visitSearch();

        T visitUnknown(String unknownType);
    }
}
