/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.offers;

import com.kard.api.core.ClientOptions;
import com.kard.api.core.RequestOptions;
import com.kard.api.resources.offers.requests.GetOfferByIdRequest;
import com.kard.api.resources.offers.requests.GetOffersRequest;
import com.kard.api.resources.offers.types.CreateOfferRequestBody;
import com.kard.api.resources.offers.types.OfferResponse;
import com.kard.api.resources.offers.types.OffersListResponse;
import com.kard.api.resources.offers.types.UpdateOfferRequestBody;

public class OffersClient {
    protected final ClientOptions clientOptions;

    private final RawOffersClient rawClient;

    public OffersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawOffersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawOffersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get offers
     */
    public OffersListResponse getOffers() {
        return this.rawClient.getOffers().body();
    }

    /**
     * Get offers
     */
    public OffersListResponse getOffers(GetOffersRequest request) {
        return this.rawClient.getOffers(request).body();
    }

    /**
     * Get offers
     */
    public OffersListResponse getOffers(GetOffersRequest request, RequestOptions requestOptions) {
        return this.rawClient.getOffers(request, requestOptions).body();
    }

    /**
     * Retrieve a specific offer by ID
     */
    public OfferResponse getOfferById(String offerId) {
        return this.rawClient.getOfferById(offerId).body();
    }

    /**
     * Retrieve a specific offer by ID
     */
    public OfferResponse getOfferById(String offerId, GetOfferByIdRequest request) {
        return this.rawClient.getOfferById(offerId, request).body();
    }

    /**
     * Retrieve a specific offer by ID
     */
    public OfferResponse getOfferById(String offerId, GetOfferByIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.getOfferById(offerId, request, requestOptions).body();
    }

    /**
     * Create a new offer
     */
    public OfferResponse createOffer(CreateOfferRequestBody request) {
        return this.rawClient.createOffer(request).body();
    }

    /**
     * Create a new offer
     */
    public OfferResponse createOffer(CreateOfferRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.createOffer(request, requestOptions).body();
    }

    /**
     * Update an existing offer (replaces all fields - omitted optional fields will be removed)
     */
    public OfferResponse updateOffer(String offerId, UpdateOfferRequestBody request) {
        return this.rawClient.updateOffer(offerId, request).body();
    }

    /**
     * Update an existing offer (replaces all fields - omitted optional fields will be removed)
     */
    public OfferResponse updateOffer(String offerId, UpdateOfferRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.updateOffer(offerId, request, requestOptions).body();
    }
}
