/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.billingagent.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BillingIssuerMatchedTransaction.Builder.class)
public final class BillingIssuerMatchedTransaction {
    private final OffsetDateTime timestamp;

    private final int amount;

    private final String merchantId;

    private final String merchantNetwork;

    private final String offerId;

    private final int commissionToIssuer;

    private final int receivedCommissionInCents;

    private final int usersCommissionInCents;

    private final Map<String, Object> additionalProperties;

    private BillingIssuerMatchedTransaction(
            OffsetDateTime timestamp,
            int amount,
            String merchantId,
            String merchantNetwork,
            String offerId,
            int commissionToIssuer,
            int receivedCommissionInCents,
            int usersCommissionInCents,
            Map<String, Object> additionalProperties) {
        this.timestamp = timestamp;
        this.amount = amount;
        this.merchantId = merchantId;
        this.merchantNetwork = merchantNetwork;
        this.offerId = offerId;
        this.commissionToIssuer = commissionToIssuer;
        this.receivedCommissionInCents = receivedCommissionInCents;
        this.usersCommissionInCents = usersCommissionInCents;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Transaction timestamp
     */
    @JsonProperty("timestamp")
    public OffsetDateTime getTimestamp() {
        return timestamp;
    }

    /**
     * @return Transaction amount in cents
     */
    @JsonProperty("amount")
    public int getAmount() {
        return amount;
    }

    /**
     * @return Merchant ID
     */
    @JsonProperty("merchantId")
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * @return Merchant network
     */
    @JsonProperty("merchantNetwork")
    public String getMerchantNetwork() {
        return merchantNetwork;
    }

    /**
     * @return The ID of the offer
     */
    @JsonProperty("offerId")
    public String getOfferId() {
        return offerId;
    }

    /**
     * @return Total Commission to issuer in cents
     */
    @JsonProperty("commissionToIssuer")
    public int getCommissionToIssuer() {
        return commissionToIssuer;
    }

    /**
     * @return Total Commission received by Kard in cents
     */
    @JsonProperty("receivedCommissionInCents")
    public int getReceivedCommissionInCents() {
        return receivedCommissionInCents;
    }

    /**
     * @return Total Commission received by cardholder in cents
     */
    @JsonProperty("usersCommissionInCents")
    public int getUsersCommissionInCents() {
        return usersCommissionInCents;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BillingIssuerMatchedTransaction && equalTo((BillingIssuerMatchedTransaction) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BillingIssuerMatchedTransaction other) {
        return timestamp.equals(other.timestamp)
                && amount == other.amount
                && merchantId.equals(other.merchantId)
                && merchantNetwork.equals(other.merchantNetwork)
                && offerId.equals(other.offerId)
                && commissionToIssuer == other.commissionToIssuer
                && receivedCommissionInCents == other.receivedCommissionInCents
                && usersCommissionInCents == other.usersCommissionInCents;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.timestamp,
                this.amount,
                this.merchantId,
                this.merchantNetwork,
                this.offerId,
                this.commissionToIssuer,
                this.receivedCommissionInCents,
                this.usersCommissionInCents);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TimestampStage builder() {
        return new Builder();
    }

    public interface TimestampStage {
        /**
         * <p>Transaction timestamp</p>
         */
        AmountStage timestamp(@NotNull OffsetDateTime timestamp);

        Builder from(BillingIssuerMatchedTransaction other);
    }

    public interface AmountStage {
        /**
         * <p>Transaction amount in cents</p>
         */
        MerchantIdStage amount(int amount);
    }

    public interface MerchantIdStage {
        /**
         * <p>Merchant ID</p>
         */
        MerchantNetworkStage merchantId(@NotNull String merchantId);
    }

    public interface MerchantNetworkStage {
        /**
         * <p>Merchant network</p>
         */
        OfferIdStage merchantNetwork(@NotNull String merchantNetwork);
    }

    public interface OfferIdStage {
        /**
         * <p>The ID of the offer</p>
         */
        CommissionToIssuerStage offerId(@NotNull String offerId);
    }

    public interface CommissionToIssuerStage {
        /**
         * <p>Total Commission to issuer in cents</p>
         */
        ReceivedCommissionInCentsStage commissionToIssuer(int commissionToIssuer);
    }

    public interface ReceivedCommissionInCentsStage {
        /**
         * <p>Total Commission received by Kard in cents</p>
         */
        UsersCommissionInCentsStage receivedCommissionInCents(int receivedCommissionInCents);
    }

    public interface UsersCommissionInCentsStage {
        /**
         * <p>Total Commission received by cardholder in cents</p>
         */
        _FinalStage usersCommissionInCents(int usersCommissionInCents);
    }

    public interface _FinalStage {
        BillingIssuerMatchedTransaction build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements TimestampStage,
                    AmountStage,
                    MerchantIdStage,
                    MerchantNetworkStage,
                    OfferIdStage,
                    CommissionToIssuerStage,
                    ReceivedCommissionInCentsStage,
                    UsersCommissionInCentsStage,
                    _FinalStage {
        private OffsetDateTime timestamp;

        private int amount;

        private String merchantId;

        private String merchantNetwork;

        private String offerId;

        private int commissionToIssuer;

        private int receivedCommissionInCents;

        private int usersCommissionInCents;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BillingIssuerMatchedTransaction other) {
            timestamp(other.getTimestamp());
            amount(other.getAmount());
            merchantId(other.getMerchantId());
            merchantNetwork(other.getMerchantNetwork());
            offerId(other.getOfferId());
            commissionToIssuer(other.getCommissionToIssuer());
            receivedCommissionInCents(other.getReceivedCommissionInCents());
            usersCommissionInCents(other.getUsersCommissionInCents());
            return this;
        }

        /**
         * <p>Transaction timestamp</p>
         * <p>Transaction timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("timestamp")
        public AmountStage timestamp(@NotNull OffsetDateTime timestamp) {
            this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
            return this;
        }

        /**
         * <p>Transaction amount in cents</p>
         * <p>Transaction amount in cents</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("amount")
        public MerchantIdStage amount(int amount) {
            this.amount = amount;
            return this;
        }

        /**
         * <p>Merchant ID</p>
         * <p>Merchant ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("merchantId")
        public MerchantNetworkStage merchantId(@NotNull String merchantId) {
            this.merchantId = Objects.requireNonNull(merchantId, "merchantId must not be null");
            return this;
        }

        /**
         * <p>Merchant network</p>
         * <p>Merchant network</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("merchantNetwork")
        public OfferIdStage merchantNetwork(@NotNull String merchantNetwork) {
            this.merchantNetwork = Objects.requireNonNull(merchantNetwork, "merchantNetwork must not be null");
            return this;
        }

        /**
         * <p>The ID of the offer</p>
         * <p>The ID of the offer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("offerId")
        public CommissionToIssuerStage offerId(@NotNull String offerId) {
            this.offerId = Objects.requireNonNull(offerId, "offerId must not be null");
            return this;
        }

        /**
         * <p>Total Commission to issuer in cents</p>
         * <p>Total Commission to issuer in cents</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("commissionToIssuer")
        public ReceivedCommissionInCentsStage commissionToIssuer(int commissionToIssuer) {
            this.commissionToIssuer = commissionToIssuer;
            return this;
        }

        /**
         * <p>Total Commission received by Kard in cents</p>
         * <p>Total Commission received by Kard in cents</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("receivedCommissionInCents")
        public UsersCommissionInCentsStage receivedCommissionInCents(int receivedCommissionInCents) {
            this.receivedCommissionInCents = receivedCommissionInCents;
            return this;
        }

        /**
         * <p>Total Commission received by cardholder in cents</p>
         * <p>Total Commission received by cardholder in cents</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("usersCommissionInCents")
        public _FinalStage usersCommissionInCents(int usersCommissionInCents) {
            this.usersCommissionInCents = usersCommissionInCents;
            return this;
        }

        @java.lang.Override
        public BillingIssuerMatchedTransaction build() {
            return new BillingIssuerMatchedTransaction(
                    timestamp,
                    amount,
                    merchantId,
                    merchantNetwork,
                    offerId,
                    commissionToIssuer,
                    receivedCommissionInCents,
                    usersCommissionInCents,
                    additionalProperties);
        }
    }
}
