/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.eligibilitybroker;

import com.kard.api.core.ClientOptions;
import com.kard.api.core.RequestOptions;
import com.kard.api.resources.eligibilitybroker.types.IngestRequestBody;
import java.util.concurrent.CompletableFuture;

public class AsyncEligibilityBrokerClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEligibilityBrokerClient rawClient;

    public AsyncEligibilityBrokerClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEligibilityBrokerClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEligibilityBrokerClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Send events to be ingested by the eligibility broker to change a user's eligibility.
     */
    public CompletableFuture<Void> ingest(IngestRequestBody request) {
        return this.rawClient.ingest(request).thenApply(response -> response.body());
    }

    /**
     * Send events to be ingested by the eligibility broker to change a user's eligibility.
     */
    public CompletableFuture<Void> ingest(IngestRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.ingest(request, requestOptions).thenApply(response -> response.body());
    }
}
