/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.uploads.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.commons.types.EmptyObject;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HistoricalTransactionCompleteNoData.Builder.class)
public final class HistoricalTransactionCompleteNoData {
    private final String id;

    private final EmptyObject attributes;

    private final Map<String, Object> additionalProperties;

    private HistoricalTransactionCompleteNoData(
            String id, EmptyObject attributes, Map<String, Object> additionalProperties) {
        this.id = id;
        this.attributes = attributes;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Upload id the issuer can use in reference to the upload session
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("attributes")
    public EmptyObject getAttributes() {
        return attributes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HistoricalTransactionCompleteNoData
                && equalTo((HistoricalTransactionCompleteNoData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HistoricalTransactionCompleteNoData other) {
        return id.equals(other.id) && attributes.equals(other.attributes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.attributes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Upload id the issuer can use in reference to the upload session</p>
         */
        AttributesStage id(@NotNull String id);

        Builder from(HistoricalTransactionCompleteNoData other);
    }

    public interface AttributesStage {
        _FinalStage attributes(@NotNull EmptyObject attributes);
    }

    public interface _FinalStage {
        HistoricalTransactionCompleteNoData build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, AttributesStage, _FinalStage {
        private String id;

        private EmptyObject attributes;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(HistoricalTransactionCompleteNoData other) {
            id(other.getId());
            attributes(other.getAttributes());
            return this;
        }

        /**
         * <p>Upload id the issuer can use in reference to the upload session</p>
         * <p>Upload id the issuer can use in reference to the upload session</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public AttributesStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("attributes")
        public _FinalStage attributes(@NotNull EmptyObject attributes) {
            this.attributes = Objects.requireNonNull(attributes, "attributes must not be null");
            return this;
        }

        @java.lang.Override
        public HistoricalTransactionCompleteNoData build() {
            return new HistoricalTransactionCompleteNoData(id, attributes, additionalProperties);
        }
    }
}
