/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.billingservice.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetRewardRequest.Builder.class)
public final class GetRewardRequest {
    private final Optional<Boolean> entries;

    private final Map<String, Object> additionalProperties;

    private GetRewardRequest(Optional<Boolean> entries, Map<String, Object> additionalProperties) {
        this.entries = entries;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Include reward entries in the response
     */
    @JsonProperty("entries")
    public Optional<Boolean> getEntries() {
        return entries;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetRewardRequest && equalTo((GetRewardRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetRewardRequest other) {
        return entries.equals(other.entries);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.entries);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> entries = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetRewardRequest other) {
            entries(other.getEntries());
            return this;
        }

        /**
         * <p>Include reward entries in the response</p>
         */
        @JsonSetter(value = "entries", nulls = Nulls.SKIP)
        public Builder entries(Optional<Boolean> entries) {
            this.entries = entries;
            return this;
        }

        public Builder entries(Boolean entries) {
            this.entries = Optional.ofNullable(entries);
            return this;
        }

        public GetRewardRequest build() {
            return new GetRewardRequest(entries, additionalProperties);
        }
    }
}
