/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.attributions;

import com.kard.api.core.ClientOptions;
import com.kard.api.core.RequestOptions;
import com.kard.api.resources.users.attributions.requests.ActivateOfferRequest;
import com.kard.api.resources.users.attributions.requests.BoostOfferRequest;
import com.kard.api.resources.users.attributions.types.ActivateOfferResponse;
import com.kard.api.resources.users.attributions.types.ActivatePlacementSlotResponse;
import com.kard.api.resources.users.attributions.types.BoostOfferResponse;
import com.kard.api.resources.users.attributions.types.CreateAttributionRequestObject;
import com.kard.api.resources.users.attributions.types.CreateAttributionResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncAttributionsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawAttributionsClient rawClient;

    public AsyncAttributionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawAttributionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawAttributionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Call this endpoint to send attribution events made by a single enrolled user for processing. A maximum of 100 events can be included in a single request.
     * <p><b>Required scopes:</b> <code>attributions:write</code></p>
     */
    public CompletableFuture<CreateAttributionResponse> create(
            String organizationId, String userId, CreateAttributionRequestObject request) {
        return this.rawClient.create(organizationId, userId, request).thenApply(response -> response.body());
    }

    /**
     * Call this endpoint to send attribution events made by a single enrolled user for processing. A maximum of 100 events can be included in a single request.
     * <p><b>Required scopes:</b> <code>attributions:write</code></p>
     */
    public CompletableFuture<CreateAttributionResponse> create(
            String organizationId,
            String userId,
            CreateAttributionRequestObject request,
            RequestOptions requestOptions) {
        return this.rawClient
                .create(organizationId, userId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Record when a user activates an offer. Creates an attribution event with eventCode=ACTIVATE and medium=CTA.
     * Optionally include the offer data by passing <code>include=offer</code>.
     */
    public CompletableFuture<ActivateOfferResponse> activate(String organizationId, String userId, String offerId) {
        return this.rawClient.activate(organizationId, userId, offerId).thenApply(response -> response.body());
    }

    /**
     * Record when a user activates an offer. Creates an attribution event with eventCode=ACTIVATE and medium=CTA.
     * Optionally include the offer data by passing <code>include=offer</code>.
     */
    public CompletableFuture<ActivateOfferResponse> activate(
            String organizationId, String userId, String offerId, RequestOptions requestOptions) {
        return this.rawClient
                .activate(organizationId, userId, offerId, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Record when a user activates an offer. Creates an attribution event with eventCode=ACTIVATE and medium=CTA.
     * Optionally include the offer data by passing <code>include=offer</code>.
     */
    public CompletableFuture<ActivateOfferResponse> activate(
            String organizationId, String userId, String offerId, ActivateOfferRequest request) {
        return this.rawClient.activate(organizationId, userId, offerId, request).thenApply(response -> response.body());
    }

    /**
     * Record when a user activates an offer. Creates an attribution event with eventCode=ACTIVATE and medium=CTA.
     * Optionally include the offer data by passing <code>include=offer</code>.
     */
    public CompletableFuture<ActivateOfferResponse> activate(
            String organizationId,
            String userId,
            String offerId,
            ActivateOfferRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .activate(organizationId, userId, offerId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Record when a user boosts an offer. Creates an attribution event with eventCode=BOOST and medium=CTA.
     * Optionally include the offer data by passing <code>include=offer</code>.
     */
    public CompletableFuture<BoostOfferResponse> boost(String organizationId, String userId, String offerId) {
        return this.rawClient.boost(organizationId, userId, offerId).thenApply(response -> response.body());
    }

    /**
     * Record when a user boosts an offer. Creates an attribution event with eventCode=BOOST and medium=CTA.
     * Optionally include the offer data by passing <code>include=offer</code>.
     */
    public CompletableFuture<BoostOfferResponse> boost(
            String organizationId, String userId, String offerId, RequestOptions requestOptions) {
        return this.rawClient
                .boost(organizationId, userId, offerId, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Record when a user boosts an offer. Creates an attribution event with eventCode=BOOST and medium=CTA.
     * Optionally include the offer data by passing <code>include=offer</code>.
     */
    public CompletableFuture<BoostOfferResponse> boost(
            String organizationId, String userId, String offerId, BoostOfferRequest request) {
        return this.rawClient.boost(organizationId, userId, offerId, request).thenApply(response -> response.body());
    }

    /**
     * Record when a user boosts an offer. Creates an attribution event with eventCode=BOOST and medium=CTA.
     * Optionally include the offer data by passing <code>include=offer</code>.
     */
    public CompletableFuture<BoostOfferResponse> boost(
            String organizationId,
            String userId,
            String offerId,
            BoostOfferRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .boost(organizationId, userId, offerId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Record when a user activates a batch-activation placement slot. Writes a slot-level
     * <code>placementSlotAttribution</code> ACTIVATE event and fans out a per-offer
     * <code>offerAttribution</code> ACTIVATE event for every offer resolved by the slot's content
     * strategy. The slot-level event id and the resolved <code>offerIds</code> are returned so the
     * partner can render the batch immediately without an extra <code>getBatchesByPlacement</code>
     * round-trip.
     * <p><b>Required scopes:</b> <code>attributions:write</code></p>
     */
    public CompletableFuture<ActivatePlacementSlotResponse> activatePlacementSlot(
            String organizationId, String userId, String placementId, String slotId) {
        return this.rawClient
                .activatePlacementSlot(organizationId, userId, placementId, slotId)
                .thenApply(response -> response.body());
    }

    /**
     * Record when a user activates a batch-activation placement slot. Writes a slot-level
     * <code>placementSlotAttribution</code> ACTIVATE event and fans out a per-offer
     * <code>offerAttribution</code> ACTIVATE event for every offer resolved by the slot's content
     * strategy. The slot-level event id and the resolved <code>offerIds</code> are returned so the
     * partner can render the batch immediately without an extra <code>getBatchesByPlacement</code>
     * round-trip.
     * <p><b>Required scopes:</b> <code>attributions:write</code></p>
     */
    public CompletableFuture<ActivatePlacementSlotResponse> activatePlacementSlot(
            String organizationId, String userId, String placementId, String slotId, RequestOptions requestOptions) {
        return this.rawClient
                .activatePlacementSlot(organizationId, userId, placementId, slotId, requestOptions)
                .thenApply(response -> response.body());
    }
}
