/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.transactions.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AuditStatus {
    public static final AuditStatus CLOSED = new AuditStatus(Value.CLOSED, "CLOSED");

    public static final AuditStatus IN_PROGRESS = new AuditStatus(Value.IN_PROGRESS, "IN_PROGRESS");

    public static final AuditStatus NEW = new AuditStatus(Value.NEW, "NEW");

    private final Value value;

    private final String string;

    AuditStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof AuditStatus && this.string.equals(((AuditStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CLOSED:
                return visitor.visitClosed();
            case IN_PROGRESS:
                return visitor.visitInProgress();
            case NEW:
                return visitor.visitNew();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AuditStatus valueOf(String value) {
        switch (value) {
            case "CLOSED":
                return CLOSED;
            case "IN_PROGRESS":
                return IN_PROGRESS;
            case "NEW":
                return NEW;
            default:
                return new AuditStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NEW,

        IN_PROGRESS,

        CLOSED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNew();

        T visitInProgress();

        T visitClosed();

        T visitUnknown(String unknownType);
    }
}
