/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.transactions.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CardNetwork {
    public static final CardNetwork DISCOVER = new CardNetwork(Value.DISCOVER, "DISCOVER");

    public static final CardNetwork VISA = new CardNetwork(Value.VISA, "VISA");

    public static final CardNetwork AMERICANEXPRESS = new CardNetwork(Value.AMERICANEXPRESS, "AMERICANEXPRESS");

    public static final CardNetwork MASTERCARD = new CardNetwork(Value.MASTERCARD, "MASTERCARD");

    private final Value value;

    private final String string;

    CardNetwork(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof CardNetwork && this.string.equals(((CardNetwork) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DISCOVER:
                return visitor.visitDiscover();
            case VISA:
                return visitor.visitVisa();
            case AMERICANEXPRESS:
                return visitor.visitAmericanexpress();
            case MASTERCARD:
                return visitor.visitMastercard();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CardNetwork valueOf(String value) {
        switch (value) {
            case "DISCOVER":
                return DISCOVER;
            case "VISA":
                return VISA;
            case "AMERICANEXPRESS":
                return AMERICANEXPRESS;
            case "MASTERCARD":
                return MASTERCARD;
            default:
                return new CardNetwork(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        VISA,

        MASTERCARD,

        AMERICANEXPRESS,

        DISCOVER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitVisa();

        T visitMastercard();

        T visitAmericanexpress();

        T visitDiscover();

        T visitUnknown(String unknownType);
    }
}
