/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.transactions.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TransactionStatus {
    public static final TransactionStatus RETURNED = new TransactionStatus(Value.RETURNED, "RETURNED");

    public static final TransactionStatus REVERSED = new TransactionStatus(Value.REVERSED, "REVERSED");

    public static final TransactionStatus DECLINED = new TransactionStatus(Value.DECLINED, "DECLINED");

    public static final TransactionStatus APPROVED = new TransactionStatus(Value.APPROVED, "APPROVED");

    public static final TransactionStatus SETTLED = new TransactionStatus(Value.SETTLED, "SETTLED");

    private final Value value;

    private final String string;

    TransactionStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TransactionStatus && this.string.equals(((TransactionStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case RETURNED:
                return visitor.visitReturned();
            case REVERSED:
                return visitor.visitReversed();
            case DECLINED:
                return visitor.visitDeclined();
            case APPROVED:
                return visitor.visitApproved();
            case SETTLED:
                return visitor.visitSettled();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TransactionStatus valueOf(String value) {
        switch (value) {
            case "RETURNED":
                return RETURNED;
            case "REVERSED":
                return REVERSED;
            case "DECLINED":
                return DECLINED;
            case "APPROVED":
                return APPROVED;
            case "SETTLED":
                return SETTLED;
            default:
                return new TransactionStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        APPROVED,

        SETTLED,

        REVERSED,

        RETURNED,

        DECLINED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitApproved();

        T visitSettled();

        T visitReversed();

        T visitReturned();

        T visitDeclined();

        T visitUnknown(String unknownType);
    }
}
