/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.placements.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Cadence.Builder.class)
public final class Cadence {
    private final CadenceFrequency frequency;

    private final Optional<String> timeOfDay;

    private final Optional<DayOfWeek> dayOfWeek;

    private final Optional<Integer> dayOfMonth;

    private final Map<String, Object> additionalProperties;

    private Cadence(
            CadenceFrequency frequency,
            Optional<String> timeOfDay,
            Optional<DayOfWeek> dayOfWeek,
            Optional<Integer> dayOfMonth,
            Map<String, Object> additionalProperties) {
        this.frequency = frequency;
        this.timeOfDay = timeOfDay;
        this.dayOfWeek = dayOfWeek;
        this.dayOfMonth = dayOfMonth;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Delivery frequency
     */
    @JsonProperty("frequency")
    public CadenceFrequency getFrequency() {
        return frequency;
    }

    /**
     * @return Optional time of day in HH:mm format (24-hour, UTC)
     */
    @JsonProperty("timeOfDay")
    public Optional<String> getTimeOfDay() {
        return timeOfDay;
    }

    /**
     * @return Day of the week to deliver (used when frequency is WEEKLY, defaults to MON)
     */
    @JsonProperty("dayOfWeek")
    public Optional<DayOfWeek> getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * @return Day of the month to deliver, 1-31 (used when frequency is MONTHLY, defaults to 1)
     */
    @JsonProperty("dayOfMonth")
    public Optional<Integer> getDayOfMonth() {
        return dayOfMonth;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Cadence && equalTo((Cadence) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Cadence other) {
        return frequency.equals(other.frequency)
                && timeOfDay.equals(other.timeOfDay)
                && dayOfWeek.equals(other.dayOfWeek)
                && dayOfMonth.equals(other.dayOfMonth);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.frequency, this.timeOfDay, this.dayOfWeek, this.dayOfMonth);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FrequencyStage builder() {
        return new Builder();
    }

    public interface FrequencyStage {
        /**
         * <p>Delivery frequency</p>
         */
        _FinalStage frequency(@NotNull CadenceFrequency frequency);

        Builder from(Cadence other);
    }

    public interface _FinalStage {
        Cadence build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Optional time of day in HH:mm format (24-hour, UTC)</p>
         */
        _FinalStage timeOfDay(Optional<String> timeOfDay);

        _FinalStage timeOfDay(String timeOfDay);

        /**
         * <p>Day of the week to deliver (used when frequency is WEEKLY, defaults to MON)</p>
         */
        _FinalStage dayOfWeek(Optional<DayOfWeek> dayOfWeek);

        _FinalStage dayOfWeek(DayOfWeek dayOfWeek);

        /**
         * <p>Day of the month to deliver, 1-31 (used when frequency is MONTHLY, defaults to 1)</p>
         */
        _FinalStage dayOfMonth(Optional<Integer> dayOfMonth);

        _FinalStage dayOfMonth(Integer dayOfMonth);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FrequencyStage, _FinalStage {
        private CadenceFrequency frequency;

        private Optional<Integer> dayOfMonth = Optional.empty();

        private Optional<DayOfWeek> dayOfWeek = Optional.empty();

        private Optional<String> timeOfDay = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Cadence other) {
            frequency(other.getFrequency());
            timeOfDay(other.getTimeOfDay());
            dayOfWeek(other.getDayOfWeek());
            dayOfMonth(other.getDayOfMonth());
            return this;
        }

        /**
         * <p>Delivery frequency</p>
         * <p>Delivery frequency</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("frequency")
        public _FinalStage frequency(@NotNull CadenceFrequency frequency) {
            this.frequency = Objects.requireNonNull(frequency, "frequency must not be null");
            return this;
        }

        /**
         * <p>Day of the month to deliver, 1-31 (used when frequency is MONTHLY, defaults to 1)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage dayOfMonth(Integer dayOfMonth) {
            this.dayOfMonth = Optional.ofNullable(dayOfMonth);
            return this;
        }

        /**
         * <p>Day of the month to deliver, 1-31 (used when frequency is MONTHLY, defaults to 1)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "dayOfMonth", nulls = Nulls.SKIP)
        public _FinalStage dayOfMonth(Optional<Integer> dayOfMonth) {
            this.dayOfMonth = dayOfMonth;
            return this;
        }

        /**
         * <p>Day of the week to deliver (used when frequency is WEEKLY, defaults to MON)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage dayOfWeek(DayOfWeek dayOfWeek) {
            this.dayOfWeek = Optional.ofNullable(dayOfWeek);
            return this;
        }

        /**
         * <p>Day of the week to deliver (used when frequency is WEEKLY, defaults to MON)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "dayOfWeek", nulls = Nulls.SKIP)
        public _FinalStage dayOfWeek(Optional<DayOfWeek> dayOfWeek) {
            this.dayOfWeek = dayOfWeek;
            return this;
        }

        /**
         * <p>Optional time of day in HH:mm format (24-hour, UTC)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage timeOfDay(String timeOfDay) {
            this.timeOfDay = Optional.ofNullable(timeOfDay);
            return this;
        }

        /**
         * <p>Optional time of day in HH:mm format (24-hour, UTC)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "timeOfDay", nulls = Nulls.SKIP)
        public _FinalStage timeOfDay(Optional<String> timeOfDay) {
            this.timeOfDay = timeOfDay;
            return this;
        }

        @java.lang.Override
        public Cadence build() {
            return new Cadence(frequency, timeOfDay, dayOfWeek, dayOfMonth, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
