/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.placements.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreatePushNotificationPlacementData.Builder.class)
public final class CreatePushNotificationPlacementData {
    private final CreatePushNotificationAttributes attributes;

    private final Map<String, Object> additionalProperties;

    private CreatePushNotificationPlacementData(
            CreatePushNotificationAttributes attributes, Map<String, Object> additionalProperties) {
        this.attributes = attributes;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Push-notification placement attributes for creation
     */
    @JsonProperty("attributes")
    public CreatePushNotificationAttributes getAttributes() {
        return attributes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreatePushNotificationPlacementData
                && equalTo((CreatePushNotificationPlacementData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreatePushNotificationPlacementData other) {
        return attributes.equals(other.attributes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.attributes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AttributesStage builder() {
        return new Builder();
    }

    public interface AttributesStage {
        /**
         * <p>Push-notification placement attributes for creation</p>
         */
        _FinalStage attributes(@NotNull CreatePushNotificationAttributes attributes);

        Builder from(CreatePushNotificationPlacementData other);
    }

    public interface _FinalStage {
        CreatePushNotificationPlacementData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AttributesStage, _FinalStage {
        private CreatePushNotificationAttributes attributes;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreatePushNotificationPlacementData other) {
            attributes(other.getAttributes());
            return this;
        }

        /**
         * <p>Push-notification placement attributes for creation</p>
         * <p>Push-notification placement attributes for creation</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("attributes")
        public _FinalStage attributes(@NotNull CreatePushNotificationAttributes attributes) {
            this.attributes = Objects.requireNonNull(attributes, "attributes must not be null");
            return this;
        }

        @java.lang.Override
        public CreatePushNotificationPlacementData build() {
            return new CreatePushNotificationPlacementData(attributes, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
