/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.placements.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmailPlacementAttributes.Builder.class)
public final class EmailPlacementAttributes {
    private final String name;

    private final String organizationId;

    private final int availableSlots;

    private final Cadence cadence;

    private final Optional<String> contentStrategyId;

    private final Map<String, Object> additionalProperties;

    private EmailPlacementAttributes(
            String name,
            String organizationId,
            int availableSlots,
            Cadence cadence,
            Optional<String> contentStrategyId,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.organizationId = organizationId;
        this.availableSlots = availableSlots;
        this.cadence = cadence;
        this.contentStrategyId = contentStrategyId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the placement
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return ID of the organization this placement belongs to
     */
    @JsonProperty("organizationId")
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * @return Number of available slots
     */
    @JsonProperty("availableSlots")
    public int getAvailableSlots() {
        return availableSlots;
    }

    /**
     * @return Delivery cadence for the email
     */
    @JsonProperty("cadence")
    public Cadence getCadence() {
        return cadence;
    }

    /**
     * @return ID of the content strategy linked to this placement, if any. Retained alongside <code>relationships.contentStrategy</code> for backward compatibility.
     */
    @JsonProperty("contentStrategyId")
    public Optional<String> getContentStrategyId() {
        return contentStrategyId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EmailPlacementAttributes && equalTo((EmailPlacementAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EmailPlacementAttributes other) {
        return name.equals(other.name)
                && organizationId.equals(other.organizationId)
                && availableSlots == other.availableSlots
                && cadence.equals(other.cadence)
                && contentStrategyId.equals(other.contentStrategyId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.organizationId, this.availableSlots, this.cadence, this.contentStrategyId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Name of the placement</p>
         */
        OrganizationIdStage name(@NotNull String name);

        Builder from(EmailPlacementAttributes other);
    }

    public interface OrganizationIdStage {
        /**
         * <p>ID of the organization this placement belongs to</p>
         */
        AvailableSlotsStage organizationId(@NotNull String organizationId);
    }

    public interface AvailableSlotsStage {
        /**
         * <p>Number of available slots</p>
         */
        CadenceStage availableSlots(int availableSlots);
    }

    public interface CadenceStage {
        /**
         * <p>Delivery cadence for the email</p>
         */
        _FinalStage cadence(@NotNull Cadence cadence);
    }

    public interface _FinalStage {
        EmailPlacementAttributes build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>ID of the content strategy linked to this placement, if any. Retained alongside <code>relationships.contentStrategy</code> for backward compatibility.</p>
         */
        _FinalStage contentStrategyId(Optional<String> contentStrategyId);

        _FinalStage contentStrategyId(String contentStrategyId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements NameStage, OrganizationIdStage, AvailableSlotsStage, CadenceStage, _FinalStage {
        private String name;

        private String organizationId;

        private int availableSlots;

        private Cadence cadence;

        private Optional<String> contentStrategyId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EmailPlacementAttributes other) {
            name(other.getName());
            organizationId(other.getOrganizationId());
            availableSlots(other.getAvailableSlots());
            cadence(other.getCadence());
            contentStrategyId(other.getContentStrategyId());
            return this;
        }

        /**
         * <p>Name of the placement</p>
         * <p>Name of the placement</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public OrganizationIdStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>ID of the organization this placement belongs to</p>
         * <p>ID of the organization this placement belongs to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("organizationId")
        public AvailableSlotsStage organizationId(@NotNull String organizationId) {
            this.organizationId = Objects.requireNonNull(organizationId, "organizationId must not be null");
            return this;
        }

        /**
         * <p>Number of available slots</p>
         * <p>Number of available slots</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("availableSlots")
        public CadenceStage availableSlots(int availableSlots) {
            this.availableSlots = availableSlots;
            return this;
        }

        /**
         * <p>Delivery cadence for the email</p>
         * <p>Delivery cadence for the email</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("cadence")
        public _FinalStage cadence(@NotNull Cadence cadence) {
            this.cadence = Objects.requireNonNull(cadence, "cadence must not be null");
            return this;
        }

        /**
         * <p>ID of the content strategy linked to this placement, if any. Retained alongside <code>relationships.contentStrategy</code> for backward compatibility.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage contentStrategyId(String contentStrategyId) {
            this.contentStrategyId = Optional.ofNullable(contentStrategyId);
            return this;
        }

        /**
         * <p>ID of the content strategy linked to this placement, if any. Retained alongside <code>relationships.contentStrategy</code> for backward compatibility.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "contentStrategyId", nulls = Nulls.SKIP)
        public _FinalStage contentStrategyId(Optional<String> contentStrategyId) {
            this.contentStrategyId = contentStrategyId;
            return this;
        }

        @java.lang.Override
        public EmailPlacementAttributes build() {
            return new EmailPlacementAttributes(
                    name, organizationId, availableSlots, cadence, contentStrategyId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
