/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.placements.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GroupPlacementData.Builder.class)
public final class GroupPlacementData {
    private final String id;

    private final GroupPlacementAttributes attributes;

    private final SlottedPlacementRelationships relationships;

    private final Map<String, Object> additionalProperties;

    private GroupPlacementData(
            String id,
            GroupPlacementAttributes attributes,
            SlottedPlacementRelationships relationships,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.attributes = attributes;
        this.relationships = relationships;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier of the placement (UUID v7)
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("attributes")
    public GroupPlacementAttributes getAttributes() {
        return attributes;
    }

    /**
     * @return JSON:API relationships for the placement. Always present on a group placement; the <code>slots</code> to-many relationship lists the slot resource identifiers.
     */
    @JsonProperty("relationships")
    public SlottedPlacementRelationships getRelationships() {
        return relationships;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GroupPlacementData && equalTo((GroupPlacementData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GroupPlacementData other) {
        return id.equals(other.id) && attributes.equals(other.attributes) && relationships.equals(other.relationships);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.attributes, this.relationships);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Unique identifier of the placement (UUID v7)</p>
         */
        AttributesStage id(@NotNull String id);

        Builder from(GroupPlacementData other);
    }

    public interface AttributesStage {
        RelationshipsStage attributes(@NotNull GroupPlacementAttributes attributes);
    }

    public interface RelationshipsStage {
        /**
         * <p>JSON:API relationships for the placement. Always present on a group placement; the <code>slots</code> to-many relationship lists the slot resource identifiers.</p>
         */
        _FinalStage relationships(@NotNull SlottedPlacementRelationships relationships);
    }

    public interface _FinalStage {
        GroupPlacementData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, AttributesStage, RelationshipsStage, _FinalStage {
        private String id;

        private GroupPlacementAttributes attributes;

        private SlottedPlacementRelationships relationships;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GroupPlacementData other) {
            id(other.getId());
            attributes(other.getAttributes());
            relationships(other.getRelationships());
            return this;
        }

        /**
         * <p>Unique identifier of the placement (UUID v7)</p>
         * <p>Unique identifier of the placement (UUID v7)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public AttributesStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("attributes")
        public RelationshipsStage attributes(@NotNull GroupPlacementAttributes attributes) {
            this.attributes = Objects.requireNonNull(attributes, "attributes must not be null");
            return this;
        }

        /**
         * <p>JSON:API relationships for the placement. Always present on a group placement; the <code>slots</code> to-many relationship lists the slot resource identifiers.</p>
         * <p>JSON:API relationships for the placement. Always present on a group placement; the <code>slots</code> to-many relationship lists the slot resource identifiers.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("relationships")
        public _FinalStage relationships(@NotNull SlottedPlacementRelationships relationships) {
            this.relationships = Objects.requireNonNull(relationships, "relationships must not be null");
            return this;
        }

        @java.lang.Override
        public GroupPlacementData build() {
            return new GroupPlacementData(id, attributes, relationships, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
