/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.organizations.placements.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PushNotificationPlacementAttributes.Builder.class)
public final class PushNotificationPlacementAttributes {
    private final String name;

    private final String organizationId;

    private final Cadence cadence;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime lastModified;

    private final Map<String, Object> additionalProperties;

    private PushNotificationPlacementAttributes(
            String name,
            String organizationId,
            Cadence cadence,
            OffsetDateTime createdAt,
            OffsetDateTime lastModified,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.organizationId = organizationId;
        this.cadence = cadence;
        this.createdAt = createdAt;
        this.lastModified = lastModified;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the placement
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return ID of the organization this placement belongs to
     */
    @JsonProperty("organizationId")
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * @return Delivery cadence for the notification
     */
    @JsonProperty("cadence")
    public Cadence getCadence() {
        return cadence;
    }

    /**
     * @return When the placement was created (ISO 8601 UTC)
     */
    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return When the placement was last modified (ISO 8601 UTC)
     */
    @JsonProperty("lastModified")
    public OffsetDateTime getLastModified() {
        return lastModified;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PushNotificationPlacementAttributes
                && equalTo((PushNotificationPlacementAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PushNotificationPlacementAttributes other) {
        return name.equals(other.name)
                && organizationId.equals(other.organizationId)
                && cadence.equals(other.cadence)
                && createdAt.equals(other.createdAt)
                && lastModified.equals(other.lastModified);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.organizationId, this.cadence, this.createdAt, this.lastModified);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Name of the placement</p>
         */
        OrganizationIdStage name(@NotNull String name);

        Builder from(PushNotificationPlacementAttributes other);
    }

    public interface OrganizationIdStage {
        /**
         * <p>ID of the organization this placement belongs to</p>
         */
        CadenceStage organizationId(@NotNull String organizationId);
    }

    public interface CadenceStage {
        /**
         * <p>Delivery cadence for the notification</p>
         */
        CreatedAtStage cadence(@NotNull Cadence cadence);
    }

    public interface CreatedAtStage {
        /**
         * <p>When the placement was created (ISO 8601 UTC)</p>
         */
        LastModifiedStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface LastModifiedStage {
        /**
         * <p>When the placement was last modified (ISO 8601 UTC)</p>
         */
        _FinalStage lastModified(@NotNull OffsetDateTime lastModified);
    }

    public interface _FinalStage {
        PushNotificationPlacementAttributes build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements NameStage, OrganizationIdStage, CadenceStage, CreatedAtStage, LastModifiedStage, _FinalStage {
        private String name;

        private String organizationId;

        private Cadence cadence;

        private OffsetDateTime createdAt;

        private OffsetDateTime lastModified;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PushNotificationPlacementAttributes other) {
            name(other.getName());
            organizationId(other.getOrganizationId());
            cadence(other.getCadence());
            createdAt(other.getCreatedAt());
            lastModified(other.getLastModified());
            return this;
        }

        /**
         * <p>Name of the placement</p>
         * <p>Name of the placement</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public OrganizationIdStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>ID of the organization this placement belongs to</p>
         * <p>ID of the organization this placement belongs to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("organizationId")
        public CadenceStage organizationId(@NotNull String organizationId) {
            this.organizationId = Objects.requireNonNull(organizationId, "organizationId must not be null");
            return this;
        }

        /**
         * <p>Delivery cadence for the notification</p>
         * <p>Delivery cadence for the notification</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("cadence")
        public CreatedAtStage cadence(@NotNull Cadence cadence) {
            this.cadence = Objects.requireNonNull(cadence, "cadence must not be null");
            return this;
        }

        /**
         * <p>When the placement was created (ISO 8601 UTC)</p>
         * <p>When the placement was created (ISO 8601 UTC)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAt")
        public LastModifiedStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>When the placement was last modified (ISO 8601 UTC)</p>
         * <p>When the placement was last modified (ISO 8601 UTC)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("lastModified")
        public _FinalStage lastModified(@NotNull OffsetDateTime lastModified) {
            this.lastModified = Objects.requireNonNull(lastModified, "lastModified must not be null");
            return this;
        }

        @java.lang.Override
        public PushNotificationPlacementAttributes build() {
            return new PushNotificationPlacementAttributes(
                    name, organizationId, cadence, createdAt, lastModified, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
