/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BrokerAmountType {
    public static final BrokerAmountType CENTS = new BrokerAmountType(Value.CENTS, "CENTS");

    private final Value value;

    private final String string;

    BrokerAmountType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BrokerAmountType && this.string.equals(((BrokerAmountType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CENTS:
                return visitor.visitCents();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BrokerAmountType valueOf(String value) {
        switch (value) {
            case "CENTS":
                return CENTS;
            default:
                return new BrokerAmountType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CENTS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCents();

        T visitUnknown(String unknownType);
    }
}
