/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.commons.types.RelationshipSingle;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmailNotificationPlacementFileRelationships.Builder.class)
public final class EmailNotificationPlacementFileRelationships {
    private final RelationshipSingle placement;

    private final Optional<RelationshipSingle> contentStrategy;

    private final Map<String, Object> additionalProperties;

    private EmailNotificationPlacementFileRelationships(
            RelationshipSingle placement,
            Optional<RelationshipSingle> contentStrategy,
            Map<String, Object> additionalProperties) {
        this.placement = placement;
        this.contentStrategy = contentStrategy;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("placement")
    public RelationshipSingle getPlacement() {
        return placement;
    }

    @JsonProperty("contentStrategy")
    public Optional<RelationshipSingle> getContentStrategy() {
        return contentStrategy;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EmailNotificationPlacementFileRelationships
                && equalTo((EmailNotificationPlacementFileRelationships) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EmailNotificationPlacementFileRelationships other) {
        return placement.equals(other.placement) && contentStrategy.equals(other.contentStrategy);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.placement, this.contentStrategy);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PlacementStage builder() {
        return new Builder();
    }

    public interface PlacementStage {
        _FinalStage placement(@NotNull RelationshipSingle placement);

        Builder from(EmailNotificationPlacementFileRelationships other);
    }

    public interface _FinalStage {
        EmailNotificationPlacementFileRelationships build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage contentStrategy(Optional<RelationshipSingle> contentStrategy);

        _FinalStage contentStrategy(RelationshipSingle contentStrategy);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PlacementStage, _FinalStage {
        private RelationshipSingle placement;

        private Optional<RelationshipSingle> contentStrategy = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EmailNotificationPlacementFileRelationships other) {
            placement(other.getPlacement());
            contentStrategy(other.getContentStrategy());
            return this;
        }

        @java.lang.Override
        @JsonSetter("placement")
        public _FinalStage placement(@NotNull RelationshipSingle placement) {
            this.placement = Objects.requireNonNull(placement, "placement must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage contentStrategy(RelationshipSingle contentStrategy) {
            this.contentStrategy = Optional.ofNullable(contentStrategy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "contentStrategy", nulls = Nulls.SKIP)
        public _FinalStage contentStrategy(Optional<RelationshipSingle> contentStrategy) {
            this.contentStrategy = contentStrategy;
            return this;
        }

        @java.lang.Override
        public EmailNotificationPlacementFileRelationships build() {
            return new EmailNotificationPlacementFileRelationships(placement, contentStrategy, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
