/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.files.types.FileMetadataAttribute;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FileResultData.Builder.class)
public final class FileResultData {
    private final String id;

    private final FileMetadataAttribute attributes;

    private final Map<String, Object> additionalProperties;

    private FileResultData(String id, FileMetadataAttribute attributes, Map<String, Object> additionalProperties) {
        this.id = id;
        this.attributes = attributes;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The internal ID of the notification
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("attributes")
    public FileMetadataAttribute getAttributes() {
        return attributes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FileResultData && equalTo((FileResultData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FileResultData other) {
        return id.equals(other.id) && attributes.equals(other.attributes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.attributes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The internal ID of the notification</p>
         */
        AttributesStage id(@NotNull String id);

        Builder from(FileResultData other);
    }

    public interface AttributesStage {
        _FinalStage attributes(@NotNull FileMetadataAttribute attributes);
    }

    public interface _FinalStage {
        FileResultData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, AttributesStage, _FinalStage {
        private String id;

        private FileMetadataAttribute attributes;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FileResultData other) {
            id(other.getId());
            attributes(other.getAttributes());
            return this;
        }

        /**
         * <p>The internal ID of the notification</p>
         * <p>The internal ID of the notification</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public AttributesStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("attributes")
        public _FinalStage attributes(@NotNull FileMetadataAttribute attributes) {
            this.attributes = Objects.requireNonNull(attributes, "attributes must not be null");
            return this;
        }

        @java.lang.Override
        public FileResultData build() {
            return new FileResultData(id, attributes, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
