/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = NotificationMetadata.Builder.class)
public final class NotificationMetadata {
    private final String issuerId;

    private final String issuerName;

    private final Map<String, Object> additionalProperties;

    private NotificationMetadata(String issuerId, String issuerName, Map<String, Object> additionalProperties) {
        this.issuerId = issuerId;
        this.issuerName = issuerName;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("issuerId")
    public String getIssuerId() {
        return issuerId;
    }

    @JsonProperty("issuerName")
    public String getIssuerName() {
        return issuerName;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof NotificationMetadata && equalTo((NotificationMetadata) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(NotificationMetadata other) {
        return issuerId.equals(other.issuerId) && issuerName.equals(other.issuerName);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.issuerId, this.issuerName);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IssuerIdStage builder() {
        return new Builder();
    }

    public interface IssuerIdStage {
        IssuerNameStage issuerId(@NotNull String issuerId);

        Builder from(NotificationMetadata other);
    }

    public interface IssuerNameStage {
        _FinalStage issuerName(@NotNull String issuerName);
    }

    public interface _FinalStage {
        NotificationMetadata build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IssuerIdStage, IssuerNameStage, _FinalStage {
        private String issuerId;

        private String issuerName;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(NotificationMetadata other) {
            issuerId(other.getIssuerId());
            issuerName(other.getIssuerName());
            return this;
        }

        @java.lang.Override
        @JsonSetter("issuerId")
        public IssuerNameStage issuerId(@NotNull String issuerId) {
            this.issuerId = Objects.requireNonNull(issuerId, "issuerId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("issuerName")
        public _FinalStage issuerName(@NotNull String issuerName) {
            this.issuerName = Objects.requireNonNull(issuerName, "issuerName must not be null");
            return this;
        }

        @java.lang.Override
        public NotificationMetadata build() {
            return new NotificationMetadata(issuerId, issuerName, additionalProperties);
        }
    }
}
