/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OfferStatus {
    public static final OfferStatus ACTIVE = new OfferStatus(Value.ACTIVE, "ACTIVE");

    public static final OfferStatus INACTIVE = new OfferStatus(Value.INACTIVE, "INACTIVE");

    private final Value value;

    private final String string;

    OfferStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof OfferStatus && this.string.equals(((OfferStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ACTIVE:
                return visitor.visitActive();
            case INACTIVE:
                return visitor.visitInactive();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OfferStatus valueOf(String value) {
        switch (value) {
            case "ACTIVE":
                return ACTIVE;
            case "INACTIVE":
                return INACTIVE;
            default:
                return new OfferStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        INACTIVE,

        ACTIVE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitInactive();

        T visitActive();

        T visitUnknown(String unknownType);
    }
}
