/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PushNotificationPlacementFileData.Builder.class)
public final class PushNotificationPlacementFileData {
    private final String id;

    private final PushNotificationPlacementFileAttributes attributes;

    private final PushNotificationPlacementFileRelationships relationships;

    private final Map<String, Object> additionalProperties;

    private PushNotificationPlacementFileData(
            String id,
            PushNotificationPlacementFileAttributes attributes,
            PushNotificationPlacementFileRelationships relationships,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.attributes = attributes;
        this.relationships = relationships;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The placement ID, also used as the notification resource ID
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("attributes")
    public PushNotificationPlacementFileAttributes getAttributes() {
        return attributes;
    }

    @JsonProperty("relationships")
    public PushNotificationPlacementFileRelationships getRelationships() {
        return relationships;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PushNotificationPlacementFileData && equalTo((PushNotificationPlacementFileData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PushNotificationPlacementFileData other) {
        return id.equals(other.id) && attributes.equals(other.attributes) && relationships.equals(other.relationships);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.attributes, this.relationships);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The placement ID, also used as the notification resource ID</p>
         */
        AttributesStage id(@NotNull String id);

        Builder from(PushNotificationPlacementFileData other);
    }

    public interface AttributesStage {
        RelationshipsStage attributes(@NotNull PushNotificationPlacementFileAttributes attributes);
    }

    public interface RelationshipsStage {
        _FinalStage relationships(@NotNull PushNotificationPlacementFileRelationships relationships);
    }

    public interface _FinalStage {
        PushNotificationPlacementFileData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, AttributesStage, RelationshipsStage, _FinalStage {
        private String id;

        private PushNotificationPlacementFileAttributes attributes;

        private PushNotificationPlacementFileRelationships relationships;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PushNotificationPlacementFileData other) {
            id(other.getId());
            attributes(other.getAttributes());
            relationships(other.getRelationships());
            return this;
        }

        /**
         * <p>The placement ID, also used as the notification resource ID</p>
         * <p>The placement ID, also used as the notification resource ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public AttributesStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("attributes")
        public RelationshipsStage attributes(@NotNull PushNotificationPlacementFileAttributes attributes) {
            this.attributes = Objects.requireNonNull(attributes, "attributes must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("relationships")
        public _FinalStage relationships(@NotNull PushNotificationPlacementFileRelationships relationships) {
            this.relationships = Objects.requireNonNull(relationships, "relationships must not be null");
            return this;
        }

        @java.lang.Override
        public PushNotificationPlacementFileData build() {
            return new PushNotificationPlacementFileData(id, attributes, relationships, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
