/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.commons.types.RelationshipSingle;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TransactionRelationships.Builder.class)
public final class TransactionRelationships {
    private final RelationshipSingle user;

    private final RelationshipSingle offer;

    private final RelationshipSingle transaction;

    private final Map<String, Object> additionalProperties;

    private TransactionRelationships(
            RelationshipSingle user,
            RelationshipSingle offer,
            RelationshipSingle transaction,
            Map<String, Object> additionalProperties) {
        this.user = user;
        this.offer = offer;
        this.transaction = transaction;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("user")
    public RelationshipSingle getUser() {
        return user;
    }

    @JsonProperty("offer")
    public RelationshipSingle getOffer() {
        return offer;
    }

    @JsonProperty("transaction")
    public RelationshipSingle getTransaction() {
        return transaction;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TransactionRelationships && equalTo((TransactionRelationships) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TransactionRelationships other) {
        return user.equals(other.user) && offer.equals(other.offer) && transaction.equals(other.transaction);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.user, this.offer, this.transaction);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static UserStage builder() {
        return new Builder();
    }

    public interface UserStage {
        OfferStage user(@NotNull RelationshipSingle user);

        Builder from(TransactionRelationships other);
    }

    public interface OfferStage {
        TransactionStage offer(@NotNull RelationshipSingle offer);
    }

    public interface TransactionStage {
        _FinalStage transaction(@NotNull RelationshipSingle transaction);
    }

    public interface _FinalStage {
        TransactionRelationships build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UserStage, OfferStage, TransactionStage, _FinalStage {
        private RelationshipSingle user;

        private RelationshipSingle offer;

        private RelationshipSingle transaction;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TransactionRelationships other) {
            user(other.getUser());
            offer(other.getOffer());
            transaction(other.getTransaction());
            return this;
        }

        @java.lang.Override
        @JsonSetter("user")
        public OfferStage user(@NotNull RelationshipSingle user) {
            this.user = Objects.requireNonNull(user, "user must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("offer")
        public TransactionStage offer(@NotNull RelationshipSingle offer) {
            this.offer = Objects.requireNonNull(offer, "offer must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("transaction")
        public _FinalStage transaction(@NotNull RelationshipSingle transaction) {
            this.transaction = Objects.requireNonNull(transaction, "transaction must not be null");
            return this;
        }

        @java.lang.Override
        public TransactionRelationships build() {
            return new TransactionRelationships(user, offer, transaction, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
