/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = WebhookUserOfferData.Builder.class)
public final class WebhookUserOfferData {
    private final String id;

    private final WebhookUserOfferAttributes attributes;

    private final WebhookUserOfferRelationships relationships;

    private final Map<String, Object> additionalProperties;

    private WebhookUserOfferData(
            String id,
            WebhookUserOfferAttributes attributes,
            WebhookUserOfferRelationships relationships,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.attributes = attributes;
        this.relationships = relationships;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The internal ID of the notification
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("attributes")
    public WebhookUserOfferAttributes getAttributes() {
        return attributes;
    }

    @JsonProperty("relationships")
    public WebhookUserOfferRelationships getRelationships() {
        return relationships;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof WebhookUserOfferData && equalTo((WebhookUserOfferData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(WebhookUserOfferData other) {
        return id.equals(other.id) && attributes.equals(other.attributes) && relationships.equals(other.relationships);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.attributes, this.relationships);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The internal ID of the notification</p>
         */
        AttributesStage id(@NotNull String id);

        Builder from(WebhookUserOfferData other);
    }

    public interface AttributesStage {
        RelationshipsStage attributes(@NotNull WebhookUserOfferAttributes attributes);
    }

    public interface RelationshipsStage {
        _FinalStage relationships(@NotNull WebhookUserOfferRelationships relationships);
    }

    public interface _FinalStage {
        WebhookUserOfferData build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, AttributesStage, RelationshipsStage, _FinalStage {
        private String id;

        private WebhookUserOfferAttributes attributes;

        private WebhookUserOfferRelationships relationships;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(WebhookUserOfferData other) {
            id(other.getId());
            attributes(other.getAttributes());
            relationships(other.getRelationships());
            return this;
        }

        /**
         * <p>The internal ID of the notification</p>
         * <p>The internal ID of the notification</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public AttributesStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("attributes")
        public RelationshipsStage attributes(@NotNull WebhookUserOfferAttributes attributes) {
            this.attributes = Objects.requireNonNull(attributes, "attributes must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("relationships")
        public _FinalStage relationships(@NotNull WebhookUserOfferRelationships relationships) {
            this.relationships = Objects.requireNonNull(relationships, "relationships must not be null");
            return this;
        }

        @java.lang.Override
        public WebhookUserOfferData build() {
            return new WebhookUserOfferData(id, attributes, relationships, additionalProperties);
        }
    }
}
