/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.commons.types.RelationshipSingle;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = WebhookOfferRelationships.Builder.class)
public final class WebhookOfferRelationships {
    private final RelationshipSingle merchant;

    private final Map<String, Object> additionalProperties;

    private WebhookOfferRelationships(RelationshipSingle merchant, Map<String, Object> additionalProperties) {
        this.merchant = merchant;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("merchant")
    public RelationshipSingle getMerchant() {
        return merchant;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof WebhookOfferRelationships && equalTo((WebhookOfferRelationships) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(WebhookOfferRelationships other) {
        return merchant.equals(other.merchant);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.merchant);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MerchantStage builder() {
        return new Builder();
    }

    public interface MerchantStage {
        _FinalStage merchant(@NotNull RelationshipSingle merchant);

        Builder from(WebhookOfferRelationships other);
    }

    public interface _FinalStage {
        WebhookOfferRelationships build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MerchantStage, _FinalStage {
        private RelationshipSingle merchant;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(WebhookOfferRelationships other) {
            merchant(other.getMerchant());
            return this;
        }

        @java.lang.Override
        @JsonSetter("merchant")
        public _FinalStage merchant(@NotNull RelationshipSingle merchant) {
            this.merchant = Objects.requireNonNull(merchant, "merchant must not be null");
            return this;
        }

        @java.lang.Override
        public WebhookOfferRelationships build() {
            return new WebhookOfferRelationships(merchant, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
