/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.offers.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.commons.types.CommissionType;
import com.kard.api.resources.commons.types.LocationType;
import com.kard.api.resources.commons.types.Source;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OfferAttributes.Builder.class)
public final class OfferAttributes {
    private final String name;

    private final Optional<LocationType> offerType;

    private final String merchantId;

    private final Optional<Boolean> isLocationSpecific;

    private final Status status;

    private final String merchantNetwork;

    private final Optional<List<String>> merchantLocationIds;

    private final Optional<Boolean> optInRequired;

    private final List<String> qualifiedIssuer;

    private final CommissionType commissionType;

    private final double commissionValue;

    private final Map<String, Double> issuerCommissionsMap;

    private final Optional<Map<String, Double>> userCommissionsMap;

    private final Optional<Boolean> isCustom;

    private final Optional<String> terms;

    private final Optional<Integer> minTransactionAmount;

    private final Optional<Integer> maxTransactionAmount;

    private final Optional<Integer> minRewardAmount;

    private final Optional<Integer> maxRewardAmount;

    private final Optional<Integer> minUserRewardAmount;

    private final Optional<Integer> maxUserRewardAmount;

    private final OffsetDateTime startDate;

    private final OffsetDateTime expirationDate;

    private final Optional<Boolean> redeemableOnce;

    private final Source source;

    private final Optional<Map<String, Boolean>> validOfferForIssuer;

    private final Optional<String> category;

    private final Optional<List<String>> mcc;

    private final Optional<Boolean> displayAlways;

    private final Optional<List<String>> audiences;

    private final Optional<List<String>> segments;

    private final Optional<String> partnerOfferId;

    private final boolean isTargeted;

    private final Attribution attribution;

    private final Optional<OffsetDateTime> createdDate;

    private final Optional<OffsetDateTime> lastModified;

    private final Map<String, Object> additionalProperties;

    private OfferAttributes(
            String name,
            Optional<LocationType> offerType,
            String merchantId,
            Optional<Boolean> isLocationSpecific,
            Status status,
            String merchantNetwork,
            Optional<List<String>> merchantLocationIds,
            Optional<Boolean> optInRequired,
            List<String> qualifiedIssuer,
            CommissionType commissionType,
            double commissionValue,
            Map<String, Double> issuerCommissionsMap,
            Optional<Map<String, Double>> userCommissionsMap,
            Optional<Boolean> isCustom,
            Optional<String> terms,
            Optional<Integer> minTransactionAmount,
            Optional<Integer> maxTransactionAmount,
            Optional<Integer> minRewardAmount,
            Optional<Integer> maxRewardAmount,
            Optional<Integer> minUserRewardAmount,
            Optional<Integer> maxUserRewardAmount,
            OffsetDateTime startDate,
            OffsetDateTime expirationDate,
            Optional<Boolean> redeemableOnce,
            Source source,
            Optional<Map<String, Boolean>> validOfferForIssuer,
            Optional<String> category,
            Optional<List<String>> mcc,
            Optional<Boolean> displayAlways,
            Optional<List<String>> audiences,
            Optional<List<String>> segments,
            Optional<String> partnerOfferId,
            boolean isTargeted,
            Attribution attribution,
            Optional<OffsetDateTime> createdDate,
            Optional<OffsetDateTime> lastModified,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.offerType = offerType;
        this.merchantId = merchantId;
        this.isLocationSpecific = isLocationSpecific;
        this.status = status;
        this.merchantNetwork = merchantNetwork;
        this.merchantLocationIds = merchantLocationIds;
        this.optInRequired = optInRequired;
        this.qualifiedIssuer = qualifiedIssuer;
        this.commissionType = commissionType;
        this.commissionValue = commissionValue;
        this.issuerCommissionsMap = issuerCommissionsMap;
        this.userCommissionsMap = userCommissionsMap;
        this.isCustom = isCustom;
        this.terms = terms;
        this.minTransactionAmount = minTransactionAmount;
        this.maxTransactionAmount = maxTransactionAmount;
        this.minRewardAmount = minRewardAmount;
        this.maxRewardAmount = maxRewardAmount;
        this.minUserRewardAmount = minUserRewardAmount;
        this.maxUserRewardAmount = maxUserRewardAmount;
        this.startDate = startDate;
        this.expirationDate = expirationDate;
        this.redeemableOnce = redeemableOnce;
        this.source = source;
        this.validOfferForIssuer = validOfferForIssuer;
        this.category = category;
        this.mcc = mcc;
        this.displayAlways = displayAlways;
        this.audiences = audiences;
        this.segments = segments;
        this.partnerOfferId = partnerOfferId;
        this.isTargeted = isTargeted;
        this.attribution = attribution;
        this.createdDate = createdDate;
        this.lastModified = lastModified;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the offer
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("offerType")
    public Optional<LocationType> getOfferType() {
        return offerType;
    }

    /**
     * @return Merchant Id in Kard's system
     */
    @JsonProperty("merchantId")
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * @return Whether offer is specific to certain locations
     */
    @JsonProperty("isLocationSpecific")
    public Optional<Boolean> getIsLocationSpecific() {
        return isLocationSpecific;
    }

    /**
     * @return Current status of the offer
     */
    @JsonProperty("status")
    public Status getStatus() {
        return status;
    }

    /**
     * @return Network the merchant belongs to
     */
    @JsonProperty("merchantNetwork")
    public String getMerchantNetwork() {
        return merchantNetwork;
    }

    /**
     * @return List of merchant location IDs where offer is valid
     */
    @JsonProperty("merchantLocationIds")
    public Optional<List<String>> getMerchantLocationIds() {
        return merchantLocationIds;
    }

    /**
     * @return Whether user opt-in is required
     */
    @JsonProperty("optInRequired")
    public Optional<Boolean> getOptInRequired() {
        return optInRequired;
    }

    /**
     * @return List of qualified issuer IDs
     */
    @JsonProperty("qualifiedIssuer")
    public List<String> getQualifiedIssuer() {
        return qualifiedIssuer;
    }

    @JsonProperty("commissionType")
    public CommissionType getCommissionType() {
        return commissionType;
    }

    /**
     * @return Commission value
     */
    @JsonProperty("commissionValue")
    public double getCommissionValue() {
        return commissionValue;
    }

    /**
     * @return Commission mapping by issuer
     */
    @JsonProperty("issuerCommissionsMap")
    public Map<String, Double> getIssuerCommissionsMap() {
        return issuerCommissionsMap;
    }

    /**
     * @return User commission mapping
     */
    @JsonProperty("userCommissionsMap")
    public Optional<Map<String, Double>> getUserCommissionsMap() {
        return userCommissionsMap;
    }

    /**
     * @return Whether this is a custom offer
     */
    @JsonProperty("isCustom")
    public Optional<Boolean> getIsCustom() {
        return isCustom;
    }

    /**
     * @return Terms and conditions for the offer
     */
    @JsonProperty("terms")
    public Optional<String> getTerms() {
        return terms;
    }

    /**
     * @return Minimum transaction amount required
     */
    @JsonProperty("minTransactionAmount")
    public Optional<Integer> getMinTransactionAmount() {
        return minTransactionAmount;
    }

    /**
     * @return Maximum transaction amount allowed
     */
    @JsonProperty("maxTransactionAmount")
    public Optional<Integer> getMaxTransactionAmount() {
        return maxTransactionAmount;
    }

    /**
     * @return Minimum reward amount
     */
    @JsonProperty("minRewardAmount")
    public Optional<Integer> getMinRewardAmount() {
        return minRewardAmount;
    }

    /**
     * @return Maximum reward amount
     */
    @JsonProperty("maxRewardAmount")
    public Optional<Integer> getMaxRewardAmount() {
        return maxRewardAmount;
    }

    /**
     * @return Minimum user reward amount
     */
    @JsonProperty("minUserRewardAmount")
    public Optional<Integer> getMinUserRewardAmount() {
        return minUserRewardAmount;
    }

    /**
     * @return Maximum user reward amount
     */
    @JsonProperty("maxUserRewardAmount")
    public Optional<Integer> getMaxUserRewardAmount() {
        return maxUserRewardAmount;
    }

    /**
     * @return When the offer becomes active (ISO 8601 UTC)
     */
    @JsonProperty("startDate")
    public OffsetDateTime getStartDate() {
        return startDate;
    }

    /**
     * @return When the offer expires (ISO 8601 UTC)
     */
    @JsonProperty("expirationDate")
    public OffsetDateTime getExpirationDate() {
        return expirationDate;
    }

    /**
     * @return Whether offer can only be redeemed once per user
     */
    @JsonProperty("redeemableOnce")
    public Optional<Boolean> getRedeemableOnce() {
        return redeemableOnce;
    }

    @JsonProperty("source")
    public Source getSource() {
        return source;
    }

    /**
     * @return Validation mapping by issuer
     */
    @JsonProperty("validOfferForIssuer")
    public Optional<Map<String, Boolean>> getValidOfferForIssuer() {
        return validOfferForIssuer;
    }

    /**
     * @return Category of the offer
     */
    @JsonProperty("category")
    public Optional<String> getCategory() {
        return category;
    }

    /**
     * @return Merchant category codes
     */
    @JsonProperty("mcc")
    public Optional<List<String>> getMcc() {
        return mcc;
    }

    /**
     * @return Whether to always display this offer
     */
    @JsonProperty("displayAlways")
    public Optional<Boolean> getDisplayAlways() {
        return displayAlways;
    }

    /**
     * @return User audiences this offer targets
     */
    @JsonProperty("audiences")
    public Optional<List<String>> getAudiences() {
        return audiences;
    }

    /**
     * @return User segments this offer targets
     */
    @JsonProperty("segments")
    public Optional<List<String>> getSegments() {
        return segments;
    }

    /**
     * @return Partner's offer identifier
     */
    @JsonProperty("partnerOfferId")
    public Optional<String> getPartnerOfferId() {
        return partnerOfferId;
    }

    /**
     * @return If the offer is targeted or not (either has segments or audiences)
     */
    @JsonProperty("isTargeted")
    public boolean getIsTargeted() {
        return isTargeted;
    }

    /**
     * @return Attribution details for the offer
     */
    @JsonProperty("attribution")
    public Attribution getAttribution() {
        return attribution;
    }

    /**
     * @return When the offer was created (ISO 8601 UTC)
     */
    @JsonProperty("createdDate")
    public Optional<OffsetDateTime> getCreatedDate() {
        return createdDate;
    }

    /**
     * @return When the offer was last modified (ISO 8601 UTC)
     */
    @JsonProperty("lastModified")
    public Optional<OffsetDateTime> getLastModified() {
        return lastModified;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OfferAttributes && equalTo((OfferAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OfferAttributes other) {
        return name.equals(other.name)
                && offerType.equals(other.offerType)
                && merchantId.equals(other.merchantId)
                && isLocationSpecific.equals(other.isLocationSpecific)
                && status.equals(other.status)
                && merchantNetwork.equals(other.merchantNetwork)
                && merchantLocationIds.equals(other.merchantLocationIds)
                && optInRequired.equals(other.optInRequired)
                && qualifiedIssuer.equals(other.qualifiedIssuer)
                && commissionType.equals(other.commissionType)
                && commissionValue == other.commissionValue
                && issuerCommissionsMap.equals(other.issuerCommissionsMap)
                && userCommissionsMap.equals(other.userCommissionsMap)
                && isCustom.equals(other.isCustom)
                && terms.equals(other.terms)
                && minTransactionAmount.equals(other.minTransactionAmount)
                && maxTransactionAmount.equals(other.maxTransactionAmount)
                && minRewardAmount.equals(other.minRewardAmount)
                && maxRewardAmount.equals(other.maxRewardAmount)
                && minUserRewardAmount.equals(other.minUserRewardAmount)
                && maxUserRewardAmount.equals(other.maxUserRewardAmount)
                && startDate.equals(other.startDate)
                && expirationDate.equals(other.expirationDate)
                && redeemableOnce.equals(other.redeemableOnce)
                && source.equals(other.source)
                && validOfferForIssuer.equals(other.validOfferForIssuer)
                && category.equals(other.category)
                && mcc.equals(other.mcc)
                && displayAlways.equals(other.displayAlways)
                && audiences.equals(other.audiences)
                && segments.equals(other.segments)
                && partnerOfferId.equals(other.partnerOfferId)
                && isTargeted == other.isTargeted
                && attribution.equals(other.attribution)
                && createdDate.equals(other.createdDate)
                && lastModified.equals(other.lastModified);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.name,
                this.offerType,
                this.merchantId,
                this.isLocationSpecific,
                this.status,
                this.merchantNetwork,
                this.merchantLocationIds,
                this.optInRequired,
                this.qualifiedIssuer,
                this.commissionType,
                this.commissionValue,
                this.issuerCommissionsMap,
                this.userCommissionsMap,
                this.isCustom,
                this.terms,
                this.minTransactionAmount,
                this.maxTransactionAmount,
                this.minRewardAmount,
                this.maxRewardAmount,
                this.minUserRewardAmount,
                this.maxUserRewardAmount,
                this.startDate,
                this.expirationDate,
                this.redeemableOnce,
                this.source,
                this.validOfferForIssuer,
                this.category,
                this.mcc,
                this.displayAlways,
                this.audiences,
                this.segments,
                this.partnerOfferId,
                this.isTargeted,
                this.attribution,
                this.createdDate,
                this.lastModified);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Name of the offer</p>
         */
        MerchantIdStage name(@NotNull String name);

        Builder from(OfferAttributes other);
    }

    public interface MerchantIdStage {
        /**
         * <p>Merchant Id in Kard's system</p>
         */
        StatusStage merchantId(@NotNull String merchantId);
    }

    public interface StatusStage {
        /**
         * <p>Current status of the offer</p>
         */
        MerchantNetworkStage status(@NotNull Status status);
    }

    public interface MerchantNetworkStage {
        /**
         * <p>Network the merchant belongs to</p>
         */
        CommissionTypeStage merchantNetwork(@NotNull String merchantNetwork);
    }

    public interface CommissionTypeStage {
        CommissionValueStage commissionType(@NotNull CommissionType commissionType);
    }

    public interface CommissionValueStage {
        /**
         * <p>Commission value</p>
         */
        StartDateStage commissionValue(double commissionValue);
    }

    public interface StartDateStage {
        /**
         * <p>When the offer becomes active (ISO 8601 UTC)</p>
         */
        ExpirationDateStage startDate(@NotNull OffsetDateTime startDate);
    }

    public interface ExpirationDateStage {
        /**
         * <p>When the offer expires (ISO 8601 UTC)</p>
         */
        SourceStage expirationDate(@NotNull OffsetDateTime expirationDate);
    }

    public interface SourceStage {
        IsTargetedStage source(@NotNull Source source);
    }

    public interface IsTargetedStage {
        /**
         * <p>If the offer is targeted or not (either has segments or audiences)</p>
         */
        AttributionStage isTargeted(boolean isTargeted);
    }

    public interface AttributionStage {
        /**
         * <p>Attribution details for the offer</p>
         */
        _FinalStage attribution(@NotNull Attribution attribution);
    }

    public interface _FinalStage {
        OfferAttributes build();

        _FinalStage offerType(Optional<LocationType> offerType);

        _FinalStage offerType(LocationType offerType);

        /**
         * <p>Whether offer is specific to certain locations</p>
         */
        _FinalStage isLocationSpecific(Optional<Boolean> isLocationSpecific);

        _FinalStage isLocationSpecific(Boolean isLocationSpecific);

        /**
         * <p>List of merchant location IDs where offer is valid</p>
         */
        _FinalStage merchantLocationIds(Optional<List<String>> merchantLocationIds);

        _FinalStage merchantLocationIds(List<String> merchantLocationIds);

        /**
         * <p>Whether user opt-in is required</p>
         */
        _FinalStage optInRequired(Optional<Boolean> optInRequired);

        _FinalStage optInRequired(Boolean optInRequired);

        /**
         * <p>List of qualified issuer IDs</p>
         */
        _FinalStage qualifiedIssuer(List<String> qualifiedIssuer);

        _FinalStage addQualifiedIssuer(String qualifiedIssuer);

        _FinalStage addAllQualifiedIssuer(List<String> qualifiedIssuer);

        /**
         * <p>Commission mapping by issuer</p>
         */
        _FinalStage issuerCommissionsMap(Map<String, Double> issuerCommissionsMap);

        _FinalStage putAllIssuerCommissionsMap(Map<String, Double> issuerCommissionsMap);

        _FinalStage issuerCommissionsMap(String key, Double value);

        /**
         * <p>User commission mapping</p>
         */
        _FinalStage userCommissionsMap(Optional<Map<String, Double>> userCommissionsMap);

        _FinalStage userCommissionsMap(Map<String, Double> userCommissionsMap);

        /**
         * <p>Whether this is a custom offer</p>
         */
        _FinalStage isCustom(Optional<Boolean> isCustom);

        _FinalStage isCustom(Boolean isCustom);

        /**
         * <p>Terms and conditions for the offer</p>
         */
        _FinalStage terms(Optional<String> terms);

        _FinalStage terms(String terms);

        /**
         * <p>Minimum transaction amount required</p>
         */
        _FinalStage minTransactionAmount(Optional<Integer> minTransactionAmount);

        _FinalStage minTransactionAmount(Integer minTransactionAmount);

        /**
         * <p>Maximum transaction amount allowed</p>
         */
        _FinalStage maxTransactionAmount(Optional<Integer> maxTransactionAmount);

        _FinalStage maxTransactionAmount(Integer maxTransactionAmount);

        /**
         * <p>Minimum reward amount</p>
         */
        _FinalStage minRewardAmount(Optional<Integer> minRewardAmount);

        _FinalStage minRewardAmount(Integer minRewardAmount);

        /**
         * <p>Maximum reward amount</p>
         */
        _FinalStage maxRewardAmount(Optional<Integer> maxRewardAmount);

        _FinalStage maxRewardAmount(Integer maxRewardAmount);

        /**
         * <p>Minimum user reward amount</p>
         */
        _FinalStage minUserRewardAmount(Optional<Integer> minUserRewardAmount);

        _FinalStage minUserRewardAmount(Integer minUserRewardAmount);

        /**
         * <p>Maximum user reward amount</p>
         */
        _FinalStage maxUserRewardAmount(Optional<Integer> maxUserRewardAmount);

        _FinalStage maxUserRewardAmount(Integer maxUserRewardAmount);

        /**
         * <p>Whether offer can only be redeemed once per user</p>
         */
        _FinalStage redeemableOnce(Optional<Boolean> redeemableOnce);

        _FinalStage redeemableOnce(Boolean redeemableOnce);

        /**
         * <p>Validation mapping by issuer</p>
         */
        _FinalStage validOfferForIssuer(Optional<Map<String, Boolean>> validOfferForIssuer);

        _FinalStage validOfferForIssuer(Map<String, Boolean> validOfferForIssuer);

        /**
         * <p>Category of the offer</p>
         */
        _FinalStage category(Optional<String> category);

        _FinalStage category(String category);

        /**
         * <p>Merchant category codes</p>
         */
        _FinalStage mcc(Optional<List<String>> mcc);

        _FinalStage mcc(List<String> mcc);

        /**
         * <p>Whether to always display this offer</p>
         */
        _FinalStage displayAlways(Optional<Boolean> displayAlways);

        _FinalStage displayAlways(Boolean displayAlways);

        /**
         * <p>User audiences this offer targets</p>
         */
        _FinalStage audiences(Optional<List<String>> audiences);

        _FinalStage audiences(List<String> audiences);

        /**
         * <p>User segments this offer targets</p>
         */
        _FinalStage segments(Optional<List<String>> segments);

        _FinalStage segments(List<String> segments);

        /**
         * <p>Partner's offer identifier</p>
         */
        _FinalStage partnerOfferId(Optional<String> partnerOfferId);

        _FinalStage partnerOfferId(String partnerOfferId);

        /**
         * <p>When the offer was created (ISO 8601 UTC)</p>
         */
        _FinalStage createdDate(Optional<OffsetDateTime> createdDate);

        _FinalStage createdDate(OffsetDateTime createdDate);

        /**
         * <p>When the offer was last modified (ISO 8601 UTC)</p>
         */
        _FinalStage lastModified(Optional<OffsetDateTime> lastModified);

        _FinalStage lastModified(OffsetDateTime lastModified);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements NameStage,
                    MerchantIdStage,
                    StatusStage,
                    MerchantNetworkStage,
                    CommissionTypeStage,
                    CommissionValueStage,
                    StartDateStage,
                    ExpirationDateStage,
                    SourceStage,
                    IsTargetedStage,
                    AttributionStage,
                    _FinalStage {
        private String name;

        private String merchantId;

        private Status status;

        private String merchantNetwork;

        private CommissionType commissionType;

        private double commissionValue;

        private OffsetDateTime startDate;

        private OffsetDateTime expirationDate;

        private Source source;

        private boolean isTargeted;

        private Attribution attribution;

        private Optional<OffsetDateTime> lastModified = Optional.empty();

        private Optional<OffsetDateTime> createdDate = Optional.empty();

        private Optional<String> partnerOfferId = Optional.empty();

        private Optional<List<String>> segments = Optional.empty();

        private Optional<List<String>> audiences = Optional.empty();

        private Optional<Boolean> displayAlways = Optional.empty();

        private Optional<List<String>> mcc = Optional.empty();

        private Optional<String> category = Optional.empty();

        private Optional<Map<String, Boolean>> validOfferForIssuer = Optional.empty();

        private Optional<Boolean> redeemableOnce = Optional.empty();

        private Optional<Integer> maxUserRewardAmount = Optional.empty();

        private Optional<Integer> minUserRewardAmount = Optional.empty();

        private Optional<Integer> maxRewardAmount = Optional.empty();

        private Optional<Integer> minRewardAmount = Optional.empty();

        private Optional<Integer> maxTransactionAmount = Optional.empty();

        private Optional<Integer> minTransactionAmount = Optional.empty();

        private Optional<String> terms = Optional.empty();

        private Optional<Boolean> isCustom = Optional.empty();

        private Optional<Map<String, Double>> userCommissionsMap = Optional.empty();

        private Map<String, Double> issuerCommissionsMap = new LinkedHashMap<>();

        private List<String> qualifiedIssuer = new ArrayList<>();

        private Optional<Boolean> optInRequired = Optional.empty();

        private Optional<List<String>> merchantLocationIds = Optional.empty();

        private Optional<Boolean> isLocationSpecific = Optional.empty();

        private Optional<LocationType> offerType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OfferAttributes other) {
            name(other.getName());
            offerType(other.getOfferType());
            merchantId(other.getMerchantId());
            isLocationSpecific(other.getIsLocationSpecific());
            status(other.getStatus());
            merchantNetwork(other.getMerchantNetwork());
            merchantLocationIds(other.getMerchantLocationIds());
            optInRequired(other.getOptInRequired());
            qualifiedIssuer(other.getQualifiedIssuer());
            commissionType(other.getCommissionType());
            commissionValue(other.getCommissionValue());
            issuerCommissionsMap(other.getIssuerCommissionsMap());
            userCommissionsMap(other.getUserCommissionsMap());
            isCustom(other.getIsCustom());
            terms(other.getTerms());
            minTransactionAmount(other.getMinTransactionAmount());
            maxTransactionAmount(other.getMaxTransactionAmount());
            minRewardAmount(other.getMinRewardAmount());
            maxRewardAmount(other.getMaxRewardAmount());
            minUserRewardAmount(other.getMinUserRewardAmount());
            maxUserRewardAmount(other.getMaxUserRewardAmount());
            startDate(other.getStartDate());
            expirationDate(other.getExpirationDate());
            redeemableOnce(other.getRedeemableOnce());
            source(other.getSource());
            validOfferForIssuer(other.getValidOfferForIssuer());
            category(other.getCategory());
            mcc(other.getMcc());
            displayAlways(other.getDisplayAlways());
            audiences(other.getAudiences());
            segments(other.getSegments());
            partnerOfferId(other.getPartnerOfferId());
            isTargeted(other.getIsTargeted());
            attribution(other.getAttribution());
            createdDate(other.getCreatedDate());
            lastModified(other.getLastModified());
            return this;
        }

        /**
         * <p>Name of the offer</p>
         * <p>Name of the offer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public MerchantIdStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Merchant Id in Kard's system</p>
         * <p>Merchant Id in Kard's system</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("merchantId")
        public StatusStage merchantId(@NotNull String merchantId) {
            this.merchantId = Objects.requireNonNull(merchantId, "merchantId must not be null");
            return this;
        }

        /**
         * <p>Current status of the offer</p>
         * <p>Current status of the offer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public MerchantNetworkStage status(@NotNull Status status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>Network the merchant belongs to</p>
         * <p>Network the merchant belongs to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("merchantNetwork")
        public CommissionTypeStage merchantNetwork(@NotNull String merchantNetwork) {
            this.merchantNetwork = Objects.requireNonNull(merchantNetwork, "merchantNetwork must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("commissionType")
        public CommissionValueStage commissionType(@NotNull CommissionType commissionType) {
            this.commissionType = Objects.requireNonNull(commissionType, "commissionType must not be null");
            return this;
        }

        /**
         * <p>Commission value</p>
         * <p>Commission value</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("commissionValue")
        public StartDateStage commissionValue(double commissionValue) {
            this.commissionValue = commissionValue;
            return this;
        }

        /**
         * <p>When the offer becomes active (ISO 8601 UTC)</p>
         * <p>When the offer becomes active (ISO 8601 UTC)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("startDate")
        public ExpirationDateStage startDate(@NotNull OffsetDateTime startDate) {
            this.startDate = Objects.requireNonNull(startDate, "startDate must not be null");
            return this;
        }

        /**
         * <p>When the offer expires (ISO 8601 UTC)</p>
         * <p>When the offer expires (ISO 8601 UTC)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("expirationDate")
        public SourceStage expirationDate(@NotNull OffsetDateTime expirationDate) {
            this.expirationDate = Objects.requireNonNull(expirationDate, "expirationDate must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("source")
        public IsTargetedStage source(@NotNull Source source) {
            this.source = Objects.requireNonNull(source, "source must not be null");
            return this;
        }

        /**
         * <p>If the offer is targeted or not (either has segments or audiences)</p>
         * <p>If the offer is targeted or not (either has segments or audiences)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("isTargeted")
        public AttributionStage isTargeted(boolean isTargeted) {
            this.isTargeted = isTargeted;
            return this;
        }

        /**
         * <p>Attribution details for the offer</p>
         * <p>Attribution details for the offer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("attribution")
        public _FinalStage attribution(@NotNull Attribution attribution) {
            this.attribution = Objects.requireNonNull(attribution, "attribution must not be null");
            return this;
        }

        /**
         * <p>When the offer was last modified (ISO 8601 UTC)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lastModified(OffsetDateTime lastModified) {
            this.lastModified = Optional.ofNullable(lastModified);
            return this;
        }

        /**
         * <p>When the offer was last modified (ISO 8601 UTC)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "lastModified", nulls = Nulls.SKIP)
        public _FinalStage lastModified(Optional<OffsetDateTime> lastModified) {
            this.lastModified = lastModified;
            return this;
        }

        /**
         * <p>When the offer was created (ISO 8601 UTC)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdDate(OffsetDateTime createdDate) {
            this.createdDate = Optional.ofNullable(createdDate);
            return this;
        }

        /**
         * <p>When the offer was created (ISO 8601 UTC)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "createdDate", nulls = Nulls.SKIP)
        public _FinalStage createdDate(Optional<OffsetDateTime> createdDate) {
            this.createdDate = createdDate;
            return this;
        }

        /**
         * <p>Partner's offer identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage partnerOfferId(String partnerOfferId) {
            this.partnerOfferId = Optional.ofNullable(partnerOfferId);
            return this;
        }

        /**
         * <p>Partner's offer identifier</p>
         */
        @java.lang.Override
        @JsonSetter(value = "partnerOfferId", nulls = Nulls.SKIP)
        public _FinalStage partnerOfferId(Optional<String> partnerOfferId) {
            this.partnerOfferId = partnerOfferId;
            return this;
        }

        /**
         * <p>User segments this offer targets</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage segments(List<String> segments) {
            this.segments = Optional.ofNullable(segments);
            return this;
        }

        /**
         * <p>User segments this offer targets</p>
         */
        @java.lang.Override
        @JsonSetter(value = "segments", nulls = Nulls.SKIP)
        public _FinalStage segments(Optional<List<String>> segments) {
            this.segments = segments;
            return this;
        }

        /**
         * <p>User audiences this offer targets</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage audiences(List<String> audiences) {
            this.audiences = Optional.ofNullable(audiences);
            return this;
        }

        /**
         * <p>User audiences this offer targets</p>
         */
        @java.lang.Override
        @JsonSetter(value = "audiences", nulls = Nulls.SKIP)
        public _FinalStage audiences(Optional<List<String>> audiences) {
            this.audiences = audiences;
            return this;
        }

        /**
         * <p>Whether to always display this offer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage displayAlways(Boolean displayAlways) {
            this.displayAlways = Optional.ofNullable(displayAlways);
            return this;
        }

        /**
         * <p>Whether to always display this offer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "displayAlways", nulls = Nulls.SKIP)
        public _FinalStage displayAlways(Optional<Boolean> displayAlways) {
            this.displayAlways = displayAlways;
            return this;
        }

        /**
         * <p>Merchant category codes</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage mcc(List<String> mcc) {
            this.mcc = Optional.ofNullable(mcc);
            return this;
        }

        /**
         * <p>Merchant category codes</p>
         */
        @java.lang.Override
        @JsonSetter(value = "mcc", nulls = Nulls.SKIP)
        public _FinalStage mcc(Optional<List<String>> mcc) {
            this.mcc = mcc;
            return this;
        }

        /**
         * <p>Category of the offer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage category(String category) {
            this.category = Optional.ofNullable(category);
            return this;
        }

        /**
         * <p>Category of the offer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "category", nulls = Nulls.SKIP)
        public _FinalStage category(Optional<String> category) {
            this.category = category;
            return this;
        }

        /**
         * <p>Validation mapping by issuer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage validOfferForIssuer(Map<String, Boolean> validOfferForIssuer) {
            this.validOfferForIssuer = Optional.ofNullable(validOfferForIssuer);
            return this;
        }

        /**
         * <p>Validation mapping by issuer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "validOfferForIssuer", nulls = Nulls.SKIP)
        public _FinalStage validOfferForIssuer(Optional<Map<String, Boolean>> validOfferForIssuer) {
            this.validOfferForIssuer = validOfferForIssuer;
            return this;
        }

        /**
         * <p>Whether offer can only be redeemed once per user</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage redeemableOnce(Boolean redeemableOnce) {
            this.redeemableOnce = Optional.ofNullable(redeemableOnce);
            return this;
        }

        /**
         * <p>Whether offer can only be redeemed once per user</p>
         */
        @java.lang.Override
        @JsonSetter(value = "redeemableOnce", nulls = Nulls.SKIP)
        public _FinalStage redeemableOnce(Optional<Boolean> redeemableOnce) {
            this.redeemableOnce = redeemableOnce;
            return this;
        }

        /**
         * <p>Maximum user reward amount</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxUserRewardAmount(Integer maxUserRewardAmount) {
            this.maxUserRewardAmount = Optional.ofNullable(maxUserRewardAmount);
            return this;
        }

        /**
         * <p>Maximum user reward amount</p>
         */
        @java.lang.Override
        @JsonSetter(value = "maxUserRewardAmount", nulls = Nulls.SKIP)
        public _FinalStage maxUserRewardAmount(Optional<Integer> maxUserRewardAmount) {
            this.maxUserRewardAmount = maxUserRewardAmount;
            return this;
        }

        /**
         * <p>Minimum user reward amount</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage minUserRewardAmount(Integer minUserRewardAmount) {
            this.minUserRewardAmount = Optional.ofNullable(minUserRewardAmount);
            return this;
        }

        /**
         * <p>Minimum user reward amount</p>
         */
        @java.lang.Override
        @JsonSetter(value = "minUserRewardAmount", nulls = Nulls.SKIP)
        public _FinalStage minUserRewardAmount(Optional<Integer> minUserRewardAmount) {
            this.minUserRewardAmount = minUserRewardAmount;
            return this;
        }

        /**
         * <p>Maximum reward amount</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxRewardAmount(Integer maxRewardAmount) {
            this.maxRewardAmount = Optional.ofNullable(maxRewardAmount);
            return this;
        }

        /**
         * <p>Maximum reward amount</p>
         */
        @java.lang.Override
        @JsonSetter(value = "maxRewardAmount", nulls = Nulls.SKIP)
        public _FinalStage maxRewardAmount(Optional<Integer> maxRewardAmount) {
            this.maxRewardAmount = maxRewardAmount;
            return this;
        }

        /**
         * <p>Minimum reward amount</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage minRewardAmount(Integer minRewardAmount) {
            this.minRewardAmount = Optional.ofNullable(minRewardAmount);
            return this;
        }

        /**
         * <p>Minimum reward amount</p>
         */
        @java.lang.Override
        @JsonSetter(value = "minRewardAmount", nulls = Nulls.SKIP)
        public _FinalStage minRewardAmount(Optional<Integer> minRewardAmount) {
            this.minRewardAmount = minRewardAmount;
            return this;
        }

        /**
         * <p>Maximum transaction amount allowed</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage maxTransactionAmount(Integer maxTransactionAmount) {
            this.maxTransactionAmount = Optional.ofNullable(maxTransactionAmount);
            return this;
        }

        /**
         * <p>Maximum transaction amount allowed</p>
         */
        @java.lang.Override
        @JsonSetter(value = "maxTransactionAmount", nulls = Nulls.SKIP)
        public _FinalStage maxTransactionAmount(Optional<Integer> maxTransactionAmount) {
            this.maxTransactionAmount = maxTransactionAmount;
            return this;
        }

        /**
         * <p>Minimum transaction amount required</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage minTransactionAmount(Integer minTransactionAmount) {
            this.minTransactionAmount = Optional.ofNullable(minTransactionAmount);
            return this;
        }

        /**
         * <p>Minimum transaction amount required</p>
         */
        @java.lang.Override
        @JsonSetter(value = "minTransactionAmount", nulls = Nulls.SKIP)
        public _FinalStage minTransactionAmount(Optional<Integer> minTransactionAmount) {
            this.minTransactionAmount = minTransactionAmount;
            return this;
        }

        /**
         * <p>Terms and conditions for the offer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage terms(String terms) {
            this.terms = Optional.ofNullable(terms);
            return this;
        }

        /**
         * <p>Terms and conditions for the offer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "terms", nulls = Nulls.SKIP)
        public _FinalStage terms(Optional<String> terms) {
            this.terms = terms;
            return this;
        }

        /**
         * <p>Whether this is a custom offer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage isCustom(Boolean isCustom) {
            this.isCustom = Optional.ofNullable(isCustom);
            return this;
        }

        /**
         * <p>Whether this is a custom offer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "isCustom", nulls = Nulls.SKIP)
        public _FinalStage isCustom(Optional<Boolean> isCustom) {
            this.isCustom = isCustom;
            return this;
        }

        /**
         * <p>User commission mapping</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage userCommissionsMap(Map<String, Double> userCommissionsMap) {
            this.userCommissionsMap = Optional.ofNullable(userCommissionsMap);
            return this;
        }

        /**
         * <p>User commission mapping</p>
         */
        @java.lang.Override
        @JsonSetter(value = "userCommissionsMap", nulls = Nulls.SKIP)
        public _FinalStage userCommissionsMap(Optional<Map<String, Double>> userCommissionsMap) {
            this.userCommissionsMap = userCommissionsMap;
            return this;
        }

        /**
         * <p>Commission mapping by issuer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage issuerCommissionsMap(String key, Double value) {
            this.issuerCommissionsMap.put(key, value);
            return this;
        }

        /**
         * <p>Commission mapping by issuer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllIssuerCommissionsMap(Map<String, Double> issuerCommissionsMap) {
            if (issuerCommissionsMap != null) {
                this.issuerCommissionsMap.putAll(issuerCommissionsMap);
            }
            return this;
        }

        /**
         * <p>Commission mapping by issuer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "issuerCommissionsMap", nulls = Nulls.SKIP)
        public _FinalStage issuerCommissionsMap(Map<String, Double> issuerCommissionsMap) {
            this.issuerCommissionsMap.clear();
            if (issuerCommissionsMap != null) {
                this.issuerCommissionsMap.putAll(issuerCommissionsMap);
            }
            return this;
        }

        /**
         * <p>List of qualified issuer IDs</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllQualifiedIssuer(List<String> qualifiedIssuer) {
            if (qualifiedIssuer != null) {
                this.qualifiedIssuer.addAll(qualifiedIssuer);
            }
            return this;
        }

        /**
         * <p>List of qualified issuer IDs</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addQualifiedIssuer(String qualifiedIssuer) {
            this.qualifiedIssuer.add(qualifiedIssuer);
            return this;
        }

        /**
         * <p>List of qualified issuer IDs</p>
         */
        @java.lang.Override
        @JsonSetter(value = "qualifiedIssuer", nulls = Nulls.SKIP)
        public _FinalStage qualifiedIssuer(List<String> qualifiedIssuer) {
            this.qualifiedIssuer.clear();
            if (qualifiedIssuer != null) {
                this.qualifiedIssuer.addAll(qualifiedIssuer);
            }
            return this;
        }

        /**
         * <p>Whether user opt-in is required</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage optInRequired(Boolean optInRequired) {
            this.optInRequired = Optional.ofNullable(optInRequired);
            return this;
        }

        /**
         * <p>Whether user opt-in is required</p>
         */
        @java.lang.Override
        @JsonSetter(value = "optInRequired", nulls = Nulls.SKIP)
        public _FinalStage optInRequired(Optional<Boolean> optInRequired) {
            this.optInRequired = optInRequired;
            return this;
        }

        /**
         * <p>List of merchant location IDs where offer is valid</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage merchantLocationIds(List<String> merchantLocationIds) {
            this.merchantLocationIds = Optional.ofNullable(merchantLocationIds);
            return this;
        }

        /**
         * <p>List of merchant location IDs where offer is valid</p>
         */
        @java.lang.Override
        @JsonSetter(value = "merchantLocationIds", nulls = Nulls.SKIP)
        public _FinalStage merchantLocationIds(Optional<List<String>> merchantLocationIds) {
            this.merchantLocationIds = merchantLocationIds;
            return this;
        }

        /**
         * <p>Whether offer is specific to certain locations</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage isLocationSpecific(Boolean isLocationSpecific) {
            this.isLocationSpecific = Optional.ofNullable(isLocationSpecific);
            return this;
        }

        /**
         * <p>Whether offer is specific to certain locations</p>
         */
        @java.lang.Override
        @JsonSetter(value = "isLocationSpecific", nulls = Nulls.SKIP)
        public _FinalStage isLocationSpecific(Optional<Boolean> isLocationSpecific) {
            this.isLocationSpecific = isLocationSpecific;
            return this;
        }

        @java.lang.Override
        public _FinalStage offerType(LocationType offerType) {
            this.offerType = Optional.ofNullable(offerType);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "offerType", nulls = Nulls.SKIP)
        public _FinalStage offerType(Optional<LocationType> offerType) {
            this.offerType = offerType;
            return this;
        }

        @java.lang.Override
        public OfferAttributes build() {
            return new OfferAttributes(
                    name,
                    offerType,
                    merchantId,
                    isLocationSpecific,
                    status,
                    merchantNetwork,
                    merchantLocationIds,
                    optInRequired,
                    qualifiedIssuer,
                    commissionType,
                    commissionValue,
                    issuerCommissionsMap,
                    userCommissionsMap,
                    isCustom,
                    terms,
                    minTransactionAmount,
                    maxTransactionAmount,
                    minRewardAmount,
                    maxRewardAmount,
                    minUserRewardAmount,
                    maxUserRewardAmount,
                    startDate,
                    expirationDate,
                    redeemableOnce,
                    source,
                    validOfferForIssuer,
                    category,
                    mcc,
                    displayAlways,
                    audiences,
                    segments,
                    partnerOfferId,
                    isTargeted,
                    attribution,
                    createdDate,
                    lastModified,
                    additionalProperties);
        }
    }
}
