/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.attributions.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import com.kard.api.resources.attributions.types.InternalAttributionType;
import com.kard.api.resources.attributions.types.InternalEventCode;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InternalGetAttributionsRequest.Builder.class)
public final class InternalGetAttributionsRequest {
    private final Optional<InternalAttributionType> filterType;

    private final Optional<String> filterEntityId;

    private final Optional<InternalEventCode> filterEventCode;

    private final Optional<OffsetDateTime> filterStartDate;

    private final Optional<OffsetDateTime> filterEndDate;

    private final Optional<String> pageAfter;

    private final Optional<String> pageBefore;

    private final Optional<Integer> pageSize;

    private final Map<String, Object> additionalProperties;

    private InternalGetAttributionsRequest(
            Optional<InternalAttributionType> filterType,
            Optional<String> filterEntityId,
            Optional<InternalEventCode> filterEventCode,
            Optional<OffsetDateTime> filterStartDate,
            Optional<OffsetDateTime> filterEndDate,
            Optional<String> pageAfter,
            Optional<String> pageBefore,
            Optional<Integer> pageSize,
            Map<String, Object> additionalProperties) {
        this.filterType = filterType;
        this.filterEntityId = filterEntityId;
        this.filterEventCode = filterEventCode;
        this.filterStartDate = filterStartDate;
        this.filterEndDate = filterEndDate;
        this.pageAfter = pageAfter;
        this.pageBefore = pageBefore;
        this.pageSize = pageSize;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Filter by attribution type (offerAttribution or notificationAttribution)
     */
    @JsonProperty("filter[type]")
    public Optional<InternalAttributionType> getFilterType() {
        return filterType;
    }

    /**
     * @return Filter by entity ID
     */
    @JsonProperty("filter[entityId]")
    public Optional<String> getFilterEntityId() {
        return filterEntityId;
    }

    /**
     * @return Filter by event code (IMPRESSION or VIEW)
     */
    @JsonProperty("filter[eventCode]")
    public Optional<InternalEventCode> getFilterEventCode() {
        return filterEventCode;
    }

    /**
     * @return Filter attributions after this date (ISO 8601 format)
     */
    @JsonProperty("filter[startDate]")
    public Optional<OffsetDateTime> getFilterStartDate() {
        return filterStartDate;
    }

    /**
     * @return Filter attributions before this date (ISO 8601 format)
     */
    @JsonProperty("filter[endDate]")
    public Optional<OffsetDateTime> getFilterEndDate() {
        return filterEndDate;
    }

    /**
     * @return Cursor for forward pagination (next page).
     */
    @JsonProperty("page[after]")
    public Optional<String> getPageAfter() {
        return pageAfter;
    }

    /**
     * @return Cursor for backward pagination (previous page).
     */
    @JsonProperty("page[before]")
    public Optional<String> getPageBefore() {
        return pageBefore;
    }

    /**
     * @return Number of items per page. Defaults to 10 if not specified and maximum value allowed 100 items per page.
     */
    @JsonProperty("page[size]")
    public Optional<Integer> getPageSize() {
        return pageSize;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InternalGetAttributionsRequest && equalTo((InternalGetAttributionsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InternalGetAttributionsRequest other) {
        return filterType.equals(other.filterType)
                && filterEntityId.equals(other.filterEntityId)
                && filterEventCode.equals(other.filterEventCode)
                && filterStartDate.equals(other.filterStartDate)
                && filterEndDate.equals(other.filterEndDate)
                && pageAfter.equals(other.pageAfter)
                && pageBefore.equals(other.pageBefore)
                && pageSize.equals(other.pageSize);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.filterType,
                this.filterEntityId,
                this.filterEventCode,
                this.filterStartDate,
                this.filterEndDate,
                this.pageAfter,
                this.pageBefore,
                this.pageSize);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<InternalAttributionType> filterType = Optional.empty();

        private Optional<String> filterEntityId = Optional.empty();

        private Optional<InternalEventCode> filterEventCode = Optional.empty();

        private Optional<OffsetDateTime> filterStartDate = Optional.empty();

        private Optional<OffsetDateTime> filterEndDate = Optional.empty();

        private Optional<String> pageAfter = Optional.empty();

        private Optional<String> pageBefore = Optional.empty();

        private Optional<Integer> pageSize = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(InternalGetAttributionsRequest other) {
            filterType(other.getFilterType());
            filterEntityId(other.getFilterEntityId());
            filterEventCode(other.getFilterEventCode());
            filterStartDate(other.getFilterStartDate());
            filterEndDate(other.getFilterEndDate());
            pageAfter(other.getPageAfter());
            pageBefore(other.getPageBefore());
            pageSize(other.getPageSize());
            return this;
        }

        /**
         * <p>Filter by attribution type (offerAttribution or notificationAttribution)</p>
         */
        @JsonSetter(value = "filter[type]", nulls = Nulls.SKIP)
        public Builder filterType(Optional<InternalAttributionType> filterType) {
            this.filterType = filterType;
            return this;
        }

        public Builder filterType(InternalAttributionType filterType) {
            this.filterType = Optional.ofNullable(filterType);
            return this;
        }

        /**
         * <p>Filter by entity ID</p>
         */
        @JsonSetter(value = "filter[entityId]", nulls = Nulls.SKIP)
        public Builder filterEntityId(Optional<String> filterEntityId) {
            this.filterEntityId = filterEntityId;
            return this;
        }

        public Builder filterEntityId(String filterEntityId) {
            this.filterEntityId = Optional.ofNullable(filterEntityId);
            return this;
        }

        /**
         * <p>Filter by event code (IMPRESSION or VIEW)</p>
         */
        @JsonSetter(value = "filter[eventCode]", nulls = Nulls.SKIP)
        public Builder filterEventCode(Optional<InternalEventCode> filterEventCode) {
            this.filterEventCode = filterEventCode;
            return this;
        }

        public Builder filterEventCode(InternalEventCode filterEventCode) {
            this.filterEventCode = Optional.ofNullable(filterEventCode);
            return this;
        }

        /**
         * <p>Filter attributions after this date (ISO 8601 format)</p>
         */
        @JsonSetter(value = "filter[startDate]", nulls = Nulls.SKIP)
        public Builder filterStartDate(Optional<OffsetDateTime> filterStartDate) {
            this.filterStartDate = filterStartDate;
            return this;
        }

        public Builder filterStartDate(OffsetDateTime filterStartDate) {
            this.filterStartDate = Optional.ofNullable(filterStartDate);
            return this;
        }

        /**
         * <p>Filter attributions before this date (ISO 8601 format)</p>
         */
        @JsonSetter(value = "filter[endDate]", nulls = Nulls.SKIP)
        public Builder filterEndDate(Optional<OffsetDateTime> filterEndDate) {
            this.filterEndDate = filterEndDate;
            return this;
        }

        public Builder filterEndDate(OffsetDateTime filterEndDate) {
            this.filterEndDate = Optional.ofNullable(filterEndDate);
            return this;
        }

        /**
         * <p>Cursor for forward pagination (next page).</p>
         */
        @JsonSetter(value = "page[after]", nulls = Nulls.SKIP)
        public Builder pageAfter(Optional<String> pageAfter) {
            this.pageAfter = pageAfter;
            return this;
        }

        public Builder pageAfter(String pageAfter) {
            this.pageAfter = Optional.ofNullable(pageAfter);
            return this;
        }

        /**
         * <p>Cursor for backward pagination (previous page).</p>
         */
        @JsonSetter(value = "page[before]", nulls = Nulls.SKIP)
        public Builder pageBefore(Optional<String> pageBefore) {
            this.pageBefore = pageBefore;
            return this;
        }

        public Builder pageBefore(String pageBefore) {
            this.pageBefore = Optional.ofNullable(pageBefore);
            return this;
        }

        /**
         * <p>Number of items per page. Defaults to 10 if not specified and maximum value allowed 100 items per page.</p>
         */
        @JsonSetter(value = "page[size]", nulls = Nulls.SKIP)
        public Builder pageSize(Optional<Integer> pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        public Builder pageSize(Integer pageSize) {
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        public InternalGetAttributionsRequest build() {
            return new InternalGetAttributionsRequest(
                    filterType,
                    filterEntityId,
                    filterEventCode,
                    filterStartDate,
                    filterEndDate,
                    pageAfter,
                    pageBefore,
                    pageSize,
                    additionalProperties);
        }
    }
}
