/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.users.rewards;

import com.kard.api.core.ClientOptions;
import com.kard.api.core.RequestOptions;
import com.kard.api.resources.users.rewards.requests.GetLocationsByUserRequest;
import com.kard.api.resources.users.rewards.requests.GetOffersByPlacementRequest;
import com.kard.api.resources.users.rewards.requests.GetOffersByUserRequest;
import com.kard.api.resources.users.rewards.types.LocationsResponseObject;
import com.kard.api.resources.users.rewards.types.OffersResponseObject;

public class RewardsClient {
    protected final ClientOptions clientOptions;

    private final RawRewardsClient rawClient;

    public RewardsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawRewardsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawRewardsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve national brand offers that a specified user is eligible for. Call this endpoint to build out your
     * <a href="/2024-10-01/api/getting-started#b-discover-a-lapsed-customer-clo">targeted offers UX experience</a>. Local offers details
     * can be found by calling the <a href="/2024-10-01/api/rewards/locations">Get Eligible Locations</a>.<br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public OffersResponseObject offers(String organizationId, String userId) {
        return this.rawClient.offers(organizationId, userId).body();
    }

    /**
     * Retrieve national brand offers that a specified user is eligible for. Call this endpoint to build out your
     * <a href="/2024-10-01/api/getting-started#b-discover-a-lapsed-customer-clo">targeted offers UX experience</a>. Local offers details
     * can be found by calling the <a href="/2024-10-01/api/rewards/locations">Get Eligible Locations</a>.<br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public OffersResponseObject offers(String organizationId, String userId, RequestOptions requestOptions) {
        return this.rawClient.offers(organizationId, userId, requestOptions).body();
    }

    /**
     * Retrieve national brand offers that a specified user is eligible for. Call this endpoint to build out your
     * <a href="/2024-10-01/api/getting-started#b-discover-a-lapsed-customer-clo">targeted offers UX experience</a>. Local offers details
     * can be found by calling the <a href="/2024-10-01/api/rewards/locations">Get Eligible Locations</a>.<br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public OffersResponseObject offers(String organizationId, String userId, GetOffersByUserRequest request) {
        return this.rawClient.offers(organizationId, userId, request).body();
    }

    /**
     * Retrieve national brand offers that a specified user is eligible for. Call this endpoint to build out your
     * <a href="/2024-10-01/api/getting-started#b-discover-a-lapsed-customer-clo">targeted offers UX experience</a>. Local offers details
     * can be found by calling the <a href="/2024-10-01/api/rewards/locations">Get Eligible Locations</a>.<br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public OffersResponseObject offers(
            String organizationId, String userId, GetOffersByUserRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .offers(organizationId, userId, request, requestOptions)
                .body();
    }

    /**
     * Retrieve offers for a placement slot. Returns offers sorted by highest cash back,
     * limited by the placement's available slots.<br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public OffersResponseObject placementOffers(String organizationId, String userId, String placementId) {
        return this.rawClient
                .placementOffers(organizationId, userId, placementId)
                .body();
    }

    /**
     * Retrieve offers for a placement slot. Returns offers sorted by highest cash back,
     * limited by the placement's available slots.<br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public OffersResponseObject placementOffers(
            String organizationId, String userId, String placementId, RequestOptions requestOptions) {
        return this.rawClient
                .placementOffers(organizationId, userId, placementId, requestOptions)
                .body();
    }

    /**
     * Retrieve offers for a placement slot. Returns offers sorted by highest cash back,
     * limited by the placement's available slots.<br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public OffersResponseObject placementOffers(
            String organizationId, String userId, String placementId, GetOffersByPlacementRequest request) {
        return this.rawClient
                .placementOffers(organizationId, userId, placementId, request)
                .body();
    }

    /**
     * Retrieve offers for a placement slot. Returns offers sorted by highest cash back,
     * limited by the placement's available slots.<br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public OffersResponseObject placementOffers(
            String organizationId,
            String userId,
            String placementId,
            GetOffersByPlacementRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .placementOffers(organizationId, userId, placementId, request, requestOptions)
                .body();
    }

    /**
     * Retrieve national and local geographic locations that a specified user has eligible in-store offers at. Use this endpoint to build
     * out your <a href="/2024-10-01/api/getting-started#c-discover-clos-near-you-map-view">map-specific UX experiences</a>. Please note
     * that Longitude and Latitude fields are prioritized over State, City and Zipcode and are the recommended search
     * pattern.<br/>
     * <br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public LocationsResponseObject locations(String organizationId, String userId) {
        return this.rawClient.locations(organizationId, userId).body();
    }

    /**
     * Retrieve national and local geographic locations that a specified user has eligible in-store offers at. Use this endpoint to build
     * out your <a href="/2024-10-01/api/getting-started#c-discover-clos-near-you-map-view">map-specific UX experiences</a>. Please note
     * that Longitude and Latitude fields are prioritized over State, City and Zipcode and are the recommended search
     * pattern.<br/>
     * <br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public LocationsResponseObject locations(String organizationId, String userId, RequestOptions requestOptions) {
        return this.rawClient.locations(organizationId, userId, requestOptions).body();
    }

    /**
     * Retrieve national and local geographic locations that a specified user has eligible in-store offers at. Use this endpoint to build
     * out your <a href="/2024-10-01/api/getting-started#c-discover-clos-near-you-map-view">map-specific UX experiences</a>. Please note
     * that Longitude and Latitude fields are prioritized over State, City and Zipcode and are the recommended search
     * pattern.<br/>
     * <br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public LocationsResponseObject locations(String organizationId, String userId, GetLocationsByUserRequest request) {
        return this.rawClient.locations(organizationId, userId, request).body();
    }

    /**
     * Retrieve national and local geographic locations that a specified user has eligible in-store offers at. Use this endpoint to build
     * out your <a href="/2024-10-01/api/getting-started#c-discover-clos-near-you-map-view">map-specific UX experiences</a>. Please note
     * that Longitude and Latitude fields are prioritized over State, City and Zipcode and are the recommended search
     * pattern.<br/>
     * <br/>
     * <b>Required scopes:</b> <code>rewards:read</code>
     */
    public LocationsResponseObject locations(
            String organizationId, String userId, GetLocationsByUserRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .locations(organizationId, userId, request, requestOptions)
                .body();
    }
}
