/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AuditEventEntityType {
    public static final AuditEventEntityType OFFER = new AuditEventEntityType(Value.OFFER, "offer");

    private final Value value;

    private final String string;

    AuditEventEntityType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AuditEventEntityType && this.string.equals(((AuditEventEntityType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OFFER:
                return visitor.visitOffer();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AuditEventEntityType valueOf(String value) {
        switch (value) {
            case "offer":
                return OFFER;
            default:
                return new AuditEventEntityType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OFFER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOffer();

        T visitUnknown(String unknownType);
    }
}
