/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = JobResponse.Builder.class)
public final class JobResponse {
    private final String type;

    private final String id;

    private final Job attributes;

    private final Map<String, Object> additionalProperties;

    private JobResponse(String type, String id, Job attributes, Map<String, Object> additionalProperties) {
        this.type = type;
        this.id = id;
        this.attributes = attributes;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public String getType() {
        return type;
    }

    /**
     * @return The request id of the pending job
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("attributes")
    public Job getAttributes() {
        return attributes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof JobResponse && equalTo((JobResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(JobResponse other) {
        return type.equals(other.type) && id.equals(other.id) && attributes.equals(other.attributes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.id, this.attributes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        IdStage type(@NotNull String type);

        Builder from(JobResponse other);
    }

    public interface IdStage {
        /**
         * <p>The request id of the pending job</p>
         */
        AttributesStage id(@NotNull String id);
    }

    public interface AttributesStage {
        _FinalStage attributes(@NotNull Job attributes);
    }

    public interface _FinalStage {
        JobResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, IdStage, AttributesStage, _FinalStage {
        private String type;

        private String id;

        private Job attributes;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(JobResponse other) {
            type(other.getType());
            id(other.getId());
            attributes(other.getAttributes());
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public IdStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>The request id of the pending job</p>
         * <p>The request id of the pending job</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public AttributesStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("attributes")
        public _FinalStage attributes(@NotNull Job attributes) {
            this.attributes = Objects.requireNonNull(attributes, "attributes must not be null");
            return this;
        }

        @java.lang.Override
        public JobResponse build() {
            return new JobResponse(type, id, attributes, additionalProperties);
        }
    }
}
