/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LocationType {
    public static final LocationType INSTORE = new LocationType(Value.INSTORE, "INSTORE");

    private final Value value;

    private final String string;

    LocationType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof LocationType && this.string.equals(((LocationType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case INSTORE:
                return visitor.visitInstore();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LocationType valueOf(String value) {
        switch (value) {
            case "INSTORE":
                return INSTORE;
            default:
                return new LocationType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        INSTORE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitInstore();

        T visitUnknown(String unknownType);
    }
}
