/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.kard.api.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kard.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProgressBarLabels.Builder.class)
public final class ProgressBarLabels {
    private final Optional<ProgressBarLabelPair> details;

    private final ProgressBarLabelPair default_;

    private final Map<String, Object> additionalProperties;

    private ProgressBarLabels(
            Optional<ProgressBarLabelPair> details,
            ProgressBarLabelPair default_,
            Map<String, Object> additionalProperties) {
        this.details = details;
        this.default_ = default_;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Label configuration for the details view
     */
    @JsonProperty("details")
    public Optional<ProgressBarLabelPair> getDetails() {
        return details;
    }

    /**
     * @return Label configuration for the default view
     */
    @JsonProperty("default")
    public ProgressBarLabelPair getDefault() {
        return default_;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProgressBarLabels && equalTo((ProgressBarLabels) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProgressBarLabels other) {
        return details.equals(other.details) && default_.equals(other.default_);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.details, this.default_);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DefaultStage builder() {
        return new Builder();
    }

    public interface DefaultStage {
        /**
         * <p>Label configuration for the default view</p>
         */
        _FinalStage default_(@NotNull ProgressBarLabelPair default_);

        Builder from(ProgressBarLabels other);
    }

    public interface _FinalStage {
        ProgressBarLabels build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Label configuration for the details view</p>
         */
        _FinalStage details(Optional<ProgressBarLabelPair> details);

        _FinalStage details(ProgressBarLabelPair details);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DefaultStage, _FinalStage {
        private ProgressBarLabelPair default_;

        private Optional<ProgressBarLabelPair> details = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProgressBarLabels other) {
            details(other.getDetails());
            default_(other.getDefault());
            return this;
        }

        /**
         * <p>Label configuration for the default view</p>
         * <p>Label configuration for the default view</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("default")
        public _FinalStage default_(@NotNull ProgressBarLabelPair default_) {
            this.default_ = Objects.requireNonNull(default_, "default_ must not be null");
            return this;
        }

        /**
         * <p>Label configuration for the details view</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage details(ProgressBarLabelPair details) {
            this.details = Optional.ofNullable(details);
            return this;
        }

        /**
         * <p>Label configuration for the details view</p>
         */
        @java.lang.Override
        @JsonSetter(value = "details", nulls = Nulls.SKIP)
        public _FinalStage details(Optional<ProgressBarLabelPair> details) {
            this.details = details;
            return this;
        }

        @java.lang.Override
        public ProgressBarLabels build() {
            return new ProgressBarLabels(details, default_, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
